// Example people, so Terreno has a neighbourhood from the first visit. They're
// made up (and say so on their pages); the places they love are real.
import type { Profile, Spot, SpotKind } from "./model";

const s = (id: string, name: string, kind: SpotKind, lat: number, lon: number, where: string, country: string, note?: string): Spot =>
  ({ id, name, kind, lon, lat, where, country, note });

export const DEMO_PROFILES: Profile[] = [
  {
    handle: "maya", name: "Maya Chen", role: "student", demo: true, skin: "2006",
    avatar: { emoji: "🦉", color: "#bf5af2" },
    now: "Counting shorebirds for my science fair project",
    bio: "Year 11 in Vancouver. I keep a list of every bird I've seen (212 so far). The Fraser River delta is the best place on Earth in October, fight me.\n\nI made the Birdwatching lens: tap any park or wetland and it tells you what's been seen there lately and whether the weather's any good for it.",
    home: { name: "Vancouver, Canada", lon: -123.1207, lat: 49.2827 },
    banner: { lon: -123.1786, lat: 49.0986 },
    spots: [
      s("m1", "Reifel Migratory Bird Sanctuary", "wild", 49.0986, -123.1786, "Delta, British Columbia", "Canada", "Snow geese by the thousand in November. Bring seed for the chickadees."),
      s("m2", "Stanley Park", "park", 49.3043, -123.1443, "Vancouver", "Canada", "The seawall at 7am, before the bikes."),
      s("m3", "Jericho Beach", "beach", 49.2722, -123.1966, "Vancouver", "Canada", "Herons stand in the shallows here like they're waiting for a bus."),
      s("m4", "Granville Island Public Market", "market", 49.2712, -123.134, "Vancouver", "Canada", "Doughnuts after birding. It's the rule."),
      s("m5", "Lighthouse Park", "trail", 49.3363, -123.2632, "West Vancouver", "Canada", "Old-growth Douglas firs and eagles over the rocks."),
      s("m6", "Queen Elizabeth Park", "view", 49.2418, -123.1126, "Vancouver", "Canada", "Highest point in the city. Hummingbirds in the quarry garden."),
      s("m7", "Burns Bog", "wild", 49.125, -122.96, "Delta, British Columbia", "Canada", "A raised peat bog about 3,000 years in the making. Sandhill cranes nest here."),
      s("m8", "Museum of Anthropology", "museum", 49.2694, -123.2593, "UBC, Vancouver", "Canada"),
      s("m9", "Boundary Bay", "wild", 49.0417, -123.0317, "Delta, British Columbia", "Canada", "Owls in winter. Stay on the dike."),
    ],
    top: ["m1", "m2", "m7", "m3", "m5", "m6", "m9", "m4"],
    posts: [
      { id: "mp1", at: "2026-09-21", title: "The snow geese are back!!", body: "First flock over Reifel this morning, maybe 400. They fly in from Wrangel Island in Russia, which is 4,000 km away. I looked it up on the globe and the line goes right over the Bering Strait.", spot: "m1" },
      { id: "mp2", at: "2026-08-30", title: "Bog day", body: "Our class went to Burns Bog. It took about 3,000 years to grow, and the peat is metres deep, full of stored carbon. Also I got bitten by nine mosquitoes.", spot: "m7" },
    ],
    lenses: ["birdwatching"],
    guestbook: [
      { from: "msokafor", name: "Ada Okafor", text: "Maya, your snow geese post is going in my Year 9 migration lesson. Brilliant.", at: "2026-09-22" },
      { from: "kenjiskies", name: "Kenji Watanabe", text: "212 birds! I can't name more than 10.", at: "2026-09-12" },
    ],
    joined: "2026-03-04",
  },
  {
    handle: "msokafor", name: "Ada Okafor", role: "teacher", demo: true, skin: "paper",
    avatar: { emoji: "🌋", color: "#ff9f0a" },
    now: "Planning a field trip to the Seven Sisters chalk cliffs",
    bio: "Geography teacher in south London. I use Terreno to show my students that the ground under their feet has a story: chalk that was sea floor, a river that used to be somewhere else, a barrier that keeps the Thames out of their homes.\n\nMy lessons and quizzes are in Teach. Ask me about rocks. Actually, don't.",
    home: { name: "London, United Kingdom", lon: -0.1276, lat: 51.5072 },
    banner: { lon: 0.0368, lat: 51.4966 },
    spots: [
      s("o1", "Royal Observatory Greenwich", "view", 51.4769, -0.0005, "Greenwich, London", "United Kingdom", "Stand on the Prime Meridian: one foot in each hemisphere."),
      s("o2", "Thames Barrier", "view", 51.4966, 0.0368, "Woolwich, London", "United Kingdom", "Closed over 200 times since 1982. My favourite thing to explain."),
      s("o3", "Natural History Museum", "museum", 51.4967, -0.1764, "South Kensington, London", "United Kingdom", "The earthquake room, every year."),
      s("o4", "Seven Sisters Country Park", "trail", 50.77, 0.148, "East Sussex", "United Kingdom", "Chalk from the shells of tiny sea creatures, 90 million years old."),
      s("o5", "Hampstead Heath", "park", 51.5608, -0.1631, "London", "United Kingdom", "Parliament Hill for the view across the whole city."),
      s("o6", "Borough Market", "market", 51.5055, -0.091, "Southwark, London", "United Kingdom"),
      s("o7", "Kew Gardens", "park", 51.4787, -0.2956, "Richmond, London", "United Kingdom", "The Temperate House: plants from every continent in one glasshouse."),
      s("o8", "British Museum", "museum", 51.5194, -0.127, "Bloomsbury, London", "United Kingdom"),
    ],
    top: ["o4", "o2", "o1", "o3", "o7", "o5", "o8", "o6"],
    posts: [
      { id: "op1", at: "2026-09-18", title: "Why the Thames Barrier matters more every year", body: "We looked at sea level on the globe with the Sea level lens: at +1 m, Greenwich's riverside goes under. The barrier is designed to last until 2070. My Year 10s had a lot of questions about 2071.", spot: "o2" },
    ],
    lenses: ["rock-detective"],
    guides: [{ id: "thames-geography-walk", title: "A geography day along the Thames", blurb: "My Year 9 field trip: time, water and rock, from the Prime Meridian to the flood barrier.", updated: "2026-09-18", stops: [
      { spot: "o1", time: "9:30", note: "Stand on the Prime Meridian. Longitude 0°: the world's time zones were counted from here for a century. Ask: why a line through Greenwich?" },
      { spot: "o2", time: "11:30", note: "The Thames Barrier: ten steel gates that close against storm surges. Open the Sea level lens and try +1 m." },
      { spot: "o6", time: "13:00", note: "Lunch at Borough Market. Spot the food that came up the river, and how far it travelled." },
      { spot: "o3", time: "14:30", note: "The Natural History Museum: the earthquake room and the rocks gallery. Find the chalk." },
    ] }],
    guestbook: [
      { from: "maya", name: "Maya Chen", text: "The chalk cliffs lesson is so good. Can you do one on bogs?", at: "2026-09-19" },
    ],
    joined: "2026-01-12",
  },
  {
    handle: "samoutside", name: "Sam Rivera", role: "explorer", demo: true, skin: "desert",
    avatar: { emoji: "🏔️", color: "#ff375f" },
    now: "Twenty-nine of Colorado's 58 fourteeners done",
    bio: "Trail runner, map nerd, bad at sleeping in. Most weekends I'm somewhere above the treeline in Colorado. I use A day here to plan for the light: where the sun rises over a ridge, and when a valley goes dark.",
    home: { name: "Denver, Colorado", lon: -104.9903, lat: 39.7392 },
    banner: { lon: -106.989, lat: 39.0708 },
    spots: [
      s("s1", "Maroon Bells", "view", 39.0708, -106.989, "Aspen, Colorado", "United States", "Sunrise in late September when the aspens are gold. Worth the 4am alarm."),
      s("s2", "Pikes Peak", "trail", 38.8409, -105.0423, "Colorado Springs", "United States", "The view that inspired 'America the Beautiful'. The doughnuts at the top are famous too."),
      s("s3", "Garden of the Gods", "park", 38.8784, -104.8698, "Colorado Springs", "United States", "Red sandstone fins tipped on end when the Rockies rose."),
      s("s4", "Red Rocks Amphitheatre", "music", 39.6654, -105.2057, "Morrison, Colorado", "United States", "The best-sounding room in the world has no roof."),
      s("s5", "Great Sand Dunes", "sky", 37.7916, -105.5943, "Mosca, Colorado", "United States", "The tallest dunes in North America, and a dark sky park."),
      s("s6", "Hanging Lake", "trail", 39.6014, -107.1917, "Glenwood Canyon", "United States", "Needs a permit. Worth it."),
      s("s7", "Mesa Verde", "museum", 37.2309, -108.4618, "Colorado", "United States", "Cliff dwellings built 800 years ago."),
      s("s8", "The Flatirons", "trail", 39.988, -105.293, "Boulder, Colorado", "United States"),
    ],
    top: ["s1", "s5", "s2", "s3", "s4", "s6", "s7", "s8"],
    posts: [
      { id: "sp1", at: "2026-09-26", title: "Gold week at the Bells", body: "Checked A day here the night before: the sun clears the ridge at 7:04 and lights the face for about 20 minutes. Got there at 6:30. Worth every step.", spot: "s1" },
    ],
    lenses: ["golden-hour"],
    guides: [{ id: "colorado-light", title: "Colorado for the light", blurb: "Five places and the time of day each one is at its best.", updated: "2026-09-26", stops: [
      { spot: "s3", time: "Sunrise", note: "Garden of the Gods at dawn: the red fins light up before anything else." },
      { spot: "s2", time: "Morning", note: "Pikes Peak by the road or the trail. Clouds build by early afternoon in summer, so go up early." },
      { spot: "s1", time: "Sunrise", note: "Maroon Bells. The lake is still at first light, and the reflection is the whole point." },
      { spot: "s5", time: "Night", note: "Great Sand Dunes after dark: a Dark Sky Park. Walk out onto the sand and lie down." },
      { spot: "s4", time: "Evening", note: "Red Rocks for a show. Get there at dusk, with Denver's lights coming on across the plains before the music starts." },
    ] }],
    guestbook: [{ from: "lena.surf", name: "Lena Brandt", text: "Mountains are just waves that stopped. Come to Portugal.", at: "2026-09-02" }],
    joined: "2026-02-20",
  },
  {
    handle: "priya.eats", name: "Priya Nair", role: "explorer", demo: true, skin: "dawn",
    avatar: { emoji: "🌻", color: "#ff9f0a" },
    now: "Eating my way down the Portuguese coast",
    bio: "Food writer based in Lisbon. I think you understand a place best through what grows there and what people cook with it. My Top 8 are where I take friends on their first day in Lisbon.",
    home: { name: "Lisbon, Portugal", lon: -9.1393, lat: 38.7223 },
    banner: { lon: -9.1459, lat: 38.7071 },
    spots: [
      s("p1", "Pastéis de Belém", "cafe", 38.6975, -9.2032, "Belém, Lisbon", "Portugal", "The original custard tart, since 1837. Cinnamon, not sugar."),
      s("p2", "Time Out Market", "market", 38.7071, -9.1459, "Cais do Sodré, Lisbon", "Portugal"),
      s("p3", "Miradouro da Senhora do Monte", "view", 38.7191, -9.1327, "Graça, Lisbon", "Portugal", "The highest viewpoint in the city, at sunset."),
      s("p4", "Alfama", "music", 38.7118, -9.13, "Lisbon", "Portugal", "Fado drifting out of doorways after dark."),
      s("p5", "LX Factory", "market", 38.7036, -9.1784, "Alcântara, Lisbon", "Portugal"),
      s("p6", "Cabo da Roca", "view", 38.7804, -9.4989, "Sintra", "Portugal", "The westernmost point of mainland Europe."),
      s("p7", "Pena Palace", "museum", 38.7876, -9.3906, "Sintra", "Portugal"),
      s("p8", "Praia da Ursa", "beach", 38.789, -9.493, "Sintra", "Portugal", "A steep scramble down. Wild and empty."),
    ],
    top: ["p1", "p3", "p4", "p2", "p6", "p8", "p7", "p5"],
    posts: [
      { id: "pp1", at: "2026-09-10", title: "Why Lisbon tastes like the Atlantic", body: "The Tagus estuary is one of the biggest in Europe, and the cold Canary Current brings sardines up the coast every summer. Everything here comes back to that water.", spot: "p2" },
    ],
    lenses: ["coffee-crawl"],
    guides: [{ id: "lisbon-in-a-day", title: "Lisbon in a day", blurb: "What I do with a friend on their first day: custard tarts, the Atlantic's edge, and fado after dark.", updated: "2026-09-12", stops: [
      { spot: "p1", time: "9:00", note: "Start at Belém before the queues. Two tarts each, warm, with cinnamon. Walk it off along the river." },
      { spot: "p5", time: "11:00", note: "LX Factory under the bridge: a bookshop in an old printworks, and good coffee." },
      { spot: "p2", time: "13:00", note: "Lunch at the market: grilled sardines if it's summer, a bifana if it isn't." },
      { spot: "p6", time: "16:00", note: "Train to Sintra, bus to Cabo da Roca: the westernmost point of mainland Europe. Next stop, America." },
      { spot: "p3", time: "19:30", note: "Back for sunset from Senhora do Monte, the highest viewpoint in the city." },
      { spot: "p4", time: "21:30", note: "Get lost in Alfama until you hear fado through a doorway. Go in." },
    ] }],
    guestbook: [],
    joined: "2026-04-01",
  },
  {
    handle: "kenjiskies", name: "Kenji Watanabe", role: "explorer", demo: true, skin: "night",
    avatar: { emoji: "🌙", color: "#5e5ce6" },
    now: "Waiting for a clear night. Tokyo, please.",
    bio: "Amateur astronomer from Tokyo. I've travelled to see the darkest skies on Earth, and I made the Stargazing lens so you can check any place for darkness, the moon and cloud before you go.",
    home: { name: "Tokyo, Japan", lon: 139.6917, lat: 35.6895 },
    banner: { lon: -155.4681, lat: 19.8207 },
    spots: [
      s("k1", "Mauna Kea summit", "sky", 19.8207, -155.4681, "Hawaii", "United States", "Above 40% of Earth's atmosphere. Bring a jacket, it's freezing."),
      s("k2", "ALMA, Chajnantor plateau", "sky", -23.0293, -67.7549, "Atacama, Chile", "Chile", "The driest desert on Earth: over 300 clear nights a year."),
      s("k3", "Lake Tekapo", "sky", -44.0047, 170.4774, "Aoraki Mackenzie Dark Sky Reserve", "New Zealand", "The Magellanic Clouds over the Church of the Good Shepherd."),
      s("k4", "Roque de los Muchachos", "sky", 28.7564, -17.8917, "La Palma, Canary Islands", "Spain"),
      s("k5", "Tromsø", "sky", 69.6492, 18.9553, "Norway", "Norway", "Aurora season is September to March."),
      s("k6", "Mount Fuji", "trail", 35.3606, 138.7274, "Japan", "Japan", "Climb overnight for sunrise from the summit, goraikō."),
      s("k7", "Uluru", "view", -25.3444, 131.0369, "Northern Territory", "Australia"),
    ],
    top: ["k1", "k2", "k3", "k5", "k4", "k6", "k7"],
    posts: [
      { id: "kp1", at: "2026-08-14", title: "Perseids from Tekapo (in my dreams)", body: "The Perseids peak in August, but they're a northern shower. From New Zealand the radiant in Perseus never even rises. Turn the globe and you can see why: Tekapo is too far south to see that part of the sky.", spot: "k3" },
    ],
    lenses: ["stargazing", "aurora-watch"],
    guestbook: [{ from: "maya", name: "Maya Chen", text: "Owls AND stars, we should be friends", at: "2026-09-13" }],
    joined: "2026-02-02",
  },
  {
    handle: "lena.surf", name: "Lena Brandt", role: "owner", demo: true, skin: "ocean",
    avatar: { emoji: "🌊", color: "#64d2ff" },
    now: "Swell's up at Nazaré this week",
    bio: "I run a small surf school in Ericeira. My Places keeps my boards, bookings and the forecast in one place; my Surf check lens tells students whether tomorrow is a lesson day.",
    home: { name: "Ericeira, Portugal", lon: -9.4167, lat: 38.9667 },
    banner: { lon: -9.071, lat: 39.6021 },
    spots: [
      s("l1", "Nazaré, Praia do Norte", "surf", 39.6021, -9.071, "Portugal", "Portugal", "The Nazaré Canyon focuses the swell into the biggest waves ever surfed."),
      s("l2", "Ribeira d'Ilhas", "surf", 38.9876, -9.4196, "Ericeira", "Portugal", "My home break. A World Surfing Reserve."),
      s("l3", "Hossegor", "surf", 43.665, -1.443, "Landes", "France"),
      s("l4", "Mundaka", "surf", 43.4078, -2.6981, "Basque Country", "Spain", "The river-mouth left, when the sandbar is right."),
      s("l5", "Uluwatu", "surf", -8.815, 115.0875, "Bali", "Indonesia"),
      s("l6", "Jeffreys Bay", "surf", -34.0333, 24.9333, "Eastern Cape", "South Africa"),
      s("l7", "Banzai Pipeline", "surf", 21.665, -158.053, "Oahu, Hawaii", "United States"),
    ],
    top: ["l2", "l1", "l4", "l3", "l6", "l5", "l7"],
    posts: [
      { id: "lp1", at: "2026-09-24", title: "Reading a swell", body: "The Surf check lens pulls the wave height and period from the marine forecast. Period is the secret: 14 seconds from a storm near Iceland beats 8 seconds of local wind chop every time.", spot: "l1" },
    ],
    lenses: ["surf-check"],
    guestbook: [{ from: "samoutside", name: "Sam Rivera", text: "Fine, I'll come. Teach me.", at: "2026-09-03" }],
    joined: "2026-05-11",
  },
];
