// A foothold in every kind of place people look up: national and state
// parks, the big tourist sights, amusement parks, race tracks, the world's
// most celebrated restaurants, fashion houses, great factories and the most
// impressive mines. Each kind is tagged, so a Work line or a lens can find
// its own, and each list is meant to grow.
import type { Fx } from "./fx";
import type { Form, IntroPlace } from "./places";

const P = (id: string, name: string, where: string, lon: number, lat: number, size: number, tags: string[], lines: string[], facts: [string, string][], extra: Partial<IntroPlace> = {}): IntroPlace =>
  ({ id, name, where, lon, lat, size, tags, lines, facts, ...extra });

/** A fairy-tale castle: a keep, turrets with pointed roofs, a tall central spire (metres). */
const castle = (h: number): Form[] => [
  { f: "box", w: h * 0.9, d: h * 0.6, h: h * 0.35 },
  { f: "box", w: h * 0.45, d: h * 0.35, h: h * 0.6 },
  { f: "cyl", r: h * 0.07, h: h * 0.7 }, { f: "cone", r: h * 0.09, h: h * 0.3, z: h * 0.7 },
  ...[[-1, -1], [1, -1], [-1, 1], [1, 1]].flatMap(([sx, sy]): Form[] => [{ f: "cyl", r: h * 0.06, h: h * 0.45, dx: sx * h * 0.42, dy: sy * h * 0.27 }, { f: "cone", r: h * 0.08, h: h * 0.2, dx: sx * h * 0.42, dy: sy * h * 0.27, z: h * 0.45 }]),
];
/** An oval racetrack with a grandstand along one straight (metres). */
const oval = (rx: number, ry: number, stand: number, rot = 0): Form[] => [
  { f: "ring", rx, ry, ix: rx - 25, iy: ry - 25, h: 1.5, rot },
  { f: "stand", rx: rx + 60, ry: ry + 60, ix: rx + 5, iy: ry + 5, h: stand, n: 4, from: 240, to: 300, rot },
];

const bison: Fx = { fx: "herd", n: 90, from: [-5000, -1500], to: [5000, 1800], spread: 2500, size: 60, color: "#4a3b2c", seconds: 40 };

export const FOOTHOLD_INTROS: IntroPlace[] = [
  // ---- National parks -------------------------------------------------------------------------------
  P("zion", "Zion Canyon", "Zion National Park, Utah", -112.9478, 37.269, 8000, ["park", "nature"],
    ["A canyon cut by the Virgin River through Navajo sandstone, its walls up to 600 m high.", "The trail to Angels Landing climbs a fin of rock with drops on both sides."],
    [["National park since", "1919"], ["Angels Landing", "1,765 m"]], { also: ["Zion National Park", "Zion", "Angels Landing"] }),
  P("delicate-arch", "Delicate Arch", "Arches National Park, Utah", -109.4993, 38.7436, 300, ["park", "nature"],
    ["A free-standing sandstone arch about 16 m tall, on Utah's licence plates.", "Arches National Park has more than 2,000 natural arches, more than anywhere else."],
    [["Height", "about 16 m"], ["Arches in the park", "over 2,000"]], { also: ["Arches National Park", "Arches"], forms: [{ f: "arch", span: 10, h: 16, t: 3.5 }] }),
  P("bryce-canyon", "Bryce Canyon", "Utah", -112.1871, 37.6283, 4000, ["park", "nature"],
    ["Not a canyon but a row of amphitheatres filled with hoodoos, spires of eroded limestone.", "Frost splits the rock more than 200 nights a year."],
    [["Rim", "about 2,400–2,700 m"]], { also: ["Bryce Canyon National Park", "Bryce"] }),
  P("acadia", "Cadillac Mountain", "Acadia National Park, Maine", -68.2264, 44.3529, 6000, ["park", "nature"],
    ["The highest point on the US Atlantic coast, and from October to March the first place in the country to see the sunrise.", "Acadia was the first national park east of the Mississippi."],
    [["Summit", "466 m"]], { also: ["Acadia National Park", "Acadia"] }),
  P("joshua-tree", "Joshua Tree", "California", -116.1, 33.95, 12000, ["park", "nature"],
    ["Where the Mojave and Colorado deserts meet, among granite boulders.", "The Joshua tree is a yucca, not a tree; Mormon settlers named it after the prophet raising his arms."],
    [["National park since", "1994"]], { also: ["Joshua Tree National Park"] }),
  P("badwater", "Badwater Basin", "Death Valley, California", -116.8253, 36.2297, 20000, ["park", "nature"],
    ["The lowest point in North America, 86 m below sea level, a crust of salt flats.", "Furnace Creek nearby recorded 56.7 °C in 1913."],
    [["Below sea level", "86 m"], ["Record heat", "56.7 °C"]], { also: ["Death Valley", "Death Valley National Park"] }),
  P("grand-teton", "Grand Teton", "Wyoming", -110.8024, 43.741, 16000, ["park", "nature"],
    ["A range that rises straight from the valley floor with no foothills, along a fault that is still moving.", "Jackson Hole lies at its feet."],
    [["Grand Teton", "4,199 m"]], { also: ["Grand Teton National Park", "Tetons"] }),
  P("badlands", "Badlands", "South Dakota", -102.3398, 43.7491, 10000, ["park", "nature"],
    ["Eroded buttes and pinnacles banded in colour, and one of the richest fossil beds in the world.", "Bison and prairie dogs live on the grassland around them."],
    [["National park since", "1978"]], { also: ["Badlands National Park"], fx: [bison] }),
  P("kruger", "Kruger National Park", "South Africa", 31.5, -24.0, 40000, ["park", "nature", "wildlife"],
    ["One of Africa's largest game reserves, about 19,500 km², home of the Big Five.", "Proclaimed in 1926, it grew out of the Sabi Game Reserve of 1898."],
    [["Area", "about 19,500 km²"]], { also: ["Kruger"], fx: [{ fx: "herd", n: 40, from: [-15000, 8000], to: [15000, -6000], spread: 6000, size: 280, color: "#6b6b6b", seconds: 60 }] }),
  P("etosha", "Etosha Pan", "Namibia", 16.0, -18.8, 60000, ["park", "nature", "wildlife"],
    ["A salt pan so large it can be seen from space, dry most of the year.", "In the dry season animals gather at the waterholes around its edge."],
    [["Pan", "about 4,800 km²"]], { also: ["Etosha National Park", "Etosha"] }),
  P("snowdon", "Yr Wyddfa (Snowdon)", "Eryri, Wales", -4.0763, 53.0685, 6000, ["park", "nature"],
    ["The highest mountain in Wales, in the national park of Eryri (Snowdonia).", "A rack railway has climbed to the summit since 1896."],
    [["Summit", "1,085 m"]], { also: ["Snowdon", "Snowdonia", "Eryri"] }),
  // ---- State parks ----------------------------------------------------------------------------------
  P("custer-state-park", "Custer State Park", "Black Hills, South Dakota", -103.45, 43.73, 15000, ["park", "nature", "wildlife"],
    ["Home to one of the largest public bison herds in the world, about 1,400 animals.", "Each September riders drive the herd in the Buffalo Roundup."],
    [["Bison", "about 1,400"]], { also: ["Custer State Park Buffalo Roundup"], fx: [bison] }),
  P("valley-of-fire", "Valley of Fire", "Nevada", -114.53, 36.43, 6000, ["park", "nature"],
    ["Red Aztec sandstone that seems to burn in the sun, and rock art 2,000 years old.", "Nevada's oldest state park, opened in 1935."],
    [["State park since", "1935"]], { also: ["Valley of Fire State Park"] }),
  P("letchworth", "Letchworth State Park", "New York", -78.051, 42.58, 4000, ["park", "nature"],
    ["The Grand Canyon of the East: the Genesee River runs through a gorge up to about 170 m deep, over three major falls.", "A rail bridge crosses high over the Upper Falls."],
    [["Major falls", "3"]], { also: ["Letchworth"] }),
  P("watkins-glen", "Watkins Glen State Park", "New York", -76.873, 42.3725, 1200, ["park", "nature"],
    ["A gorge with 19 waterfalls in about 3 km, its trail passing behind and under them.", "Rainbow Falls is the one people photograph."],
    [["Waterfalls", "19"]], { also: ["Watkins Glen"] }),
  P("antelope-canyon", "Antelope Canyon", "Navajo Nation, Arizona", -111.3743, 36.8619, 400, ["park", "nature"],
    ["A slot canyon carved by flash floods through sandstone, lit by shafts of light at midday.", "It is on Navajo land and visited only with a Navajo guide."],
    [["Upper canyon depth", "about 37 m"]], { also: ["Upper Antelope Canyon", "Lower Antelope Canyon"] }),
  P("horseshoe-bend", "Horseshoe Bend", "Page, Arizona", -111.5104, 36.8791, 1500, ["park", "nature"],
    ["The Colorado River swings in a near-full loop about 300 m below the rim.", "Glen Canyon Dam is just upstream."],
    [["Drop to the river", "about 300 m"]]),
  P("mcway-falls", "McWay Falls", "Big Sur, California", -121.6719, 36.1578, 800, ["park", "nature"],
    ["A waterfall that drops about 24 m onto a beach in a cove, in Julia Pfeiffer Burns State Park.", "Until landslides in 1983 built up the beach, it fell straight into the Pacific."],
    [["Drop", "about 24 m"]], { also: ["Big Sur", "Julia Pfeiffer Burns State Park"] }),
  P("dead-horse-point", "Dead Horse Point", "Utah", -109.7406, 38.4706, 4000, ["park", "nature"],
    ["An overlook about 600 m above a gooseneck of the Colorado River.", "The last scene of Thelma & Louise was filmed nearby."],
    [["Above the river", "about 600 m"]], { also: ["Dead Horse Point State Park"] }),
  P("palo-duro", "Palo Duro Canyon", "Texas", -101.66, 34.94, 16000, ["park", "nature"],
    ["The second-largest canyon in the United States, about 190 km long and up to 240 m deep.", "The Lighthouse, a hoodoo on its rim, is its emblem."],
    [["Length", "about 190 km"]], { also: ["Palo Duro Canyon State Park"] }),
  P("starved-rock", "Starved Rock", "Illinois", -88.9946, 41.3196, 4000, ["park", "nature"],
    ["Sandstone canyons with waterfalls that freeze into ice falls in winter, on the Illinois River.", "The name comes from a legend of a siege on the rock."],
    [["Canyons", "18"]], { also: ["Starved Rock State Park"] }),
  P("hocking-hills", "Old Man's Cave", "Hocking Hills, Ohio", -82.541, 39.4357, 2000, ["park", "nature"],
    ["A gorge of Blackhand sandstone with falls, caves and hemlock forest.", "It's named after a hermit who lived in the cave in the 1800s."],
    [["State park since", "1949"]], { also: ["Hocking Hills State Park", "Hocking Hills"] }),
  // ---- Tourist sights -------------------------------------------------------------------------------
  P("las-vegas-strip", "Las Vegas Strip", "Las Vegas, Nevada", -115.1728, 36.1147, 3000, ["attraction", "music", "retail"],
    ["About 6.8 km of resort casinos along Las Vegas Boulevard, lit all night.", "Many of the world's largest hotels stand along it."],
    [["Length", "about 6.8 km"]], { also: ["The Strip", "Las Vegas"] }),
  P("bellagio-fountains", "Fountains of Bellagio", "Las Vegas, Nevada", -115.1741, 36.1126, 600, ["attraction", "music"],
    ["Fountains on a lake of about 3 hectares that dance to music, shooting up to about 140 m.", "Shows run every 15 to 30 minutes."],
    [["Highest jets", "about 140 m"]], { also: ["Bellagio"] }),
  P("walk-of-fame", "Hollywood Walk of Fame", "Hollywood, Los Angeles", -118.3417, 34.1016, 900, ["attraction", "art", "music"],
    ["More than 2,700 brass stars set in the pavement of Hollywood Boulevard and Vine Street.", "The first were laid in 1960."],
    [["Stars", "more than 2,700"]], { also: ["Walk of Fame", "Hollywood Boulevard"] }),
  P("central-park", "Central Park", "Manhattan, New York", -73.9654, 40.7829, 5000, ["attraction", "park"],
    ["341 hectares designed by Olmsted and Vaux from 1858, almost all of it made by hand.", "One of the most visited urban parks in the world."],
    [["Area", "341 ha"], ["Begun", "1858"]], { forms: [{ f: "box", w: 800, d: 4000, h: 0.5, rot: -29 }] }),
  P("alcatraz", "Alcatraz Island", "San Francisco Bay", -122.4229, 37.8267, 800, ["attraction"],
    ["A fort, a military prison, and from 1934 to 1963 a federal penitentiary for the most notorious prisoners.", "No escape was ever proven to have succeeded."],
    [["Federal prison", "1934–1963"]], { also: ["Alcatraz"], forms: [{ f: "box", w: 150, d: 40, h: 14 }, { f: "cyl", r: 3, h: 26, dx: 60, dy: 20 }] }),
  P("trevi-fountain", "Trevi Fountain", "Rome, Italy", 12.4833, 41.9009, 300, ["attraction", "art"],
    ["A baroque fountain finished in 1762, where visitors throw a coin over their shoulder to return to Rome.", "The coins, over a million euros a year, go to charity."],
    [["Finished", "1762"], ["Width", "about 49 m"]], { also: ["Fontana di Trevi", "Trevi"], forms: [{ f: "box", w: 49, d: 10, h: 26, dy: 15 }, { f: "box", w: 50, d: 20, h: 1.5 }] }),
  P("pantheon", "Pantheon", "Rome, Italy", 12.4768, 41.8986, 300, ["attraction", "architecture"],
    ["Built about AD 125, its dome is still the largest of unreinforced concrete in the world.", "The 9 m oculus at the top is open to the sky."],
    [["Dome", "43.3 m across"], ["Built", "about AD 125"]], { forms: [{ f: "cyl", r: 21.6, h: 21.6 }, { f: "dome", r: 21.6, h: 21.6, z: 21.6 }, { f: "box", w: 34, d: 16, h: 18, dy: -28 }] }),
  P("spanish-steps", "Spanish Steps", "Rome, Italy", 12.4828, 41.9058, 300, ["attraction", "fashion"],
    ["135 steps of 1725 climbing from Piazza di Spagna to the church of Trinità dei Monti.", "Via Condotti, Rome's fashion street, runs from their foot."],
    [["Steps", "135"]], { also: ["Piazza di Spagna"], forms: [{ f: "steps", w: 40, top: 20, h: 22, n: 10 }, { f: "box", w: 30, d: 15, h: 30, dy: 40 }] }),
  P("sacre-coeur", "Sacré-Cœur", "Montmartre, Paris", 2.3431, 48.8867, 500, ["attraction", "architecture"],
    ["A white basilica on the highest point in Paris, finished in 1914.", "Its stone whitens with rain."],
    [["Dome", "83 m"]], { also: ["Sacre Coeur", "Montmartre"], forms: [{ f: "box", w: 85, d: 35, h: 30 }, { f: "cyl", r: 12, h: 25, z: 20 }, { f: "dome", r: 12, h: 25, z: 45 }, { f: "box", w: 9, d: 9, h: 84, dx: 45 }] }),
  P("moulin-rouge", "Moulin Rouge", "Pigalle, Paris", 2.3323, 48.8841, 400, ["attraction", "music"],
    ["The cabaret of 1889 where the can-can became famous, under its red windmill.", "Toulouse-Lautrec painted its dancers."],
    [["Opened", "1889"]], { forms: [{ f: "box", w: 30, d: 20, h: 14 }, { f: "cyl", r: 3, h: 18, dx: -8 }] }),
  P("buckingham-palace", "Buckingham Palace", "Westminster, London", -0.1419, 51.5014, 600, ["attraction", "architecture"],
    ["The monarch's London home since 1837, with 775 rooms.", "The Changing of the Guard takes place in its forecourt."],
    [["Rooms", "775"]], { forms: [{ f: "ring", rx: 95, ry: 60, ix: 60, iy: 35, h: 24 }, { f: "box", w: 108, d: 16, h: 24, dy: -60 }] }),
  P("british-museum", "British Museum", "Bloomsbury, London", -0.127, 51.5194, 500, ["attraction", "art"],
    ["Founded in 1753, the first national public museum in the world.", "The Rosetta Stone and the Parthenon sculptures are here."],
    [["Founded", "1753"], ["Objects", "about 8 million"]], { forms: [{ f: "ring", rx: 110, ry: 80, ix: 70, iy: 55, h: 22 }, { f: "cyl", r: 23, h: 22 }, { f: "shell", rx: 70, ry: 55, h: 6, z: 22 }] }),
  P("anne-frank-house", "Anne Frank House", "Amsterdam, Netherlands", 4.884, 52.3752, 300, ["attraction"],
    ["Where Anne Frank and her family hid from 1942 to 1944 in the secret annexe behind a bookcase.", "Her diary has been read in some 70 languages."],
    [["In hiding", "1942–1944"]], { forms: [{ f: "box", w: 8, d: 20, h: 18 }] }),
  P("las-ramblas", "La Rambla", "Barcelona, Spain", 2.1734, 41.3809, 1500, ["attraction", "food", "retail"],
    ["A tree-lined promenade of about 1.2 km from Plaça de Catalunya to the old port.", "La Boqueria market opens off it."],
    [["Length", "about 1.2 km"]], { also: ["Las Ramblas", "Rambla"] }),
  P("palm-jumeirah", "Palm Jumeirah", "Dubai, United Arab Emirates", 55.1386, 25.1124, 8000, ["attraction", "architecture"],
    ["An island shaped like a palm tree, built from sand dredged from the Gulf and finished in the 2000s.", "A breakwater crescent protects its fronds."],
    [["Fronds", "16"]], { also: ["The Palm"] }),
  P("merlion", "Merlion Park", "Marina Bay, Singapore", 103.8545, 1.2868, 400, ["attraction"],
    ["A half-lion, half-fish statue spouting water into Marina Bay, Singapore's emblem since 1972.", "The lion is for Singapura, the lion city; the fish for its fishing village past."],
    [["Statue", "8.6 m"]], { also: ["Merlion"] }),
  P("victoria-peak", "Victoria Peak", "Hong Kong", 114.145, 22.2759, 3000, ["attraction"],
    ["The highest hill on Hong Kong Island, with the famous view over the harbour.", "The Peak Tram has climbed it since 1888."],
    [["Height", "552 m"], ["Peak Tram", "1888"]], { also: ["The Peak", "Peak Tram"] }),
  P("senso-ji", "Sensō-ji", "Asakusa, Tokyo", 139.7967, 35.7148, 500, ["attraction", "architecture"],
    ["Tokyo's oldest temple, by tradition founded in 628, entered through the Kaminarimon with its giant red lantern.", "Nakamise street of stalls leads up to it."],
    [["Founded", "628, by tradition"]], { also: ["Senso-ji", "Sensoji", "Asakusa", "Kaminarimon"], forms: [{ f: "box", w: 35, d: 25, h: 14 }, { f: "pyramid", w: 40, h: 14, z: 14 }, { f: "box", w: 10, d: 10, h: 53, dx: -45, dy: -20 }] }),
  P("n-seoul-tower", "N Seoul Tower", "Namsan, Seoul", 126.9882, 37.5512, 800, ["attraction"],
    ["A communications and observation tower on Namsan mountain, opened to the public in 1980.", "Couples leave padlocks on its railings."],
    [["Tower", "236 m"]], { also: ["Namsan Tower", "Seoul Tower"], forms: [{ f: "cyl", r: 6, top: 4, h: 180 }, { f: "cyl", r: 12, h: 18, z: 130 }, { f: "cyl", r: 1, h: 56, z: 180 }] }),
  P("grand-palace-bangkok", "Grand Palace", "Bangkok, Thailand", 100.4913, 13.75, 700, ["attraction", "architecture"],
    ["The royal palace since 1782, with Wat Phra Kaew, the Temple of the Emerald Buddha.", "Its roofs glitter with gold, glass and porcelain."],
    [["Built from", "1782"]], { also: ["Wat Phra Kaew", "Temple of the Emerald Buddha"], forms: [{ f: "ring", rx: 220, ry: 200, ix: 214, iy: 194, h: 6 }, { f: "box", w: 60, d: 30, h: 18, dy: -60 }, { f: "cone", r: 8, h: 45, dx: -60, dy: 60 }] }),
  P("copacabana", "Copacabana", "Rio de Janeiro, Brazil", -43.1873, -22.9711, 4000, ["attraction", "music"],
    ["Four kilometres of beach and the wave-patterned promenade by Roberto Burle Marx.", "Millions gather here for New Year's Eve."],
    [["Beach", "about 4 km"]], { also: ["Copacabana Beach"] }),
  // ---- Amusement parks ------------------------------------------------------------------------------
  P("disneyland", "Disneyland", "Anaheim, California", -117.919, 33.8121, 500, ["amusement", "attraction"],
    ["Walt Disney's first park, opened on 17 July 1955.", "Sleeping Beauty Castle, 23 m tall, is drawn to look taller by forced perspective."],
    [["Opened", "1955"], ["Castle", "23 m"]], { also: ["Disneyland Resort", "Disneyland Park"], forms: castle(23) }),
  P("magic-kingdom", "Magic Kingdom", "Walt Disney World, Florida", -81.5812, 28.4177, 500, ["amusement", "attraction"],
    ["Opened in 1971, the most visited theme park in the world.", "Cinderella Castle rises 57 m at the end of Main Street, U.S.A."],
    [["Opened", "1971"], ["Castle", "57 m"]], { also: ["Walt Disney World", "Disney World", "Cinderella Castle"], forms: castle(57) }),
  P("epcot", "EPCOT", "Walt Disney World, Florida", -81.5494, 28.3747, 500, ["amusement", "attraction", "tech"],
    ["Opened in 1982 as a showcase of the future, with a world fair of eleven nations around a lagoon.", "Spaceship Earth is a geodesic sphere about 50 m across."],
    [["Opened", "1982"], ["Spaceship Earth", "55 m"]], { also: ["Spaceship Earth"], forms: [{ f: "cyl", r: 4, h: 6, dx: -10 }, { f: "cyl", r: 4, h: 6, dx: 10 }, { f: "cyl", r: 4, h: 6, dy: 12 }, { f: "sphere", r: 25, z: 5 }] }),
  P("universal-orlando", "Universal Orlando", "Orlando, Florida", -81.4678, 28.4752, 2500, ["amusement", "attraction", "gaming"],
    ["Theme parks built around films, opened from 1990, with the Wizarding World of Harry Potter.", "Epic Universe opened in 2025."],
    [["First park", "1990"]], { also: ["Universal Studios Florida", "Islands of Adventure"] }),
  P("universal-hollywood", "Universal Studios Hollywood", "Universal City, California", -118.3534, 34.1381, 1500, ["amusement", "attraction"],
    ["A working film studio whose tram tour, started in 1964, grew into a theme park.", "The backlot sets are still used for filming."],
    [["Studio Tour", "since 1964"]], { also: ["Universal Hollywood"] }),
  P("tokyo-disneyland", "Tokyo Disneyland", "Urayasu, Chiba", 139.8807, 35.6329, 500, ["amusement", "attraction"],
    ["The first Disney park outside the United States, opened in 1983.", "Tokyo DisneySea, opened beside it in 2001, is often called the most beautiful theme park."],
    [["Opened", "1983"]], { also: ["Tokyo DisneySea", "Tokyo Disney Resort"], forms: castle(51) }),
  P("disneyland-paris", "Disneyland Paris", "Marne-la-Vallée, France", 2.7758, 48.8722, 500, ["amusement", "attraction"],
    ["Opened in 1992, the most visited theme park in Europe.", "Its castle is Le Château de la Belle au Bois Dormant, Sleeping Beauty's."],
    [["Opened", "1992"]], { forms: castle(45) }),
  P("shanghai-disneyland", "Shanghai Disneyland", "Pudong, Shanghai", 121.667, 31.144, 500, ["amusement", "attraction"],
    ["Opened in 2016, with the tallest of the Disney castles.", "The Enchanted Storybook Castle is about 60 m tall."],
    [["Opened", "2016"]], { forms: castle(60) }),
  P("cedar-point", "Cedar Point", "Sandusky, Ohio", -82.6835, 41.4822, 2500, ["amusement", "attraction"],
    ["The roller coaster capital of the world, on a peninsula in Lake Erie.", "It opened as a bathing beach in 1870."],
    [["Opened", "1870"], ["Roller coasters", "about 17"]], { forms: [{ f: "arch", span: 300, h: 94, t: 3 }, { f: "arch", span: 250, h: 70, t: 3, dx: 300, rot: 60 }] }),
  P("magic-mountain", "Six Flags Magic Mountain", "Valencia, California", -118.597, 34.4253, 1500, ["amusement", "attraction"],
    ["The park with the most roller coasters in the world.", "Its coasters climb the hills of the Santa Clarita Valley."],
    [["Roller coasters", "about 20"]], { also: ["Magic Mountain"] }),
  P("europa-park", "Europa-Park", "Rust, Germany", 7.721, 48.266, 1500, ["amusement", "attraction"],
    ["Germany's largest theme park, opened in 1975, each area themed on a European country.", "Its owners, the Mack family, build rides for parks across the world."],
    [["Opened", "1975"]]),
  P("efteling", "Efteling", "Kaatsheuvel, Netherlands", 5.0499, 51.65, 1500, ["amusement", "attraction"],
    ["A park of fairy tales, opened in 1952 around a fairy-tale forest designed by the illustrator Anton Pieck.", "One of the oldest theme parks in the world."],
    [["Opened", "1952"]]),
  P("tivoli-gardens", "Tivoli Gardens", "Copenhagen, Denmark", 12.5681, 55.6737, 500, ["amusement", "attraction"],
    ["Opened in 1843, one of the oldest amusement parks still running.", "Walt Disney visited and took ideas home for Disneyland."],
    [["Opened", "1843"], ["Rutschebanen coaster", "1914"]], { also: ["Tivoli"] }),
  P("blackpool-pleasure-beach", "Blackpool Pleasure Beach", "Blackpool, England", -3.055, 53.792, 800, ["amusement", "attraction"],
    ["A seaside amusement park opened in 1896, with wooden coasters from the 1920s and 1930s.", "The Big One was the tallest roller coaster in the world when it opened in 1994."],
    [["Opened", "1896"]]),
  P("coney-island", "Coney Island", "Brooklyn, New York", -73.9786, 40.5755, 1200, ["amusement", "attraction", "food"],
    ["New York's seaside playground since the late 1800s: the Cyclone of 1927 and the Wonder Wheel of 1920 still run.", "Nathan's has sold hot dogs here since 1916."],
    [["Cyclone", "1927"], ["Wonder Wheel", "1920"]], { forms: [{ f: "arch", span: 46, h: 46, t: 2 }, { f: "box", w: 120, d: 6, h: 1.5, dx: 150, dy: -30 }] }),
  P("universal-studios-japan", "Universal Studios Japan", "Osaka, Japan", 135.4323, 34.6654, 1500, ["amusement", "attraction", "gaming"],
    ["Opened in 2001 on Osaka Bay.", "Super Nintendo World, opened in 2021, lets you walk into Mario's world."],
    [["Opened", "2001"], ["Super Nintendo World", "2021"]], { also: ["USJ", "Super Nintendo World"] }),
  P("ferrari-world", "Ferrari World", "Yas Island, Abu Dhabi", 54.6072, 24.4837, 1200, ["amusement", "attraction", "racing"],
    ["An indoor park under a red roof of about 200,000 m², opened in 2010.", "Formula Rossa reaches 240 km/h, one of the fastest roller coasters in the world."],
    [["Formula Rossa", "240 km/h"]], { forms: [{ f: "shell", rx: 350, ry: 350, h: 50 }, { f: "cone", r: 60, h: 80 }] }),
  P("portaventura", "PortAventura World", "Salou, Spain", 1.1557, 41.0878, 1500, ["amusement", "attraction"],
    ["Opened in 1995 on the Costa Daurada.", "Red Force launches riders 112 m into the air."],
    [["Opened", "1995"]], { also: ["PortAventura", "Port Aventura"] }),
  P("everland", "Everland", "Yongin, South Korea", 127.2026, 37.2939, 1500, ["amusement", "attraction"],
    ["South Korea's largest theme park, opened in 1976.", "Its wooden coaster T Express drops at 77 degrees."],
    [["Opened", "1976"]]),
  // ---- Race tracks ----------------------------------------------------------------------------------
  P("daytona", "Daytona International Speedway", "Daytona Beach, Florida", -81.0702, 29.1852, 2000, ["racing", "sport"],
    ["A tri-oval of about 4 km with turns banked at 31 degrees, opened in 1959.", "The Daytona 500 opens the NASCAR season."],
    [["Opened", "1959"], ["Banking", "31°"]], { also: ["Daytona 500", "Daytona Speedway"], forms: oval(650, 330, 30) }),
  P("talladega", "Talladega Superspeedway", "Lincoln, Alabama", -86.0664, 33.5671, 2500, ["racing", "sport"],
    ["NASCAR's longest oval, about 4.3 km, with turns banked at 33 degrees.", "Cars run in packs at over 300 km/h."],
    [["Lap", "about 4.28 km"], ["Banking", "33°"]], { also: ["Talladega"], forms: oval(750, 360, 25, 20) }),
  P("le-mans", "Circuit de la Sarthe", "Le Mans, France", 0.2075, 47.9561, 16000, ["racing", "sport"],
    ["Home of the 24 Hours of Le Mans since 1923, most of its 13.6 km on public roads.", "The Mulsanne Straight runs about 6 km."],
    [["Lap", "about 13.6 km"], ["First race", "1923"]], { also: ["Le Mans", "24 Hours of Le Mans"] }),
  P("monaco-gp", "Circuit de Monaco", "Monte Carlo, Monaco", 7.4206, 43.7347, 2000, ["racing", "sport"],
    ["A Grand Prix run through the streets of Monte Carlo since 1929, past the casino and the harbour.", "Its 3.3 km lap is the slowest and narrowest in Formula One."],
    [["Lap", "about 3.3 km"], ["First Grand Prix", "1929"]], { also: ["Monaco Grand Prix", "Monte Carlo"] }),
  P("silverstone", "Silverstone", "Northamptonshire, England", -1.0169, 52.0786, 4000, ["racing", "sport"],
    ["A wartime airfield where the first Formula One World Championship race was held, on 13 May 1950.", "Home of the British Grand Prix."],
    [["First F1 race", "1950"], ["Lap", "about 5.9 km"]], { also: ["British Grand Prix"] }),
  P("monza", "Monza", "Lombardy, Italy", 9.2811, 45.6156, 4000, ["racing", "sport"],
    ["The Temple of Speed, opened in 1922 in a royal park, the fastest track in Formula One.", "Its old banked oval still stands in the trees."],
    [["Opened", "1922"]], { also: ["Autodromo Nazionale Monza", "Italian Grand Prix"] }),
  P("spa", "Spa-Francorchamps", "Ardennes, Belgium", 5.9714, 50.4372, 6000, ["racing", "sport"],
    ["About 7 km through the Ardennes hills, with the climb through Eau Rouge and Raidillon.", "Rain can fall on one part of the track and not another."],
    [["Lap", "about 7 km"]], { also: ["Spa Francorchamps", "Belgian Grand Prix", "Eau Rouge"] }),
  P("nordschleife", "Nürburgring Nordschleife", "Eifel, Germany", 6.9475, 50.3356, 12000, ["racing", "sport"],
    ["About 20.8 km and over 150 corners through the Eifel forest, opened in 1927.", "Jackie Stewart called it the Green Hell; carmakers still test lap times here."],
    [["Lap", "about 20.8 km"], ["Opened", "1927"]], { also: ["Nürburgring", "Nurburgring", "Green Hell"] }),
  P("suzuka", "Suzuka Circuit", "Mie, Japan", 136.5391, 34.8431, 3000, ["racing", "sport"],
    ["A figure-of-eight circuit built by Honda in 1962, the only one in Formula One that crosses itself.", "Next to it is an amusement park with a Ferris wheel."],
    [["Opened", "1962"], ["Lap", "about 5.8 km"]], { also: ["Suzuka", "Japanese Grand Prix"] }),
  P("interlagos", "Interlagos", "São Paulo, Brazil", -46.6997, -23.7036, 3000, ["racing", "sport"],
    ["The Autódromo José Carlos Pace, run anticlockwise between two lakes.", "Ayrton Senna won his home race here in 1991 and 1993."],
    [["Opened", "1940"]], { also: ["Autódromo José Carlos Pace", "Brazilian Grand Prix"] }),
  P("cota", "Circuit of the Americas", "Austin, Texas", -97.6411, 30.1328, 3000, ["racing", "sport"],
    ["Opened in 2012, the first purpose-built Formula One circuit in the United States.", "Turn 1 climbs about 40 m up a steep hill."],
    [["Opened", "2012"]], { also: ["COTA", "United States Grand Prix"] }),
  P("bathurst", "Mount Panorama", "Bathurst, Australia", 149.5552, -33.4472, 3000, ["racing", "sport"],
    ["A public road around a hill, about 6.2 km, closed for the Bathurst 1000 each October.", "The lap climbs and drops about 174 m."],
    [["Lap", "about 6.2 km"]], { also: ["Bathurst", "Bathurst 1000"] }),
  P("yas-marina", "Yas Marina Circuit", "Abu Dhabi, United Arab Emirates", 54.6031, 24.4672, 3000, ["racing", "sport"],
    ["Opened in 2009, with a hotel straddling the track; the race runs from day into night.", "It often hosts the last race of the Formula One season."],
    [["Opened", "2009"]], { also: ["Abu Dhabi Grand Prix"] }),
  P("isle-of-man-tt", "Snaefell Mountain Course", "Isle of Man", -4.48, 54.168, 25000, ["racing", "sport"],
    ["About 60.7 km of public roads, raced by motorcycles in the Isle of Man TT since 1911.", "Riders pass stone walls and houses at over 300 km/h."],
    [["Lap", "about 60.7 km"], ["TT since", "1907"]], { also: ["Isle of Man TT", "TT"] }),
  P("churchill-downs", "Churchill Downs", "Louisville, Kentucky", -85.77, 38.2034, 1200, ["racing", "sport"],
    ["Home of the Kentucky Derby, run on the first Saturday of May since 1875.", "Its twin spires were built in 1895."],
    [["Kentucky Derby", "since 1875"]], { also: ["Kentucky Derby"], forms: [{ f: "ring", rx: 300, ry: 150, ix: 285, iy: 135, h: 0.6 }, { f: "box", w: 250, d: 40, h: 25, dy: -190 }, ...[-12, 12].flatMap((dx): Form[] => [{ f: "box", w: 6, d: 6, h: 28, dx, dy: -190 }, { f: "pyramid", w: 6, h: 8, dx, dy: -190, z: 28 }])] }),
  P("ascot", "Ascot Racecourse", "Berkshire, England", -0.6765, 51.4127, 2000, ["racing", "sport", "fashion"],
    ["Founded by Queen Anne in 1711; Royal Ascot each June is as much about hats as horses.", "The royal procession arrives by carriage."],
    [["Founded", "1711"]], { also: ["Royal Ascot", "Ascot"] }),
  P("flemington", "Flemington Racecourse", "Melbourne, Australia", 144.907, -37.7889, 2000, ["racing", "sport"],
    ["Home of the Melbourne Cup since 1861, the race that stops a nation.", "Its fences are lined with thousands of roses."],
    [["Melbourne Cup", "since 1861"]], { also: ["Melbourne Cup"] }),
  P("longchamp", "ParisLongchamp", "Bois de Boulogne, Paris", 2.2333, 48.8577, 2000, ["racing", "sport"],
    ["Home of the Prix de l'Arc de Triomphe, run each October since 1920.", "The grandstand was rebuilt in 2018."],
    [["The Arc", "since 1920"]], { also: ["Longchamp", "Prix de l'Arc de Triomphe"] }),
  // ---- Celebrated restaurants -----------------------------------------------------------------------
  P("el-celler-de-can-roca", "El Celler de Can Roca", "Girona, Spain", 2.8064, 41.9963, 300, ["food"],
    ["Run by the three Roca brothers, a chef, a sommelier and a pastry chef, beside their parents' restaurant.", "Named the world's best restaurant by The World's 50 Best in 2013 and 2015."],
    [["World's best", "2013, 2015"]], { also: ["Can Roca", "Celler de Can Roca"] }),
  P("noma", "Noma", "Copenhagen, Denmark", 12.6043, 55.683, 300, ["food"],
    ["René Redzepi's restaurant that started the New Nordic movement, foraging and fermenting the North.", "Named the world's best five times; it ended regular service at the end of 2024 to become a food laboratory."],
    [["World's best", "2010–12, 2014, 2021"]], { also: ["noma"] }),
  P("osteria-francescana", "Osteria Francescana", "Modena, Italy", 10.9236, 44.6455, 300, ["food", "art"],
    ["Massimo Bottura's restaurant, where Italian classics are taken apart and remade.", "Named the world's best in 2016 and 2018."],
    [["World's best", "2016, 2018"]], { also: ["Francescana"] }),
  P("french-laundry", "The French Laundry", "Yountville, California", -122.3651, 38.4044, 300, ["food"],
    ["Thomas Keller's restaurant in an old stone laundry in the Napa Valley.", "Named the world's best in 2003 and 2004."],
    [["World's best", "2003, 2004"]], { also: ["French Laundry"] }),
  P("eleven-madison-park", "Eleven Madison Park", "Manhattan, New York", -73.9873, 40.7416, 300, ["food"],
    ["A grand dining room in an Art Deco tower on Madison Square Park.", "Named the world's best in 2017."],
    [["World's best", "2017"]], { also: ["EMP"] }),
  P("central-lima", "Central", "Barranco, Lima", -77.0293, -12.1496, 300, ["food"],
    ["Virgilio Martínez and Pía León cook Peru by altitude, from the sea to the high Andes.", "Named the world's best in 2023."],
    [["World's best", "2023"]], { also: ["Central Restaurante"] }),
  P("disfrutar", "Disfrutar", "Barcelona, Spain", 2.1515, 41.3878, 300, ["food"],
    ["Opened in 2014 by three chefs who met in the kitchen of elBulli.", "Named the world's best in 2024."],
    [["World's best", "2024"]]),
  P("maido", "Maido", "Miraflores, Lima", -77.0303, -12.1243, 300, ["food"],
    ["Mitsuharu Tsumura's Nikkei cooking: Japanese technique with Peruvian produce.", "Named the world's best in 2025."],
    [["World's best", "2025"]]),
  P("geranium", "Geranium", "Copenhagen, Denmark", 12.5722, 55.7032, 300, ["food"],
    ["Rasmus Kofoed's restaurant on the eighth floor of the national football stadium.", "Named the world's best in 2022."],
    [["World's best", "2022"]]),
  P("mirazur", "Mirazur", "Menton, France", 7.5281, 43.7854, 300, ["food"],
    ["Mauro Colagreco's restaurant on the border with Italy, its menus set by the phases of the moon.", "Named the world's best in 2019."],
    [["World's best", "2019"]]),
  P("fat-duck", "The Fat Duck", "Bray, England", -0.7032, 51.5079, 300, ["food"],
    ["Heston Blumenthal's restaurant of kitchen science: snail porridge and sound of the sea.", "Named the world's best in 2005."],
    [["World's best", "2005"]], { also: ["Fat Duck"] }),
  P("elbulli", "elBulli", "Cala Montjoi, Spain", 3.2295, 42.2457, 400, ["food"],
    ["Ferran Adrià's restaurant on a cove of the Costa Brava, where foams and spherification began.", "Named the world's best five times; it closed in 2011."],
    [["World's best", "2002, 2006–09"], ["Closed", "2011"]], { also: ["El Bulli"] }),
  P("botin", "Sobrino de Botín", "Madrid, Spain", -3.7083, 40.414, 200, ["food"],
    ["Founded in 1725, the oldest restaurant in the world still running, says Guinness.", "Its wood oven, roasting suckling pig, has burned for centuries."],
    [["Founded", "1725"]], { also: ["Botín", "Botin"] }),
  P("katzs", "Katz's Delicatessen", "Lower East Side, New York", -73.9874, 40.7223, 200, ["food"],
    ["A deli open since 1888, known for pastrami hand-cut and piled on rye.", "The famous scene in When Harry Met Sally was filmed here."],
    [["Open since", "1888"]], { also: ["Katz's", "Katz's Deli"] }),
  P("peter-luger", "Peter Luger Steak House", "Williamsburg, Brooklyn", -73.9623, 40.7099, 200, ["food"],
    ["A steakhouse in Williamsburg since 1887, ageing its porterhouse in its own rooms.", "For most of its life it took only cash."],
    [["Open since", "1887"]], { also: ["Peter Luger"] }),
  P("paul-bocuse", "L'Auberge du Pont de Collonges", "Lyon, France", 4.8486, 45.8178, 300, ["food"],
    ["Paul Bocuse's restaurant on the Saône, which held three Michelin stars from 1965 to 2020.", "Its truffle soup was made for the French president in 1975."],
    [["Three stars", "1965–2020"]], { also: ["Paul Bocuse", "Bocuse"] }),
  P("sukiyabashi-jiro", "Sukiyabashi Jiro", "Ginza, Tokyo", 139.7639, 35.6719, 200, ["food"],
    ["A ten-seat sushi counter in a Ginza basement, made famous by the film Jiro Dreams of Sushi (2011).", "Jiro Ono was born in 1925."],
    [["Seats", "10"]], { also: ["Jiro", "Jiro Dreams of Sushi"] }),
  P("tour-dargent", "La Tour d'Argent", "Paris, France", 2.3542, 48.8501, 200, ["food"],
    ["A restaurant on the Seine facing Notre-Dame, which claims roots in 1582.", "Each pressed duck it serves is numbered; the count is past a million."],
    [["Ducks numbered since", "1890"]], { also: ["Tour d'Argent"] }),
  P("pujol", "Pujol", "Polanco, Mexico City", -99.1951, 19.4318, 200, ["food"],
    ["Enrique Olvera's restaurant, which brought Mexican cooking to the world's top tables.", "Its mole madre has been aged and fed for thousands of days."],
    [["Opened", "2000"]]),
  // ---- Fashion houses -------------------------------------------------------------------------------
  P("chanel-rue-cambon", "Chanel, 31 Rue Cambon", "Paris, France", 2.3283, 48.8679, 200, ["fashion"],
    ["Coco Chanel's house since 1918: the boutique below, the salons and her apartment above.", "She watched her shows from the top of the mirrored staircase."],
    [["House here since", "1918"]], { also: ["Chanel", "31 Rue Cambon"] }),
  P("hermes-faubourg", "Hermès, 24 Faubourg Saint-Honoré", "Paris, France", 2.3209, 48.8697, 200, ["fashion"],
    ["Founded in 1837 as a harness maker; at this address since 1880.", "Its rooftop horseman holds up a scarf like a flag."],
    [["Founded", "1837"]], { also: ["Hermès", "Hermes"] }),
  P("dior-montaigne", "Dior, 30 Avenue Montaigne", "Paris, France", 2.3045, 48.8661, 200, ["fashion"],
    ["Where Christian Dior showed the New Look in February 1947.", "La Galerie Dior tells the house's story inside."],
    [["New Look", "1947"]], { also: ["Dior", "Christian Dior", "30 Montaigne"] }),
  P("louis-vuitton-asnieres", "Louis Vuitton, Asnières", "Asnières-sur-Seine, France", 2.288, 48.915, 300, ["fashion"],
    ["The trunk workshop Louis Vuitton opened in 1859, where special orders are still made by hand.", "The family house stands beside it."],
    [["Workshop since", "1859"]], { also: ["Louis Vuitton", "LV"] }),
  P("gucci-florence", "Gucci, Florence", "Florence, Italy", 11.2557, 43.7695, 300, ["fashion"],
    ["Guccio Gucci opened a leather shop in Florence in 1921 after working at the Savoy in London.", "Much of its leather is still worked in the hills around Florence."],
    [["Founded", "1921"]], { also: ["Gucci"] }),
  P("fondazione-prada", "Fondazione Prada", "Milan, Italy", 9.2047, 45.4445, 400, ["fashion", "art"],
    ["Prada's art foundation in an old distillery, opened in 2015, with a tower clad in gold leaf.", "Prada began as a leather goods shop in Milan's Galleria in 1913."],
    [["Opened", "2015"]], { also: ["Prada"], forms: [{ f: "box", w: 120, d: 80, h: 12 }, { f: "box", w: 12, d: 12, h: 20, dx: 40 }, { f: "box", w: 20, d: 20, h: 60, dx: -50, dy: 40 }] }),
  P("armani-silos", "Armani/Silos", "Milan, Italy", 9.1666, 45.4518, 300, ["fashion", "art"],
    ["Giorgio Armani's museum of his own work, in a grain store of 1950, opened in 2015.", "Armani founded his company in 1975."],
    [["Opened", "2015"]], { also: ["Armani", "Giorgio Armani"] }),
  P("via-montenapoleone", "Via Montenapoleone", "Milan, Italy", 9.1953, 45.4685, 800, ["fashion", "retail"],
    ["The heart of Milan's Quadrilatero della Moda, the fashion district.", "One of the most expensive shopping streets in the world."],
    [["Length", "about 350 m"]], { also: ["Montenapoleone", "Quadrilatero della Moda"] }),
  P("savile-row", "Savile Row", "Mayfair, London", -0.1413, 51.5108, 500, ["fashion"],
    ["The street of bespoke tailoring since the 1800s.", "The Beatles played their last concert on the roof of No. 3 in 1969."],
    [["Rooftop concert", "1969"]]),
  P("fifth-avenue", "Fifth Avenue", "Manhattan, New York", -73.975, 40.76, 1500, ["fashion", "retail"],
    ["The flagship stores between 49th and 60th streets make it one of the most expensive shopping streets on Earth.", "Tiffany & Co. has stood at 57th Street since 1940."],
    [["Tiffany here since", "1940"]]),
  P("nike-campus", "Nike World Headquarters", "Beaverton, Oregon", -122.8282, 45.5093, 1500, ["fashion", "sport"],
    ["Nike's campus, its buildings named after athletes.", "The company began in 1964 selling running shoes from a car boot."],
    [["Founded", "1964"]], { also: ["Nike", "Nike HQ"] }),
  P("adidas-herzogenaurach", "Adidas, Herzogenaurach", "Bavaria, Germany", 10.9068, 49.5759, 1500, ["fashion", "sport"],
    ["Adidas's home, the town where the Dassler brothers fell out and founded Adidas and Puma.", "The two companies faced each other across the river Aurach."],
    [["Adidas founded", "1949"]], { also: ["Adidas", "Puma", "Herzogenaurach"] }),
  P("inditex-arteixo", "Inditex, Arteixo", "Galicia, Spain", -8.5096, 43.3049, 1500, ["fashion", "retail"],
    ["Headquarters of Inditex, owner of Zara, which designs and ships new clothes to its shops twice a week.", "The first Zara opened in nearby A Coruña in 1975."],
    [["First Zara", "1975"]], { also: ["Zara", "Inditex"] }),
  P("ralph-lauren-rhinelander", "Rhinelander Mansion", "Madison Avenue, New York", -73.966, 40.7714, 200, ["fashion"],
    ["A French Renaissance mansion of 1898, Ralph Lauren's flagship since 1986.", "Lauren founded his company in 1967 with a line of ties."],
    [["Built", "1898"]], { also: ["Ralph Lauren"] }),
  // ---- Great factories ------------------------------------------------------------------------------
  P("boeing-everett", "Boeing Everett Factory", "Everett, Washington", -122.273, 47.922, 2500, ["factory", "tech"],
    ["The largest building in the world by volume, where 747s were built and 767s and 777s still are.", "It has its own fire brigade, banks and a railway spur."],
    [["Volume", "about 13.4 million m³"]], { also: ["Boeing Everett", "Boeing factory"], forms: [{ f: "box", w: 1000, d: 340, h: 35 }] }),
  P("airbus-toulouse", "Airbus, Toulouse", "Blagnac, France", 1.36, 43.648, 3000, ["factory", "tech"],
    ["Final assembly lines for Airbus jets beside Toulouse airport.", "The A380 was assembled in the Jean-Luc Lagardère hall, one of the largest buildings in Europe."],
    [["A380s built", "251"]], { also: ["Airbus"], forms: [{ f: "box", w: 490, d: 250, h: 46 }] }),
  P("vw-wolfsburg", "Volkswagen Wolfsburg", "Wolfsburg, Germany", 10.79, 52.429, 4000, ["factory"],
    ["One of the largest car factories in the world, about 6.5 km² beside the Mittelland Canal.", "Its four brick chimneys are the town's landmark."],
    [["Site", "about 6.5 km²"], ["Opened", "1938"]], { also: ["Volkswagen", "VW Wolfsburg", "Autostadt"], forms: [{ f: "box", w: 1300, d: 200, h: 30 }, ...[0, 1, 2, 3].map((i): Form => ({ f: "cyl", r: 5, h: 80, dx: -300 + i * 120, dy: -110 }))] }),
  P("hyundai-ulsan", "Hyundai Ulsan Plant", "Ulsan, South Korea", 129.378, 35.528, 5000, ["factory"],
    ["The largest single car factory in the world, building up to about 1.4 million cars a year.", "Ships load the cars at its own wharf."],
    [["Capacity", "about 1.4 million cars a year"]], { also: ["Hyundai Ulsan"] }),
  P("river-rouge", "Ford River Rouge Complex", "Dearborn, Michigan", -83.1563, 42.3, 4000, ["factory"],
    ["Henry Ford's plant of 1928: iron ore and coal in at one end, cars out of the other.", "The F-150 is built here now, under a living roof of sedum."],
    [["Finished", "1928"]], { also: ["Ford Rouge", "River Rouge"] }),
  P("giga-texas", "Tesla Gigafactory Texas", "Austin, Texas", -97.617, 30.2223, 3000, ["factory", "tech"],
    ["Opened in 2022, one of the largest factories in the world by floor area, about 1 km².", "It builds the Model Y and the Cybertruck."],
    [["Opened", "2022"]], { also: ["Giga Texas", "Tesla Austin"], forms: [{ f: "box", w: 1100, d: 380, h: 30 }] }),
  P("tesla-fremont", "Tesla Fremont Factory", "Fremont, California", -121.945, 37.494, 2500, ["factory", "tech"],
    ["A General Motors and then a GM–Toyota plant, bought by Tesla in 2010.", "It builds more cars than any other factory in the United States."],
    [["Tesla since", "2010"]], { also: ["Tesla Fremont"] }),
  P("foxconn-zhengzhou", "Foxconn Zhengzhou", "Henan, China", 113.835, 34.522, 5000, ["factory", "tech"],
    ["iPhone City: the plant that assembles a large share of the world's iPhones.", "At its peak it employs a couple of hundred thousand people."],
    [["Opened", "2010"]], { also: ["iPhone City", "Foxconn"] }),
  P("tsmc-fab-18", "TSMC Fab 18", "Tainan, Taiwan", 120.284, 23.11, 2000, ["factory", "tech"],
    ["A chip fab making the most advanced processors in the world, at the 5 and 3 nanometre nodes.", "TSMC makes most of the world's leading-edge chips."],
    [["Nodes", "5 nm and 3 nm"]], { also: ["TSMC"] }),
  P("samsung-pyeongtaek", "Samsung Pyeongtaek Campus", "Gyeonggi, South Korea", 127.016, 37.005, 3000, ["factory", "tech"],
    ["One of the largest semiconductor plants in the world, making memory chips.", "Each of its fab lines is about the size of several football pitches."],
    [["Production from", "2017"]], { also: ["Samsung Pyeongtaek"] }),
  P("asml-veldhoven", "ASML", "Veldhoven, Netherlands", 5.403, 51.404, 1500, ["factory", "tech"],
    ["The only company that makes extreme-ultraviolet lithography machines, which print the smallest chips.", "Each machine ships in about 40 containers."],
    [["EUV maker", "the only one"]]),
  P("ferrari-maranello", "Ferrari, Maranello", "Emilia-Romagna, Italy", 10.8613, 44.532, 1500, ["factory", "racing"],
    ["Ferrari's factory since 1943, with the Fiorano test track beside it.", "Every Ferrari road car is built here."],
    [["Here since", "1943"]], { also: ["Ferrari", "Maranello"] }),
  P("lego-billund", "LEGO House", "Billund, Denmark", 9.1243, 55.7351, 600, ["factory", "gaming", "architecture"],
    ["The home of LEGO, where the brick was patented in 1958; the factory is down the road.", "LEGO House, opened in 2017, is stacked like giant bricks."],
    [["Brick patented", "1958"]], { also: ["LEGO", "Billund"], forms: [{ f: "box", w: 60, d: 60, h: 8 }, { f: "box", w: 30, d: 30, h: 8, dx: -10, z: 8 }, { f: "box", w: 20, d: 30, h: 8, dx: 15, dy: 10, z: 8 }, { f: "box", w: 16, d: 16, h: 8, dx: 5, dy: -10, z: 16 }, { f: "box", w: 10, d: 10, h: 8, z: 24 }] }),
  P("guinness-storehouse", "Guinness Storehouse", "St James's Gate, Dublin", -6.2867, 53.3419, 600, ["factory", "food"],
    ["Arthur Guinness signed a 9,000-year lease on the brewery in 1759.", "The storehouse is shaped inside like a giant pint glass."],
    [["Lease signed", "1759"]], { also: ["Guinness", "St James's Gate"] }),
  P("meyer-werft", "Meyer Werft", "Papenburg, Germany", 7.378, 53.092, 2000, ["factory"],
    ["A shipyard building cruise ships in halls about 500 m long, far up the river Ems.", "Each new ship is floated down the river to the sea."],
    [["Founded", "1795"]], { forms: [{ f: "box", w: 504, d: 125, h: 75 }, { f: "box", w: 370, d: 100, h: 60, dy: -140 }] }),
  P("hhi-ulsan", "Hyundai Heavy Industries Shipyard", "Ulsan, South Korea", 129.428, 35.51, 6000, ["factory"],
    ["The largest shipyard in the world, building tankers, container ships and LNG carriers.", "Its goliath cranes lift over 1,000 tonnes."],
    [["Founded", "1972"]], { also: ["Hyundai Heavy Industries"] }),
  P("basf-ludwigshafen", "BASF Ludwigshafen", "Rhineland-Palatinate, Germany", 8.425, 49.52, 6000, ["factory"],
    ["The largest integrated chemical site in the world, about 10 km² on the Rhine.", "Its plants feed each other through about 2,800 km of pipes."],
    [["Site", "about 10 km²"]], { also: ["BASF"] }),
  P("jamnagar-refinery", "Jamnagar Refinery", "Gujarat, India", 69.87, 22.35, 8000, ["factory", "energy"],
    ["The largest oil refinery complex in the world, run by Reliance.", "It can process about 1.4 million barrels a day."],
    [["Capacity", "about 1.4 million barrels a day"]], { also: ["Jamnagar", "Reliance Jamnagar"] }),
  P("three-gorges-dam", "Three Gorges Dam", "Hubei, China", 111.0039, 30.8236, 6000, ["factory", "energy", "architecture"],
    ["The largest power station in the world, about 22.5 GW, across the Yangtze.", "Ships climb past it in a five-step lock or a ship lift."],
    [["Capacity", "about 22.5 GW"], ["Length", "about 2.3 km"]], { also: ["Three Gorges"], forms: [{ f: "box", w: 2300, d: 120, h: 185, rot: -20 }] }),
  P("itaipu", "Itaipu Dam", "Brazil–Paraguay border", -54.5886, -25.4083, 8000, ["factory", "energy"],
    ["A dam on the Paraná owned by Brazil and Paraguay, with about 14 GW of turbines.", "In some years it has made more electricity than any other plant."],
    [["Capacity", "about 14 GW"]], { also: ["Itaipu"], forms: [{ f: "box", w: 1500, d: 100, h: 196, rot: 30 }] }),
  // ---- Mines ----------------------------------------------------------------------------------------
  P("bingham-canyon", "Bingham Canyon Mine", "Utah", -112.15, 40.523, 7000, ["mining"],
    ["One of the largest man-made excavations on Earth, more than 1.2 km deep and about 4 km across.", "It has been worked as an open pit since 1906."],
    [["Depth", "over 1.2 km"], ["Open pit since", "1906"]], { also: ["Kennecott", "Bingham Canyon"] }),
  P("chuquicamata", "Chuquicamata", "Atacama, Chile", -68.9, -22.29, 9000, ["mining"],
    ["One of the largest open-pit copper mines in the world, about 4 km long and 1 km deep.", "It is now being taken underground."],
    [["Pit depth", "about 1 km"]], { also: ["Chuqui"] }),
  P("escondida", "Escondida", "Atacama, Chile", -69.07, -24.27, 9000, ["mining"],
    ["The world's largest copper mine by output, in the Atacama desert at about 3,100 m.", "It produces about a twentieth of the world's copper."],
    [["Altitude", "about 3,100 m"]]),
  P("grasberg", "Grasberg", "Central Papua, Indonesia", 137.116, -4.053, 6000, ["mining"],
    ["One of the largest gold and copper mines in the world, near 4,000 m in the mountains of Papua.", "Mining has moved from the open pit to caves below it."],
    [["Altitude", "about 4,000 m"]]),
  P("mir-mine", "Mir Mine", "Mirny, Yakutia", 113.994, 62.527, 3000, ["mining"],
    ["A diamond pit about 525 m deep and 1.2 km across, beside the town of Mirny.", "Open-pit mining stopped in 2001; work went underground."],
    [["Depth", "about 525 m"], ["Across", "about 1.2 km"]], { also: ["Mirny mine"] }),
  P("super-pit", "Super Pit", "Kalgoorlie, Western Australia", 121.505, -30.778, 5000, ["mining"],
    ["Australia's largest open-cut gold mine, about 3.5 km long, 1.5 km wide and 600 m deep.", "It swallowed the old underground mines of the Golden Mile."],
    [["Size", "about 3.5 × 1.5 km"]], { also: ["Fimiston Open Pit", "Kalgoorlie Super Pit"] }),
  P("kiruna-mine", "Kiruna Mine", "Lapland, Sweden", 20.2, 67.85, 6000, ["mining"],
    ["The largest underground iron ore mine in the world, worked since 1898.", "The ground is sinking towards it, so the town of Kiruna is being moved."],
    [["Worked since", "1898"]], { also: ["Kiruna"] }),
  P("mponeng", "Mponeng", "Gauteng, South Africa", 27.421, -26.437, 3000, ["mining"],
    ["The deepest mine in the world, reaching more than 4 km below the surface for gold.", "The rock at the bottom is about 60 °C; ice slurry cools the tunnels."],
    [["Depth", "over 4 km"]]),
  P("garzweiler", "Garzweiler", "Rhineland, Germany", 6.48, 51.05, 15000, ["mining", "energy"],
    ["An open-cast lignite mine where giant bucket-wheel excavators like Bagger 288 move whole villages of earth.", "Villages in its path have been moved and demolished."],
    [["Coal", "lignite"]], { also: ["Garzweiler mine", "Bagger 288"] }),
  P("diavik", "Diavik Diamond Mine", "Lac de Gras, Northwest Territories", 110.28, 64.49, 6000, ["mining"],
    ["Diamond pits on an island in a sub-Arctic lake, held back by dikes.", "In winter supplies arrive on an ice road."],
    [["Opened", "2003"]], { also: ["Diavik"] }),
  P("carajas", "Carajás", "Pará, Brazil", -50.16, -6.07, 10000, ["mining"],
    ["The largest iron ore mine in the world, in the Amazon.", "Its ore runs about 890 km by rail to the Atlantic."],
    [["Railway to the coast", "about 890 km"]], { also: ["Carajas", "Serra dos Carajás"] }),
  P("big-hole", "The Big Hole", "Kimberley, South Africa", 24.768, -28.738, 1500, ["mining"],
    ["A diamond mine dug largely by hand from 1871 to 1914, about 215 m deep.", "About 2,700 kg of diamonds came out of it."],
    [["Dug", "1871–1914"], ["Depth", "about 215 m"]], { also: ["Kimberley Mine", "Big Hole Kimberley"] }),
  P("morenci", "Morenci Mine", "Arizona", -109.36, 33.09, 9000, ["mining"],
    ["One of the largest copper mines in North America, worked since the 1870s.", "The old town of Morenci was moved for the pit."],
    [["Worked since", "1870s"]], { also: ["Morenci"] }),
  P("oyu-tolgoi", "Oyu Tolgoi", "South Gobi, Mongolia", 106.86, 43.0, 8000, ["mining"],
    ["One of the largest copper and gold deposits known, in the Gobi desert.", "Its underground mine is a block cave far below the open pit."],
    [["Discovered", "2001"]]),
  P("hull-rust", "Hull–Rust–Mahoning Mine", "Hibbing, Minnesota", -92.95, 47.44, 6000, ["mining"],
    ["The Grand Canyon of the North: an iron ore pit more than 5 km long, worked since 1895.", "The town of Hibbing was moved to make room for it."],
    [["Worked since", "1895"]], { also: ["Hull Rust Mine"] }),
];
