// World Heritage Sites with intros of their own: the ones people look up most
// that the first lists don't already cover, each with a few lines, the
// figures worth knowing and, for buildings, a simple massing model. Every
// other site on the World Heritage List gets a plainer intro from the list
// itself (see unesco.ts); the year each was inscribed is added from there.
import type { Form, IntroPlace } from "./places";

const P = (id: string, name: string, where: string, lon: number, lat: number, size: number, tags: string[], lines: string[], facts: [string, string][], extra: Partial<IntroPlace> = {}): IntroPlace =>
  ({ id, name, where, lon, lat, size, tags: ["heritage", ...tags], lines, facts, ...extra });

const grid = (nx: number, ny: number, step: number, f: (i: number, j: number) => Form[]): Form[] =>
  Array.from({ length: nx * ny }, (_, k) => f(k % nx, Math.floor(k / nx)).map((x) => ({ ...x, dx: ((x as { dx?: number }).dx ?? 0) + (k % nx - (nx - 1) / 2) * step, dy: ((x as { dy?: number }).dy ?? 0) + (Math.floor(k / nx) - (ny - 1) / 2) * step }) as Form)).flat();
const spire = (x: number, y: number, w: number, h: number, cone: number): Form[] => [{ f: "box", w, d: w, h, dx: x, dy: y }, { f: "cone", r: w * 0.55, h: cone, dx: x, dy: y, z: h }];

export const HERITAGE_INTROS: IntroPlace[] = [
  // ---- Europe ---------------------------------------------------------------------------------------
  P("versailles", "Palace of Versailles", "Versailles, France", 2.1204, 48.8049, 900, ["architecture", "art"],
    ["Louis XIV turned his father's hunting lodge into the seat of French power; the court moved here in 1682.", "In the Hall of Mirrors, 73 m long, the treaty that ended the First World War was signed in 1919."],
    [["Court moved here", "1682"], ["Hall of Mirrors", "73 m"]],
    { also: ["Versailles", "Château de Versailles"], forms: [{ f: "box", w: 40, d: 400, h: 22 }, { f: "box", w: 130, d: 28, h: 20, dx: 85, dy: 185 }, { f: "box", w: 130, d: 28, h: 20, dx: 85, dy: -185 }, { f: "box", w: 90, d: 22, h: 22, dx: 60, dy: 45 }, { f: "box", w: 90, d: 22, h: 22, dx: 60, dy: -45 }, { f: "box", w: 22, d: 45, h: 40, dx: 80, dy: 110 }],
      parts: [{ label: "Hall of Mirrors", dx: -10, h: 24 }, { label: "Royal Chapel", dx: 80, dy: 110, h: 40 }, { label: "Marble Court", dx: 70, h: 6 }] }),
  P("pompeii", "Pompeii", "Campania, Italy", 14.4848, 40.7489, 1600, ["architecture"],
    ["A Roman town buried by the eruption of Vesuvius in AD 79, and preserved under the ash.", "Excavated since 1748, it still shows streets, shops, houses and graffiti as they were that day."],
    [["Buried", "AD 79"], ["Digging since", "1748"]],
    { also: ["Pompei", "Pompeii ruins"], forms: [...grid(6, 4, 70, () => [{ f: "box", w: 55, d: 55, h: 4 }]), { f: "box", w: 150, d: 40, h: 1, dx: -300, dy: -40 }, { f: "ring", rx: 68, ry: 52, ix: 33, iy: 18, h: 12, dx: 560, dy: -150 }],
      parts: [{ label: "The Forum", dx: -300, dy: -40, h: 3 }, { label: "Amphitheatre", dx: 560, dy: -150, h: 12 }] }),
  P("florence-cathedral", "Florence Cathedral", "Florence, Italy", 11.256, 43.7731, 500, ["architecture", "art"],
    ["Brunelleschi's dome, finished in 1436, is still the largest brick dome ever built.", "Giotto's bell tower stands beside it, and the octagonal Baptistery faces its doors."],
    [["Dome finished", "1436"], ["Height to the lantern", "about 114 m"]],
    { also: ["Duomo di Firenze", "Il Duomo", "Santa Maria del Fiore", "Florence"], forms: [{ f: "box", w: 85, d: 40, h: 42, dx: -40 }, { f: "box", w: 30, d: 90, h: 42, dx: 25 }, { f: "cyl", r: 23, h: 55, dx: 30 }, { f: "dome", r: 23, h: 38, dx: 30, z: 55 }, { f: "cyl", r: 3.5, h: 18, dx: 30, z: 92 }, { f: "box", w: 15, d: 15, h: 85, dx: -75, dy: -30 }, { f: "cyl", r: 13, h: 28, dx: -135 }, { f: "dome", r: 13, h: 8, dx: -135, z: 28 }],
      parts: [{ label: "Brunelleschi's dome", dx: 30, h: 110 }, { label: "Giotto's campanile", dx: -75, dy: -30, h: 85 }, { label: "Baptistery", dx: -135, h: 36 }] }),
  P("siena-campo", "Piazza del Campo", "Siena, Italy", 11.3317, 43.3184, 400, ["architecture"],
    ["Siena's shell-shaped square, sloping towards the town hall, where the Palio horse race is run twice each summer.", "The Torre del Mangia rises 102 m from the Palazzo Pubblico."],
    [["Torre del Mangia", "102 m"], ["Palio", "2 July and 16 August"]],
    { also: ["Siena"], forms: [{ f: "stand", rx: 90, ry: 75, ix: 0.1, iy: 0.1, h: 1, n: 1, from: 0, to: 180 }, { f: "box", w: 90, d: 25, h: 25, dy: -12 }, { f: "box", w: 9, d: 9, h: 102, dx: -40, dy: -12 }],
      parts: [{ label: "Torre del Mangia", dx: -40, dy: -12, h: 102 }] }),
  P("cinque-terre", "Cinque Terre", "Liguria, Italy", 9.6836, 44.135, 2500, [],
    ["Five villages clinging to the cliffs of the Ligurian coast, joined by footpaths and a railway through the rock.", "Their vineyards grow on terraces walled by hand over a thousand years."],
    [["Villages", "5"]], { also: ["Vernazza", "Manarola", "Portovenere"] }),
  P("amalfi-coast", "Amalfi Coast", "Campania, Italy", 14.6027, 40.634, 3000, [],
    ["Towns hung on the cliffs south of Naples, with lemon terraces and a road cut into the rock.", "Amalfi was a maritime republic that traded across the Mediterranean in the 900s and 1000s."],
    [["Coastline", "about 50 km"]], { also: ["Amalfi", "Positano", "Costiera Amalfitana"] }),
  P("alberobello", "Trulli of Alberobello", "Apulia, Italy", 17.2365, 40.782, 500, ["architecture"],
    ["About 1,500 trulli: limestone houses built without mortar, under conical roofs of stone slabs.", "Some of the roofs carry symbols painted in whitewash."],
    [["Trulli", "about 1,500"]], { also: ["Alberobello", "Trulli"], forms: grid(6, 4, 14, () => [{ f: "cyl", r: 4.5, h: 3 }, { f: "cone", r: 5, h: 6, z: 3 }]) }),
  P("matera", "Sassi of Matera", "Basilicata, Italy", 16.6115, 40.6664, 1200, [],
    ["Houses and churches cut into the sides of a ravine, lived in since the Palaeolithic.", "Emptied as a slum in the 1950s, the Sassi have been restored and lived in again."],
    [["Lived in for", "about 9,000 years"]], { also: ["Matera", "Sassi di Matera"] }),
  P("tre-cime", "Tre Cime di Lavaredo", "Dolomites, Italy", 12.3058, 46.6187, 5000, [],
    ["Three limestone peaks, the emblem of the Dolomites: an ancient coral reef raised into mountains.", "The pale rock turns pink at sunset, the enrosadira."],
    [["Cima Grande", "2,999 m"]], { also: ["Dolomites", "Tre Cime"] }),
  P("mount-etna", "Mount Etna", "Sicily, Italy", 14.9934, 37.751, 25000, [],
    ["Europe's highest active volcano, erupting almost constantly.", "Its height changes with each eruption."],
    [["Height", "about 3,300 m"]], { also: ["Etna"] }),
  P("chartres", "Chartres Cathedral", "Chartres, France", 1.4876, 48.4478, 400, ["architecture", "art"],
    ["A Gothic cathedral built mostly between 1194 and 1220, still with most of its medieval stained glass.", "Its two spires don't match: one plain Romanesque, the other a later Flamboyant Gothic."],
    [["Built", "1194–1220"], ["Spires", "105 m and 113 m"]],
    { forms: [{ f: "box", w: 130, d: 32, h: 37 }, { f: "box", w: 30, d: 64, h: 37, dx: 15 }, ...spire(-62, 12, 16, 60, 45), ...spire(-62, -12, 16, 60, 53)],
      parts: [{ label: "Rose windows", dx: -55, h: 30 }, { label: "The two spires", dx: -62, h: 110 }] }),
  P("chambord", "Château de Chambord", "Loire Valley, France", 1.517, 47.6162, 700, ["architecture"],
    ["Francis I's Renaissance château in the Loire valley, begun in 1519.", "Its double-helix staircase, perhaps drawn by Leonardo da Vinci, lets two people climb without meeting."],
    [["Begun", "1519"]], { also: ["Chambord", "Loire Valley"], forms: [{ f: "ring", rx: 78, ry: 58, ix: 71, iy: 51, h: 14 }, { f: "box", w: 44, d: 44, h: 28 }, ...[[-22, -22], [22, -22], [-22, 22], [22, 22]].map(([dx, dy]): Form => ({ f: "cyl", r: 10, h: 30, dx, dy })), { f: "cyl", r: 5, h: 22, z: 28 }],
      parts: [{ label: "Double-helix staircase", h: 50 }] }),
  P("pont-du-gard", "Pont du Gard", "Gard, France", 4.5354, 43.9475, 500, ["architecture"],
    ["A Roman aqueduct bridge of three tiers of arches, built about AD 50 to carry water to Nîmes.", "Its stones were laid without mortar."],
    [["Height", "about 49 m"], ["Top tier", "about 275 m long"]],
    { forms: [{ f: "box", w: 142, d: 6, h: 22, rot: -30 }, { f: "box", w: 242, d: 4.5, h: 20, z: 22, rot: -30 }, { f: "box", w: 275, d: 3, h: 7, z: 42, rot: -30 }] }),
  P("carcassonne", "Cité de Carcassonne", "Aude, France", 2.3633, 43.2063, 900, ["architecture"],
    ["A walled medieval city with two rings of walls about 3 km long and 52 towers.", "Restored by Viollet-le-Duc in the 1800s, with pointed slate roofs the original may never have had."],
    [["Towers", "52"], ["Walls", "about 3 km"]],
    { also: ["Carcassonne"], forms: [{ f: "ring", rx: 270, ry: 140, ix: 263, iy: 133, h: 9 }, { f: "ring", rx: 245, ry: 120, ix: 238, iy: 113, h: 13 }, ...Array.from({ length: 12 }, (_, i): Form[] => { const a = (i / 12) * Math.PI * 2; return [{ f: "cyl", r: 6, h: 18, dx: Math.cos(a) * 245, dy: Math.sin(a) * 120 }, { f: "cone", r: 6.5, h: 9, dx: Math.cos(a) * 245, dy: Math.sin(a) * 120, z: 18 }]; }).flat()] }),
  P("avignon", "Palais des Papes", "Avignon, France", 4.8075, 43.9507, 500, ["architecture"],
    ["The largest Gothic palace in the world, home of the popes from 1309 to 1377.", "Nearby, the Pont Saint-Bénezet of the song stops halfway across the Rhône."],
    [["Popes here", "1309–1377"]], { also: ["Avignon", "Palace of the Popes", "Pont d'Avignon"], forms: [{ f: "box", w: 120, d: 100, h: 45 }, { f: "box", w: 18, d: 18, h: 55, dx: 50, dy: 40 }] }),
  P("tower-of-london", "Tower of London", "City of London", -0.0759, 51.5081, 500, ["architecture"],
    ["William the Conqueror's White Tower, begun about 1078, stands at the heart of a fortress, palace and prison.", "The Crown Jewels are kept here, and ravens are kept too, so the kingdom won't fall."],
    [["White Tower begun", "about 1078"], ["White Tower", "27 m"]],
    { forms: [{ f: "ring", rx: 115, ry: 100, ix: 109, iy: 94, h: 8 }, { f: "ring", rx: 90, ry: 78, ix: 85, iy: 73, h: 11 }, { f: "box", w: 36, d: 32, h: 27 }, ...[[-18, -16], [18, -16], [-18, 16], [18, 16]].map(([dx, dy]): Form => ({ f: "cyl", r: 3.5, h: 33, dx, dy }))],
      parts: [{ label: "The White Tower", h: 33 }, { label: "Jewel House", dy: 45, h: 10 }, { label: "Traitors' Gate", dy: -95, h: 6 }] }),
  P("bath", "Roman Baths, Bath", "Somerset, England", -2.359, 51.3811, 600, ["architecture"],
    ["A Roman spa built round the only hot springs in Britain, then a Georgian city of crescents in honey-coloured stone.", "The Royal Crescent, finished in 1774, curves for 150 m."],
    [["Spring water", "about 46 °C"]], { also: ["Bath", "City of Bath", "Royal Crescent"], forms: [{ f: "box", w: 60, d: 40, h: 12 }, { f: "box", w: 70, d: 22, h: 25, dx: 20, dy: 60 }, { f: "box", w: 10, d: 10, h: 50, dx: 0, dy: 60 }],
      parts: [{ label: "The Great Bath", h: 3 }, { label: "Bath Abbey", dx: 20, dy: 60, h: 50 }] }),
  P("giants-causeway", "Giant's Causeway", "County Antrim, Northern Ireland", -6.5117, 55.2408, 1500, [],
    ["About 40,000 interlocking basalt columns, most of them six-sided, left by lava cooling 50 to 60 million years ago.", "Legend says the giant Finn McCool built it to cross to Scotland."],
    [["Columns", "about 40,000"]], { also: ["Giants Causeway"] }),
  P("canterbury-cathedral", "Canterbury Cathedral", "Canterbury, England", 1.083, 51.2798, 500, ["architecture"],
    ["The mother church of the Church of England, where Archbishop Thomas Becket was murdered in 1170.", "Pilgrims to his shrine gave Chaucer The Canterbury Tales."],
    [["Becket murdered", "1170"], ["Bell Harry tower", "72 m"]], { also: ["Canterbury"], forms: [{ f: "box", w: 160, d: 38, h: 30 }, { f: "box", w: 30, d: 70, h: 30, dx: 10 }, { f: "box", w: 13, d: 13, h: 72, dx: 10 }, ...spire(-78, 14, 10, 50, 2), ...spire(-78, -14, 10, 50, 2)] }),
  P("hadrians-wall", "Hadrian's Wall at Housesteads", "Northumberland, England", -2.3311, 55.013, 2500, ["architecture"],
    ["The Roman frontier across northern Britain, about 117 km from sea to sea, begun in AD 122.", "Housesteads fort sits on the crags here; its barracks, granaries and latrines can still be traced."],
    [["Begun", "AD 122"], ["Length", "about 117 km"]], { also: ["Hadrian's Wall", "Hadrians Wall", "Housesteads"], forms: [{ f: "box", w: 2200, d: 3, h: 4, rot: -10 }, { f: "box", w: 180, d: 110, h: 2, dy: -60 }] }),
  P("kew-gardens", "Kew Gardens", "Richmond, London", -0.2959, 51.4787, 1200, ["architecture"],
    ["The Royal Botanic Gardens, with the largest collection of living plants in the world.", "Its Palm House of 1848 was one of the first great buildings of iron and glass."],
    [["Living plants", "about 50,000 kinds"]], { also: ["Royal Botanic Gardens, Kew", "Kew"], forms: [{ f: "shell", rx: 55, ry: 15, h: 19 }, { f: "dome", r: 15, h: 19 }] }),
  P("seville-cathedral", "Seville Cathedral", "Seville, Spain", -5.9931, 37.3858, 600, ["architecture"],
    ["The largest Gothic cathedral in the world, begun in 1401 on the site of the city's great mosque.", "Its bell tower, the Giralda, began as the mosque's minaret; Columbus's tomb is inside."],
    [["Begun", "1401"], ["Giralda", "about 104 m"]], { also: ["Giralda", "Seville", "Real Alcázar"], forms: [{ f: "box", w: 126, d: 83, h: 40 }, { f: "box", w: 14, d: 14, h: 70, dx: 55, dy: 35 }, { f: "box", w: 10, d: 10, h: 34, dx: 55, dy: 35, z: 70 }],
      parts: [{ label: "The Giralda", dx: 55, dy: 35, h: 104 }, { label: "Tomb of Columbus", h: 10 }] }),
  P("cordoba-mezquita", "Mosque-Cathedral of Córdoba", "Córdoba, Spain", -4.7794, 37.8789, 500, ["architecture", "art"],
    ["A great mosque begun in 785: a forest of some 850 columns under red-and-white arches.", "In the 1500s a Renaissance cathedral was built into the middle of it."],
    [["Begun", "785"], ["Columns", "about 850"]], { also: ["Mezquita", "Córdoba", "Cordoba Mosque"], forms: [{ f: "box", w: 175, d: 130, h: 13, dy: 25 }, { f: "box", w: 30, d: 75, h: 40, dy: 30 }, { f: "box", w: 120, d: 60, h: 1, dy: -70 }, { f: "box", w: 12, d: 12, h: 54, dy: -95 }] }),
  P("toledo", "Historic City of Toledo", "Toledo, Spain", -4.0207, 39.858, 1500, ["architecture"],
    ["A hilltop city in a loop of the Tagus, where Christians, Muslims and Jews lived side by side for centuries.", "El Greco painted it, and its sword-makers were famous across Europe."],
    [["Capital of Spain until", "1561"]], { also: ["Toledo", "Alcázar of Toledo"], forms: [{ f: "box", w: 60, d: 60, h: 30 }, ...[[-30, -30], [30, -30], [-30, 30], [30, 30]].map(([dx, dy]): Form => ({ f: "box", w: 8, d: 8, h: 42, dx, dy }))] }),
  P("segovia-aqueduct", "Aqueduct of Segovia", "Segovia, Spain", -4.1179, 40.9479, 600, ["architecture"],
    ["A Roman aqueduct of granite blocks laid without mortar, built about AD 100 and still standing in the middle of the city.", "It carried water until the 1900s."],
    [["Arches", "167"], ["Highest", "about 28 m"]], { also: ["Segovia"], forms: [{ f: "box", w: 300, d: 3, h: 28, rot: -40 }, { f: "box", w: 150, d: 3, h: 12, dx: 150, dy: 140, rot: -60 }] }),
  P("santiago-compostela", "Santiago de Compostela Cathedral", "Galicia, Spain", -8.5446, 42.8805, 500, ["architecture"],
    ["The goal of the Camino de Santiago, built over what is believed to be the tomb of St James.", "Pilgrims have walked here since the 800s."],
    [["Towers", "about 74 m"]], { also: ["Santiago de Compostela", "Camino de Santiago"], forms: [{ f: "box", w: 100, d: 70, h: 30 }, ...spire(-50, 18, 14, 60, 14), ...spire(-50, -18, 14, 60, 14)] }),
  P("park-guell", "Park Güell", "Barcelona, Spain", 2.1527, 41.4145, 500, ["architecture", "art"],
    ["Gaudí's hillside garden city of 1900–1914, with its mosaic dragon and a serpentine bench looking over Barcelona.", "Only two houses were built; it became a public park in 1926."],
    [["Built", "1900–1914"]], { also: ["Park Guell", "Parc Güell"], forms: [{ f: "box", w: 85, d: 40, h: 8 }, { f: "box", w: 10, d: 10, h: 18, dx: -60, dy: -40 }, { f: "cone", r: 6, h: 10, dx: -60, dy: -40, z: 18 }] }),
  P("pena-palace", "Pena Palace", "Sintra, Portugal", -9.3904, 38.7876, 600, ["architecture"],
    ["A Romantic palace in red and yellow on a hilltop above Sintra, built in the 1840s for King Ferdinand II.", "On a clear day it can be seen from Lisbon."],
    [["Built", "1840s"]], { also: ["Sintra", "Palácio da Pena"], forms: [{ f: "box", w: 60, d: 30, h: 15 }, { f: "cyl", r: 7, h: 30, dx: -25 }, { f: "dome", r: 7, h: 6, dx: -25, z: 30 }, { f: "box", w: 9, d: 9, h: 30, dx: 25 }] }),
  P("belem-tower", "Belém Tower", "Lisbon, Portugal", -9.216, 38.6916, 600, ["architecture"],
    ["A fortress of 1519 at the mouth of the Tagus, where Portugal's ships set out on their voyages.", "Nearby, the Jerónimos Monastery was paid for by the spice trade."],
    [["Finished", "1519"], ["Tower", "30 m"]], { also: ["Torre de Belém", "Jerónimos Monastery", "Belem"], forms: [{ f: "box", w: 30, d: 25, h: 10 }, { f: "box", w: 13, d: 13, h: 30, dy: -12 }] }),
  P("hungarian-parliament", "Hungarian Parliament Building", "Budapest, Hungary", 19.0457, 47.5071, 800, ["architecture"],
    ["Finished in 1904 on the Danube bank in Pest, the largest building in Hungary.", "The Holy Crown of Hungary is kept under its dome."],
    [["Length", "268 m"], ["Dome", "96 m"]], { also: ["Budapest Parliament", "Budapest"], forms: [{ f: "box", w: 60, d: 268, h: 25 }, { f: "cyl", r: 18, h: 20, z: 25 }, { f: "dome", r: 18, h: 30, z: 45 }, { f: "cone", r: 3, h: 20, z: 75 }, ...spire(-15, 50, 7, 45, 15), ...spire(-15, -50, 7, 45, 15)] }),
  P("schonbrunn", "Schönbrunn Palace", "Vienna, Austria", 16.3122, 48.1845, 1600, ["architecture"],
    ["The Habsburgs' summer palace, with 1,441 rooms, rebuilt in its present form from the 1740s for Maria Theresa.", "Its gardens climb the hill to the Gloriette."],
    [["Rooms", "1,441"]], { also: ["Schonbrunn", "Schloss Schönbrunn"], forms: [{ f: "box", w: 180, d: 25, h: 25 }, { f: "box", w: 30, d: 120, h: 20, dx: -90, dy: 60 }, { f: "box", w: 30, d: 120, h: 20, dx: 90, dy: 60 }, { f: "box", w: 85, d: 10, h: 20, dy: -650 }],
      parts: [{ label: "The palace", h: 25 }, { label: "The Gloriette", dy: -650, h: 20 }] }),
  P("st-stephens-vienna", "St Stephen's Cathedral", "Vienna, Austria", 16.3731, 48.2086, 400, ["architecture"],
    ["Vienna's cathedral, with a roof of 230,000 glazed tiles and a south tower of 136 m.", "Its first great bell, the Pummerin, was cast from cannons the Ottoman army left behind in 1683."],
    [["South tower", "136 m"]], { also: ["Stephansdom", "Vienna"], forms: [{ f: "box", w: 107, d: 35, h: 28 }, { f: "pyramid", w: 35, h: 30, z: 28 }, ...spire(10, -22, 14, 70, 66)] }),
  P("salzburg", "Hohensalzburg Fortress", "Salzburg, Austria", 13.0471, 47.795, 900, ["architecture", "music"],
    ["A fortress begun in 1077 above Salzburg's baroque old town, one of the largest medieval castles in Europe.", "Mozart was born in the town below in 1756."],
    [["Begun", "1077"]], { also: ["Salzburg", "Festung Hohensalzburg"], forms: [{ f: "box", w: 250, d: 150, h: 12 }, { f: "box", w: 60, d: 50, h: 32 }] }),
  P("hallstatt", "Hallstatt", "Salzkammergut, Austria", 13.6493, 47.5622, 1500, [],
    ["A lakeside village under the mountains, where salt has been mined for some 7,000 years.", "It gave its name to an Iron Age culture of central Europe."],
    [["Salt mined for", "about 7,000 years"]]),
  P("prague-castle", "Prague Castle", "Prague, Czechia", 14.4005, 50.0909, 800, ["architecture"],
    ["Seat of Bohemian kings, Holy Roman emperors and now the Czech president, one of the largest castle complexes in the world.", "St Vitus Cathedral at its heart took nearly 600 years to finish, from 1344 to 1929."],
    [["Length", "about 570 m"], ["St Vitus", "1344–1929"]],
    { also: ["Prague", "Pražský hrad", "St Vitus Cathedral"], forms: [{ f: "box", w: 500, d: 120, h: 16 }, { f: "box", w: 124, d: 60, h: 33, dx: -20 }, ...spire(-10, -28, 15, 70, 26), ...spire(-75, 18, 9, 50, 32), ...spire(-75, -18, 9, 50, 32)],
      parts: [{ label: "St Vitus Cathedral", dx: -10, dy: -28, h: 96 }] }),
  P("charles-bridge", "Charles Bridge", "Prague, Czechia", 14.4114, 50.0865, 700, ["architecture"],
    ["Begun in 1357 under Charles IV, the only way across the Vltava in Prague until 1841.", "Thirty statues of saints line its 516 m."],
    [["Begun", "1357"], ["Length", "516 m"]], { also: ["Karlův most"], forms: [{ f: "box", w: 516, d: 10, h: 13, rot: -12 }, { f: "box", w: 14, d: 14, h: 47, dx: 252, dy: -54 }, { f: "box", w: 12, d: 12, h: 40, dx: -252, dy: 54 }] }),
  P("wawel", "Wawel Castle", "Kraków, Poland", 19.9354, 50.0541, 800, ["architecture"],
    ["The royal castle and cathedral on Wawel Hill, where Poland's kings were crowned and buried.", "Below it, Kraków's market square is one of the largest medieval squares in Europe."],
    [["Royal seat until", "1596"]], { also: ["Kraków", "Krakow", "Wawel Hill"], forms: [{ f: "ring", rx: 50, ry: 45, ix: 35, iy: 30, h: 20 }, { f: "box", w: 70, d: 25, h: 25, dx: -90 }, { f: "box", w: 12, d: 12, h: 50, dx: -110, dy: 10 }] }),
  P("auschwitz", "Auschwitz-Birkenau", "Oświęcim, Poland", 19.1789, 50.0343, 2000, [],
    ["The largest of the Nazi German concentration and extermination camps, where about 1.1 million people were murdered, most of them Jews.", "It is kept as a memorial and museum, so that it is not forgotten."],
    [["Liberated", "27 January 1945"]], { also: ["Auschwitz", "Birkenau"] }),
  P("wieliczka", "Wieliczka Salt Mine", "Lesser Poland", 20.0548, 49.9837, 1000, [],
    ["A salt mine worked from the 1200s until 1996, with chapels and statues carved from rock salt.", "The Chapel of St Kinga lies 101 m underground."],
    [["Worked", "1200s–1996"]], { also: ["Wieliczka"] }),
  P("tallinn", "Tallinn Old Town", "Tallinn, Estonia", 24.7453, 59.4372, 1000, ["architecture"],
    ["One of the best-kept medieval towns of the Hanseatic League, walled, with its town hall of 1404.", "Toompea hill above it was the seat of power."],
    [["Town hall", "1404"]], { also: ["Tallinn"], forms: [{ f: "box", w: 40, d: 15, h: 15 }, ...spire(-15, 0, 6, 30, 34)] }),
  P("cologne-cathedral", "Cologne Cathedral", "Cologne, Germany", 6.958, 50.9413, 500, ["architecture"],
    ["Begun in 1248 and finished in 1880, true to the medieval plans.", "Its twin spires, 157 m, made it the tallest building in the world from 1880 to 1884."],
    [["Built", "1248–1880"], ["Spires", "157 m"]], { also: ["Kölner Dom", "Cologne"], forms: [{ f: "box", w: 144, d: 45, h: 43 }, { f: "box", w: 30, d: 86, h: 43, dx: 20 }, ...spire(-65, 13, 18, 100, 57), ...spire(-65, -13, 18, 100, 57)] }),
  P("sanssouci", "Sanssouci", "Potsdam, Germany", 13.0383, 52.4043, 600, ["architecture"],
    ["Frederick the Great's summer palace of 1747, on top of terraced vineyards.", "Its name means 'without care'."],
    [["Built", "1745–1747"]], { also: ["Potsdam", "Sanssouci Palace"], forms: [{ f: "steps", w: 160, top: 120, h: 18, n: 6, dy: -60 }, { f: "box", w: 100, d: 15, h: 10, z: 18 }, { f: "dome", r: 8, h: 8, z: 28 }] }),
  P("bruges", "Belfry of Bruges", "Bruges, Belgium", 3.2247, 51.2093, 800, ["architecture"],
    ["A medieval trading city of canals and brick gables, left as it was when its harbour silted up.", "Its belfry, 83 m, stands over the market square."],
    [["Belfry", "83 m"]], { also: ["Bruges", "Brugge"], forms: [{ f: "box", w: 45, d: 80, h: 18 }, { f: "box", w: 15, d: 15, h: 83, dy: -40 }] }),
  P("grand-place", "Grand-Place", "Brussels, Belgium", 4.3525, 50.8467, 400, ["architecture"],
    ["Brussels' central square, rebuilt by the guilds after a French bombardment in 1695.", "The town hall's Gothic tower rises 96 m."],
    [["Town hall tower", "96 m"]], { also: ["Grand Place", "Grote Markt", "Brussels"], forms: [{ f: "ring", rx: 60, ry: 40, ix: 52, iy: 32, h: 20 }, { f: "box", w: 60, d: 15, h: 25, dy: -38 }, ...spire(0, -38, 9, 60, 36)] }),
  P("amsterdam-canals", "Canal Ring of Amsterdam", "Amsterdam, Netherlands", 4.8852, 52.37, 2500, ["architecture"],
    ["Seventeenth-century canals dug in concentric arcs, lined with merchants' houses on narrow plots.", "The city has about 100 km of canals and 1,500 bridges."],
    [["Dug", "1600s"], ["Bridges", "about 1,500"]], { also: ["Amsterdam", "Grachtengordel"] }),
  P("kinderdijk", "Kinderdijk", "South Holland, Netherlands", 4.639, 51.8834, 1500, ["energy"],
    ["Nineteen windmills built in the 1730s and 1740s to pump water out of the polders.", "Water management here has kept the land dry for nearly a thousand years."],
    [["Windmills", "19"]], { forms: Array.from({ length: 8 }, (_, i): Form[] => [{ f: "cyl", r: 5, top: 4, h: 18, dx: -350 + i * 100, dy: i % 2 ? 40 : -40 }, { f: "cone", r: 4.5, h: 6, dx: -350 + i * 100, dy: i % 2 ? 40 : -40, z: 18 }]).flat() }),
  P("bryggen", "Bryggen", "Bergen, Norway", 5.3245, 60.3977, 500, ["architecture"],
    ["The wooden wharf of the Hanseatic merchants who ran the stockfish trade from the 1300s.", "The gabled houses have burned and been rebuilt in the same way many times."],
    [["Hanseatic office", "1360–1754"]], { also: ["Bergen"], forms: Array.from({ length: 10 }, (_, i): Form => ({ f: "box", w: 9, d: 30, h: 12, dx: -45 + i * 10 })) }),
  P("geirangerfjord", "Geirangerfjord", "Western Norway", 7.1, 62.105, 10000, [],
    ["A fjord carved by glaciers, walled by cliffs and waterfalls such as the Seven Sisters.", "With Nærøyfjord, it stands for the West Norwegian fjords."],
    [["Length", "about 15 km"]], { also: ["Geiranger", "Norwegian fjords"] }),
  P("stari-most", "Stari Most", "Mostar, Bosnia and Herzegovina", 17.815, 43.3372, 400, ["architecture"],
    ["An Ottoman bridge of 1566 over the Neretva, destroyed in 1993 and rebuilt from the river's stones by 2004.", "Divers still leap from it, about 21 m to the water."],
    [["Built", "1566"], ["Rebuilt", "2004"]], { also: ["Mostar", "Mostar Bridge"], forms: [{ f: "arch", span: 29, h: 21, t: 4, rot: 0 }, { f: "box", w: 10, d: 10, h: 25, dx: -20 }, { f: "box", w: 10, d: 10, h: 22, dx: 20 }] }),
  P("dubrovnik", "Walls of Dubrovnik", "Dubrovnik, Croatia", 18.1094, 42.6413, 900, ["architecture"],
    ["Walls nearly 2 km round enclose the old city of Ragusa, a maritime republic until 1808.", "They have stood, largely unchanged, since the 1600s."],
    [["Walls", "about 1,940 m"], ["Height", "up to 25 m"]], { also: ["Dubrovnik", "Old City of Dubrovnik"], forms: [{ f: "ring", rx: 220, ry: 130, ix: 213, iy: 123, h: 20 }, { f: "cyl", r: 15, h: 30, dx: -80, dy: 125 }, { f: "box", w: 30, d: 30, h: 20, dx: 210, dy: -40 }] }),
  P("plitvice", "Plitvice Lakes", "Lika, Croatia", 15.6144, 44.8778, 8000, [],
    ["Sixteen terraced lakes in the karst, joined by waterfalls over barriers of travertine.", "The travertine still grows, about a centimetre a year."],
    [["Lakes", "16"]], { also: ["Plitvice Lakes National Park", "Plitvice"] }),
  P("kotor", "Bay of Kotor", "Kotor, Montenegro", 18.7712, 42.4247, 4000, [],
    ["A walled Venetian town at the end of a winding bay under steep limestone mountains.", "Its walls climb 260 m up the mountain behind it."],
    [["Walls", "about 4.5 km"]], { also: ["Kotor"] }),
  P("meteora", "Meteora", "Thessaly, Greece", 21.6305, 39.7217, 3000, [],
    ["Monasteries on sandstone pillars rising hundreds of metres above the plain of Thessaly.", "Monks reached them by ladders and nets until steps were cut in the 1920s."],
    [["Monasteries still active", "6"]]),
  P("delphi", "Delphi", "Phocis, Greece", 22.501, 38.4824, 1200, ["architecture"],
    ["The sanctuary of Apollo where the Pythia gave oracles; the Greeks called it the navel of the world.", "A theatre and a stadium climb the slopes of Mount Parnassus above the temple."],
    [["Oracle consulted", "from the 700s BC"]], { also: ["Oracle of Delphi"], forms: [{ f: "box", w: 60, d: 24, h: 2 }, ...[0, 1, 2, 3, 4, 5].map((i): Form => ({ f: "cyl", r: 0.9, h: 10, dx: -10 + i * 4, dy: 10, z: 2 })), { f: "stand", rx: 40, ry: 40, ix: 10, iy: 10, h: 12, n: 4, from: 20, to: 160, dx: -30, dy: 60 }],
      parts: [{ label: "Temple of Apollo", h: 12 }, { label: "Theatre", dx: -30, dy: 80, h: 12 }] }),
  P("olympia", "Olympia", "Elis, Greece", 21.6301, 37.6383, 1200, ["sport", "architecture"],
    ["The sanctuary of Zeus where the Olympic Games were held every four years from 776 BC.", "The Olympic flame is still lit here, from the sun's rays, before every Games."],
    [["First Games", "776 BC"]], { also: ["Ancient Olympia"], forms: [{ f: "box", w: 64, d: 28, h: 3 }, ...[0, 1, 2, 3].map((i): Form => ({ f: "cyl", r: 1.1, h: 10, dx: -24 + i * 16, dy: 12, z: 3 })), { f: "box", w: 212, d: 32, h: 0.5, dx: 260, dy: 40 }],
      parts: [{ label: "Temple of Zeus", h: 13 }, { label: "The stadium", dx: 260, dy: 40, h: 2 }] }),
  P("mount-athos", "Mount Athos", "Chalkidiki, Greece", 24.3263, 40.157, 15000, [],
    ["A peninsula of twenty Orthodox monasteries, self-governing, where monks have lived since the 800s.", "Women have not been allowed in for a thousand years."],
    [["Monasteries", "20"], ["Summit", "2,033 m"]], { also: ["Athos"] }),
  P("rila-monastery", "Rila Monastery", "Rila Mountains, Bulgaria", 23.3403, 42.1335, 600, ["architecture", "art"],
    ["Founded in the 900s by the hermit St John of Rila and rebuilt after a fire in 1833.", "Its arcaded church is painted inside and out."],
    [["Founded", "900s"]], { forms: [{ f: "ring", rx: 75, ry: 55, ix: 60, iy: 40, h: 18 }, { f: "box", w: 30, d: 20, h: 14 }, { f: "box", w: 9, d: 9, h: 23, dx: 30 }] }),
  P("st-sophia-kyiv", "Saint Sophia Cathedral", "Kyiv, Ukraine", 30.5143, 50.4529, 400, ["architecture", "art"],
    ["Founded in the 1000s under Yaroslav the Wise, with mosaics and frescoes from that time.", "With the Kyiv Pechersk Lavra it is one of the oldest Christian sites of eastern Europe."],
    [["Founded", "1000s"]], { also: ["Kyiv", "St Sophia Kyiv", "Kyiv Pechersk Lavra"], forms: [{ f: "box", w: 40, d: 40, h: 18 }, { f: "cyl", r: 7, h: 8, z: 18 }, { f: "dome", r: 7, h: 9, z: 26 }, ...[[-13, -13], [13, -13], [-13, 13], [13, 13]].map(([dx, dy]): Form => ({ f: "dome", r: 4, h: 6, dx, dy, z: 18 })), { f: "box", w: 10, d: 10, h: 76, dy: -80 }] }),
  // ---- The Americas ---------------------------------------------------------------------------------
  P("independence-hall", "Independence Hall", "Philadelphia, Pennsylvania", -75.15, 39.9489, 400, ["architecture"],
    ["Where the Declaration of Independence (1776) and the Constitution (1787) were debated and signed.", "The Liberty Bell hangs in a pavilion across the street."],
    [["Declaration", "1776"], ["Constitution", "1787"]], { forms: [{ f: "box", w: 33, d: 14, h: 12 }, { f: "box", w: 9, d: 9, h: 30, dy: -10 }, { f: "cone", r: 4, h: 11, dy: -10, z: 30 }, { f: "box", w: 20, d: 12, h: 9, dx: -35 }, { f: "box", w: 20, d: 12, h: 9, dx: 35 }] }),
  P("mesa-verde", "Cliff Palace, Mesa Verde", "Colorado", -108.474, 37.1677, 500, ["architecture"],
    ["Ancestral Puebloan villages built into alcoves in the cliffs between about 1190 and 1280.", "Cliff Palace, the largest, has about 150 rooms."],
    [["Built", "about 1190–1280"], ["Rooms", "about 150"]], { also: ["Mesa Verde", "Cliff Palace"], forms: Array.from({ length: 9 }, (_, i): Form => ({ f: "box", w: 10, d: 8, h: 4 + (i % 3) * 3, dx: -45 + i * 11, dy: Math.abs(i - 4) * 3 })) }),
  P("everglades", "Everglades", "Florida", -80.9, 25.3, 30000, [],
    ["A slow river of sawgrass, tens of kilometres wide and a few centimetres deep, flowing to Florida Bay.", "The only place where alligators and crocodiles live side by side."],
    [["Park area", "about 6,100 km²"]], { also: ["Everglades National Park"] }),
  P("great-smoky", "Great Smoky Mountains", "Tennessee and North Carolina", -83.4985, 35.5628, 20000, [],
    ["Ancient mountains under a blue haze, with some of the richest temperate forests on Earth.", "The most visited national park in the United States."],
    [["Clingmans Dome", "2,025 m"]], { also: ["Great Smoky Mountains National Park", "Smoky Mountains", "Smokies"] }),
  P("kilauea", "Kīlauea", "Hawaiʻi Volcanoes National Park", -155.2834, 19.4069, 12000, [],
    ["One of the most active volcanoes on Earth, beside Mauna Loa, the largest.", "In Hawaiian tradition its crater is the home of Pele."],
    [["Summit", "1,247 m"]], { also: ["Hawaii Volcanoes National Park", "Kilauea"] }),
  P("carlsbad-caverns", "Carlsbad Caverns", "New Mexico", -104.4436, 32.1479, 3000, [],
    ["More than 100 caves in an ancient fossil reef; the Big Room is the largest single cave chamber in North America by volume.", "At dusk in summer, hundreds of thousands of bats fly out."],
    [["Big Room", "about 1.2 km long"]], { also: ["Carlsbad Caverns National Park"] }),
  P("pueblo-bonito", "Pueblo Bonito, Chaco Canyon", "New Mexico", -107.9563, 36.0604, 500, ["architecture"],
    ["The largest of Chaco's great houses, built in stages between about 850 and 1150, with some 650 rooms.", "Chaco's buildings line up with the sun and moon."],
    [["Rooms", "about 650"]], { also: ["Chaco Canyon", "Chaco Culture"], forms: [{ f: "stand", rx: 80, ry: 55, ix: 55, iy: 35, h: 12, n: 3, from: 0, to: 180 }, { f: "box", w: 160, d: 4, h: 6 }] }),
  P("taos-pueblo", "Taos Pueblo", "New Mexico", -105.5455, 36.4398, 400, ["architecture"],
    ["Multi-storey adobe houses lived in for about a thousand years.", "No electricity or running water is allowed in the old town."],
    [["Lived in for", "about 1,000 years"]], { forms: [{ f: "steps", w: 60, top: 15, h: 15, n: 5 }, { f: "steps", w: 40, top: 12, h: 12, n: 4, dx: 70, dy: -50 }] }),
  P("redwood", "Redwood National Park", "California", -124.0046, 41.2132, 8000, [],
    ["The tallest trees on Earth: coast redwoods over 100 m high, some more than 2,000 years old.", "The tallest known, Hyperion, at about 116 m, grows here, its exact place kept secret."],
    [["Tallest tree", "about 116 m"]], { also: ["Redwoods", "Redwood National and State Parks"] }),
  P("monticello", "Monticello", "Charlottesville, Virginia", -78.4532, 38.0086, 400, ["architecture"],
    ["Thomas Jefferson's house, which he designed and redesigned for forty years.", "It is pictured on the back of the US nickel."],
    [["Begun", "1769"]], { forms: [{ f: "box", w: 34, d: 26, h: 10 }, { f: "cyl", r: 8, h: 3, z: 10 }, { f: "dome", r: 8, h: 5, z: 13 }, { f: "box", w: 12, d: 8, h: 9, dy: -17 }] }),
  P("mammoth-cave", "Mammoth Cave", "Kentucky", -86.1, 37.187, 6000, [],
    ["The longest known cave system in the world, with more than 680 km mapped.", "It is still being explored."],
    [["Mapped", "more than 680 km"]], { also: ["Mammoth Cave National Park"] }),
  P("moraine-lake", "Moraine Lake", "Banff National Park, Canada", -116.1773, 51.3217, 5000, [],
    ["A glacier-fed lake in the Valley of the Ten Peaks, its colour from rock flour ground by the ice.", "Banff is one of the Canadian Rocky Mountain parks, which hold the Burgess Shale fossils."],
    [["Elevation", "about 1,885 m"]], { also: ["Banff", "Banff National Park", "Lake Louise", "Canadian Rockies"] }),
  P("old-quebec", "Old Québec", "Québec City, Canada", -71.2058, 46.8123, 900, ["architecture"],
    ["The only walled city in North America north of Mexico, founded by Champlain in 1608.", "The Château Frontenac, a railway hotel of 1893, stands over it."],
    [["Founded", "1608"]], { also: ["Quebec City", "Château Frontenac", "Chateau Frontenac"], forms: [{ f: "box", w: 70, d: 40, h: 30 }, { f: "box", w: 20, d: 20, h: 60, dx: 10 }, { f: "pyramid", w: 20, h: 18, dx: 10, z: 60 }] }),
  P("palenque", "Palenque", "Chiapas, Mexico", -92.0465, 17.4838, 900, ["architecture"],
    ["A Maya city at the edge of the rainforest; its king Pakal was buried in 683 inside the Temple of the Inscriptions.", "Its palace has a four-storey tower, perhaps for watching the sky."],
    [["Pakal buried", "683"]], { forms: [{ f: "steps", w: 60, top: 25, h: 22, n: 9, dx: -90, dy: -30 }, { f: "box", w: 22, d: 12, h: 7, dx: -90, dy: -30, z: 22 }, { f: "box", w: 100, d: 80, h: 10, dx: 30 }, { f: "box", w: 7, d: 7, h: 15, dx: 30, z: 10 }],
      parts: [{ label: "Temple of the Inscriptions", dx: -90, dy: -30, h: 30 }, { label: "The Palace", dx: 30, h: 25 }] }),
  P("uxmal", "Uxmal", "Yucatán, Mexico", -89.7713, 20.3597, 800, ["architecture"],
    ["A Puuc Maya city of finely carved stone, at its height in the 800s and 900s.", "Its Pyramid of the Magician has rounded ends, unusual in the Maya world."],
    [["Pyramid of the Magician", "about 35 m"]], { forms: [{ f: "frustum", w: 70, top: 25, h: 35 }, { f: "ring", rx: 50, ry: 40, ix: 32, iy: 22, h: 8, dy: -130 }] }),
  P("guanajuato", "Guanajuato", "Guanajuato, Mexico", -101.2567, 21.017, 1500, ["architecture"],
    ["A silver-mining town of colourful houses climbing a ravine, with roads running in old riverbeds underground.", "The War of Independence began nearby in 1810."],
    [["Founded", "1500s"]]),
  P("monte-alban", "Monte Albán", "Oaxaca, Mexico", -96.7676, 17.0437, 1000, ["architecture"],
    ["The Zapotec capital on a flattened mountaintop above the valley of Oaxaca, lived in for about 1,500 years.", "Its Danzantes carvings are among the oldest in Mesoamerica."],
    [["Founded", "about 500 BC"]], { also: ["Oaxaca"], forms: [{ f: "box", w: 300, d: 150, h: 1, rot: 90 }, { f: "steps", w: 60, top: 40, h: 12, n: 3, dy: 170 }, { f: "steps", w: 70, top: 50, h: 12, n: 3, dy: -170 }, { f: "box", w: 30, d: 60, h: 8 }] }),
  P("cusco", "Cusco", "Cusco, Peru", -71.9787, -13.5167, 1200, ["architecture"],
    ["Capital of the Inca empire; the Spanish built their churches and houses on Inca walls.", "Above it, the zigzag walls of Sacsayhuamán use stones of over 100 tonnes."],
    [["Altitude", "about 3,400 m"]], { also: ["Cuzco", "Sacsayhuamán", "Sacsayhuaman"], forms: [{ f: "box", w: 85, d: 50, h: 25, dy: 50 }, ...spire(-35, 70, 11, 35, 4), ...spire(35, 70, 11, 35, 4), { f: "box", w: 130, d: 130, h: 0.5 }] }),
  P("quito", "City of Quito", "Quito, Ecuador", -78.5121, -0.22, 1200, ["architecture"],
    ["One of the best-kept historic centres in the Americas, at 2,850 m in the Andes.", "With Kraków it was among the first places on the World Heritage List."],
    [["Altitude", "about 2,850 m"]], { also: ["Quito"] }),
  P("ouro-preto", "Ouro Preto", "Minas Gerais, Brazil", -43.5047, -20.3856, 1200, ["architecture", "art"],
    ["A gold-rush town of the 1700s, with baroque churches by the sculptor Aleijadinho.", "Its gold paid for much of Portugal's building in that century."],
    [["Founded", "1711"]]),
  P("pelourinho", "Pelourinho, Salvador", "Bahia, Brazil", -38.5108, -12.9718, 800, ["architecture", "music"],
    ["The colonial heart of Salvador, Brazil's first capital, with pastel houses and gilded churches.", "Afro-Brazilian music and capoeira fill its streets."],
    [["Founded", "1549"]], { also: ["Salvador", "Salvador da Bahia", "Pelourinho"] }),
  P("valparaiso", "Valparaíso", "Valparaíso, Chile", -71.627, -33.0458, 2000, ["art"],
    ["A port city of colourful houses on steep hills, joined by funiculars built from the 1880s.", "It was the main stop for ships rounding Cape Horn before the Panama Canal."],
    [["Funiculars built from", "1883"]], { also: ["Valparaiso"] }),
  P("antigua-guatemala", "Antigua Guatemala", "Sacatepéquez, Guatemala", -90.7344, 14.5586, 1500, ["architecture"],
    ["The old Spanish capital of Central America, laid out in a grid under three volcanoes.", "After earthquakes in 1773 the capital moved; the ruined churches were left standing."],
    [["Capital until", "1773"]], { also: ["Antigua"] }),
  P("copan", "Copán", "Copán, Honduras", -89.1405, 14.8378, 700, ["architecture", "art"],
    ["A Maya city famous for its carved stelae and its Hieroglyphic Stairway, the longest Maya text known.", "Its dynasty ruled for about 400 years."],
    [["Glyphs on the stairway", "about 2,200"]], { also: ["Copan"], forms: [{ f: "steps", w: 30, top: 10, h: 20, n: 10 }, { f: "box", w: 120, d: 80, h: 0.5, dy: 100 }] }),
  P("chan-chan", "Chan Chan", "La Libertad, Peru", -79.0747, -8.1078, 1500, ["architecture"],
    ["Capital of the Chimú kingdom, the largest city of earth and adobe in the Americas.", "Its walls are carved with fish, birds and waves."],
    [["Area", "about 20 km²"]], { also: ["Chan Chan Archaeological Zone"], forms: [{ f: "ring", rx: 220, ry: 140, ix: 215, iy: 135, h: 9 }, { f: "ring", rx: 90, ry: 70, ix: 86, iy: 66, h: 7, dx: -60 }] }),
  P("great-blue-hole", "Great Blue Hole", "Belize Barrier Reef", -87.535, 17.3157, 1500, [],
    ["A marine sinkhole about 300 m across and 125 m deep, in the Belize Barrier Reef.", "Stalactites inside show it was a dry cave in the last ice age."],
    [["Across", "about 300 m"], ["Deep", "about 125 m"]], { also: ["Blue Hole", "Belize Barrier Reef"] }),
  P("tiwanaku", "Tiwanaku", "La Paz, Bolivia", -68.6738, -16.5546, 700, ["architecture"],
    ["Capital of a culture that ruled around Lake Titicaca from about 500 to 1000.", "Its Gate of the Sun is cut from a single block of andesite."],
    [["Altitude", "about 3,850 m"]], { also: ["Tiahuanaco", "Gate of the Sun"], forms: [{ f: "box", w: 130, d: 120, h: 3 }, { f: "box", w: 4, d: 1, h: 3, dx: 40 }, { f: "steps", w: 190, top: 160, h: 16, n: 7, dx: -220 }] }),
  // ---- Africa and the Middle East -------------------------------------------------------------------
  P("karnak", "Karnak", "Luxor, Egypt", 32.6573, 25.7188, 900, ["architecture"],
    ["The largest religious complex of ancient Egypt, built up over some 2,000 years for the god Amun.", "Its Hypostyle Hall holds 134 giant columns, the tallest 21 m."],
    [["Columns in the Hypostyle Hall", "134"], ["Tallest", "21 m"]], { also: ["Karnak Temple", "Luxor", "Thebes"], forms: [{ f: "box", w: 113, d: 15, h: 43, dx: -110 }, { f: "box", w: 103, d: 52, h: 21, dx: -40, rot: 90 }, { f: "box", w: 80, d: 12, h: 30, dx: 10 }, { f: "box", w: 2.5, d: 2.5, h: 29, dx: 40 }, { f: "box", w: 200, d: 80, h: 6, dx: 140 }],
      parts: [{ label: "First pylon", dx: -110, h: 43 }, { label: "Hypostyle Hall", dx: -40, h: 22 }, { label: "Obelisk of Hatshepsut", dx: 40, h: 29 }] }),
  P("valley-of-the-kings", "Valley of the Kings", "West Bank, Luxor, Egypt", 32.6014, 25.7402, 2000, [],
    ["Tombs of New Kingdom pharaohs cut into the hills across the Nile from Luxor.", "Tutankhamun's tomb, found almost untouched in 1922, is here."],
    [["Tombs", "more than 60"], ["Tutankhamun found", "1922"]], { also: ["Tutankhamun's tomb"] }),
  P("luxor-temple", "Luxor Temple", "Luxor, Egypt", 32.639, 25.6995, 500, ["architecture"],
    ["Built mainly by Amenhotep III and Ramesses II, joined to Karnak by an avenue of sphinxes nearly 3 km long.", "One of its pair of obelisks now stands in the Place de la Concorde in Paris."],
    [["Avenue of Sphinxes", "about 2.7 km"]], { forms: [{ f: "box", w: 65, d: 12, h: 24, dy: 110 }, { f: "box", w: 2.5, d: 2.5, h: 25, dx: -15, dy: 125 }, { f: "box", w: 50, d: 200, h: 12, dy: -20 }] }),
  P("fez-medina", "Medina of Fez", "Fez, Morocco", -4.9773, 34.0646, 1500, ["food", "retail"],
    ["Fez el-Bali, one of the largest car-free urban areas in the world, a maze of some 9,000 lanes.", "Its al-Qarawiyyin, founded in 859, is often called the oldest university still working."],
    [["Al-Qarawiyyin founded", "859"]], { also: ["Fez", "Fes", "Fes el-Bali", "Chouara Tannery"] }),
  P("ait-benhaddou", "Aït Benhaddou", "Ouarzazate, Morocco", -7.129, 31.047, 600, ["architecture"],
    ["A fortified village of earth and clay on a caravan route across the Atlas.", "It has stood in for Jerusalem, Rome and Yunkai in films and television."],
    [["On the caravan route to", "Marrakesh"]], { also: ["Ait Benhaddou"], forms: [{ f: "steps", w: 160, top: 40, h: 30, n: 6 }, ...[[-40, -40], [40, -40], [-40, 40], [40, 40]].map(([dx, dy]): Form => ({ f: "box", w: 10, d: 10, h: 18, dx, dy, z: 10 }))] }),
  P("volubilis", "Volubilis", "Meknes, Morocco", -5.5547, 34.0742, 800, ["architecture", "art"],
    ["A Roman city at the edge of the empire, known for its mosaics and triumphal arch.", "It was lived in long after the Romans left."],
    [["Arch of Caracalla", "217"]], { forms: [{ f: "box", w: 20, d: 4, h: 12 }, ...[0, 1, 2, 3, 4].map((i): Form => ({ f: "cyl", r: 0.8, h: 12, dx: 40 + i * 5, dy: 30 })), { f: "box", w: 40, d: 25, h: 3, dx: 45, dy: 25 }] }),
  P("carthage", "Carthage", "Tunis, Tunisia", 10.3233, 36.8528, 2000, ["architecture"],
    ["The Phoenician city that fought Rome for the Mediterranean, destroyed in 146 BC and rebuilt as a Roman city.", "Its round naval harbour could hold some 200 warships."],
    [["Destroyed", "146 BC"]], { forms: [{ f: "ring", rx: 160, ry: 160, ix: 110, iy: 110, h: 1 }, { f: "cyl", r: 35, h: 4 }] }),
  P("el-djem", "Amphitheatre of El Jem", "El Djem, Tunisia", 10.7069, 35.2963, 500, ["architecture", "sport"],
    ["One of the largest Roman amphitheatres, built about AD 238 for some 35,000 spectators.", "It stands almost whole in the middle of a small town."],
    [["Seats", "about 35,000"], ["Built", "about AD 238"]], { also: ["El Jem", "El Djem"], forms: [{ f: "stand", rx: 74, ry: 61, ix: 32, iy: 19, h: 30, n: 5 }, { f: "ring", rx: 74, ry: 61, ix: 71, iy: 58, h: 36 }] }),
  P("leptis-magna", "Leptis Magna", "Khoms, Libya", 14.2904, 32.6383, 1200, ["architecture"],
    ["Birthplace of the emperor Septimius Severus, who made it one of the finest cities of Roman Africa.", "Sand kept it well until it was dug out in the 1900s."],
    [["Severan arch", "about 203"]], { forms: [{ f: "stand", rx: 70, ry: 70, ix: 20, iy: 20, h: 15, n: 4, from: 0, to: 180 }, { f: "box", w: 100, d: 60, h: 2, dx: 150 }] }),
  P("robben-island", "Robben Island", "Table Bay, South Africa", 18.3667, -33.8064, 4000, [],
    ["An island prison where Nelson Mandela spent 18 of his 27 years in jail.", "It is now a museum, often guided by former prisoners."],
    [["Mandela held here", "1964–1982"]]),
  P("goree", "Gorée Island", "Dakar, Senegal", -17.3983, 14.6672, 800, [],
    ["A small island off Dakar that was a centre of the Atlantic slave trade.", "Its House of Slaves, with its Door of No Return, is a memorial."],
    [["Island length", "about 900 m"]], { also: ["Goree", "Île de Gorée", "House of Slaves"] }),
  P("lamu", "Lamu Old Town", "Lamu, Kenya", 40.902, -2.2717, 800, ["architecture"],
    ["The oldest and best-kept Swahili town in East Africa, lived in for over 700 years.", "There are almost no cars; donkeys carry the loads."],
    [["Lived in for", "over 700 years"]], { also: ["Lamu"] }),
  P("baalbek", "Baalbek", "Beqaa Valley, Lebanon", 36.2039, 34.0069, 700, ["architecture"],
    ["Roman temples on a colossal scale: six columns of the Temple of Jupiter still stand about 20 m tall.", "Its foundations hold some of the largest stones ever moved, of about 800 tonnes."],
    [["Jupiter's columns", "about 20 m"]], { forms: [{ f: "box", w: 90, d: 50, h: 7 }, ...[0, 1, 2, 3, 4, 5].map((i): Form => ({ f: "cyl", r: 1.1, h: 20, dx: -25 + i * 5, dy: -20, z: 7 })), { f: "box", w: 35, d: 66, h: 15, dx: 20, dy: -80 }],
      parts: [{ label: "Temple of Jupiter", dy: -20, h: 27 }, { label: "Temple of Bacchus", dx: 20, dy: -80, h: 15 }] }),
  P("byblos", "Byblos", "Mount Lebanon, Lebanon", 35.644, 34.1197, 600, [],
    ["One of the oldest towns lived in without a break, since the Neolithic.", "Papyrus was traded through it to Greece, which named books after it."],
    [["Lived in since", "about 7000 BC"]], { also: ["Jbeil"] }),
  P("krak-des-chevaliers", "Krak des Chevaliers", "Homs, Syria", 36.2945, 34.757, 500, ["architecture"],
    ["A Crusader castle held by the Knights Hospitaller from 1142, with two rings of walls.", "T. E. Lawrence called it the most wholly admirable castle in the world."],
    [["Held by the Hospitallers from", "1142"]], { forms: [{ f: "ring", rx: 105, ry: 70, ix: 98, iy: 63, h: 15 }, { f: "ring", rx: 70, ry: 50, ix: 60, iy: 40, h: 25 }, ...[[-60, -40], [60, -40], [-60, 40], [60, 40]].map(([dx, dy]): Form => ({ f: "cyl", r: 9, h: 30, dx, dy }))] }),
  P("umayyad-mosque", "Umayyad Mosque", "Damascus, Syria", 36.3069, 33.5115, 500, ["architecture", "art"],
    ["One of the oldest and largest mosques, built from 705 on the site of a Roman temple and a church.", "Its courtyard is lined with golden mosaics of gardens and cities."],
    [["Built", "705–715"]], { also: ["Damascus", "Great Mosque of Damascus"], forms: [{ f: "box", w: 157, d: 50, h: 20, dy: -40 }, { f: "ring", rx: 79, ry: 50, ix: 74, iy: 45, h: 10, dy: 10 }, { f: "dome", r: 10, h: 18, dy: -40, z: 20 }, { f: "box", w: 7, d: 7, h: 50, dx: 75, dy: -60 }] }),
  P("babylon", "Babylon", "Babil, Iraq", 44.4209, 32.5422, 2000, ["architecture"],
    ["Capital of Hammurabi and Nebuchadnezzar, by the Euphrates.", "Its Ishtar Gate of blue glazed brick was taken to Berlin, where it stands in the Pergamon Museum."],
    [["Nebuchadnezzar II", "605–562 BC"]], { forms: [{ f: "box", w: 30, d: 15, h: 15 }, { f: "box", w: 600, d: 8, h: 5, dy: 200 }] }),
  P("hegra", "Hegra", "AlUla, Saudi Arabia", 37.9539, 26.7914, 3000, ["architecture"],
    ["The Nabataeans' southern city, with over 100 tombs cut into sandstone outcrops.", "Qasr al-Farid, a lone tomb in a single rock, was never finished."],
    [["Tombs", "more than 100"]], { also: ["Mada'in Salih", "AlUla", "Qasr al-Farid"] }),
  P("naqsh-e-jahan", "Naqsh-e Jahan Square", "Isfahan, Iran", 51.6776, 32.6575, 1000, ["architecture", "art", "retail"],
    ["Shah Abbas's royal square of the early 1600s, one of the largest city squares in the world.", "The Shah Mosque, the Ali Qapu palace and the Sheikh Lotfollah Mosque face each other across it."],
    [["Square", "about 560 m × 160 m"]], { also: ["Isfahan", "Imam Square", "Shah Mosque"], forms: [{ f: "ring", rx: 290, ry: 90, ix: 280, iy: 80, h: 12, rot: 90 }, { f: "dome", r: 25, h: 50, dy: -330 }, { f: "cyl", r: 3, h: 42, dx: -20, dy: -300 }, { f: "cyl", r: 3, h: 42, dx: 20, dy: -300 }, { f: "dome", r: 12, h: 15, dx: 90 }, { f: "box", w: 25, d: 30, h: 38, dx: -90 }] }),
  P("ephesus", "Ephesus", "İzmir, Türkiye", 27.3404, 37.9395, 1200, ["architecture"],
    ["A great Greek and Roman port city whose harbour silted up, leaving it inland.", "The façade of the Library of Celsus, built about 117, has been set up again."],
    [["Library of Celsus", "about 117"]], { also: ["Efes", "Library of Celsus"], forms: [{ f: "box", w: 21, d: 6, h: 16 }, { f: "stand", rx: 75, ry: 75, ix: 20, iy: 20, h: 30, n: 5, from: 200, to: 340, dx: 120, dy: 300 }],
      parts: [{ label: "Library of Celsus", h: 16 }, { label: "Great Theatre", dx: 120, dy: 260, h: 30 }] }),
  P("pamukkale", "Pamukkale", "Denizli, Türkiye", 29.121, 37.9214, 2000, [],
    ["White terraces of travertine left by hot springs flowing down the hillside.", "The Roman spa city of Hierapolis was built above them."],
    [["Water", "about 35 °C"]], { also: ["Hierapolis", "Cotton Castle"] }),
  P("troy", "Troy", "Çanakkale, Türkiye", 26.239, 39.9573, 600, [],
    ["A mound of nine cities built one on another over 4,000 years.", "Heinrich Schliemann dug here from 1871, looking for Homer's Troy."],
    [["Cities, one on another", "9"]], { also: ["Truva", "Hisarlik"] }),
  P("nemrut", "Mount Nemrut", "Adıyaman, Türkiye", 38.7408, 37.981, 800, ["art"],
    ["A king's tomb mound on a mountaintop, guarded by colossal stone heads of gods and lions.", "Antiochus I of Commagene built it in the first century BC."],
    [["Summit", "2,134 m"]], { also: ["Nemrut Dağ", "Nemrut Dag"], forms: [{ f: "cone", r: 75, h: 50 }, ...[-20, -10, 0, 10, 20].map((dx): Form => ({ f: "box", w: 4, d: 4, h: 8, dx, dy: -85 }))] }),
  P("masada", "Masada", "Judaean Desert", 35.3536, 31.3156, 1500, [],
    ["Herod's palace-fortress on a mesa above the Dead Sea.", "Its defenders held out against Rome until AD 73 or 74; the siege ramp is still there."],
    [["Above the Dead Sea", "about 400 m"]], { forms: [{ f: "box", w: 600, d: 250, h: 20, rot: -20 }] }),
  P("bahai-gardens", "Bahá'í Gardens", "Haifa, Israel", 34.9871, 32.8143, 1000, ["architecture"],
    ["Nineteen terraced gardens climbing Mount Carmel to the golden-domed Shrine of the Báb.", "They are the Bahá'í faith's most holy place after Bahjí."],
    [["Terraces", "19"]], { also: ["Bahai Gardens", "Shrine of the Báb"], forms: [{ f: "steps", w: 120, top: 40, h: 60, n: 10 }, { f: "box", w: 25, d: 25, h: 15, z: 60 }, { f: "dome", r: 8, h: 10, z: 75 }] }),
  P("socotra", "Socotra", "Arabian Sea, Yemen", 53.9, 12.5, 40000, [],
    ["An island so long isolated that over a third of its plants grow nowhere else.", "Its dragon's blood trees look like umbrellas turned inside out."],
    [["Plants found only here", "about 37%"]]),
  P("shibam", "Shibam", "Hadhramaut, Yemen", 48.6264, 15.9266, 500, ["architecture"],
    ["A walled town of mud-brick tower houses up to eight storeys, the Manhattan of the desert.", "Most date from the 1500s and are rebuilt as they wear."],
    [["Tallest houses", "about 30 m"]], { forms: grid(6, 4, 22, () => [{ f: "box", w: 16, d: 16, h: 26 }]) }),
  P("sanaa", "Old City of Sana'a", "Sana'a, Yemen", 44.2141, 15.3556, 1200, ["architecture"],
    ["Rammed-earth tower houses trimmed in white gypsum, lived in for more than 2,500 years.", "It has over 100 mosques and 6,000 houses from before the 1000s."],
    [["Altitude", "about 2,200 m"]], { also: ["Sanaa"] }),
  P("wadi-al-hitan", "Wadi Al-Hitan", "Faiyum, Egypt", 30.0333, 29.2667, 4000, [],
    ["The Valley of Whales: fossil skeletons of early whales that still had hind legs, in the desert.", "They show whales evolving from land mammals."],
    [["Fossils", "about 40 million years old"]], { also: ["Valley of the Whales"] }),
  P("bwindi", "Bwindi Impenetrable Forest", "Uganda", 29.66, -1.05, 15000, [],
    ["A mountain rainforest that shelters about half the world's mountain gorillas.", "Some gorilla families can be visited on foot."],
    [["Mountain gorillas", "about half of all"]], { also: ["Bwindi"] }),
  P("mount-kenya", "Mount Kenya", "Kenya", 37.3083, -0.1521, 15000, [],
    ["Africa's second-highest mountain, an extinct volcano with glaciers on the equator.", "It gave Kenya its name."],
    [["Batian", "5,199 m"]]),
  P("simien", "Simien Mountains", "Amhara, Ethiopia", 38.0667, 13.1833, 20000, [],
    ["Jagged peaks and sheer drops of 1,500 m, home of gelada monkeys and the Walia ibex.", "Ras Dashen, Ethiopia's highest peak, rises at its edge."],
    [["Ras Dashen", "4,550 m"]], { also: ["Simien National Park"] }),
  // ---- Asia and the Pacific -------------------------------------------------------------------------
  P("temple-of-heaven", "Temple of Heaven", "Beijing, China", 116.4074, 39.8822, 600, ["architecture"],
    ["Where Ming and Qing emperors prayed for good harvests, built from 1406.", "The Hall of Prayer, round under three blue roofs, is held up without a single nail."],
    [["Hall of Prayer", "38 m"]], { also: ["Tiantan"], forms: [{ f: "cyl", r: 45, h: 2 }, { f: "cyl", r: 38, h: 2, z: 2 }, { f: "cyl", r: 31, h: 2, z: 4 }, { f: "cyl", r: 16, h: 12, z: 6 }, { f: "cone", r: 19, h: 6, z: 18 }, { f: "cyl", r: 13, h: 4, z: 22 }, { f: "cone", r: 15, h: 5, z: 26 }, { f: "cyl", r: 9, h: 3, z: 31 }, { f: "cone", r: 11, h: 5, z: 34 }] }),
  P("summer-palace", "Summer Palace", "Beijing, China", 116.2755, 39.9999, 2500, ["architecture"],
    ["Imperial gardens of lakes, halls and pavilions, rebuilt by the Empress Dowager Cixi in the 1880s.", "The Long Corridor runs 728 m along Kunming Lake, painted all the way."],
    [["Long Corridor", "728 m"]], { also: ["Yiheyuan"], forms: [{ f: "steps", w: 60, top: 25, h: 30, n: 4, dy: 150 }, { f: "cyl", r: 8, h: 41, dy: 150, z: 30 }, { f: "box", w: 728, d: 4, h: 4, dy: 80 }] }),
  P("huangshan", "Huangshan", "Anhui, China", 118.1667, 30.1333, 12000, ["art"],
    ["The Yellow Mountains: granite peaks, twisted pines and a sea of clouds, painted for centuries.", "Some 60,000 stone steps climb them."],
    [["Lotus Peak", "1,864 m"]], { also: ["Yellow Mountain", "Mount Huangshan"] }),
  P("west-lake", "West Lake", "Hangzhou, China", 120.1445, 30.2427, 6000, ["art"],
    ["A lake of causeways, temples and pagodas that set a model for gardens across China, Japan and Korea.", "Poets and painters have shaped it for a thousand years."],
    [["Area", "about 6.4 km²"]], { also: ["Hangzhou", "Xihu"] }),
  P("mogao-caves", "Mogao Caves", "Dunhuang, China", 94.809, 40.0418, 1000, ["art"],
    ["Nearly 500 Buddhist cave temples on the Silk Road, painted over a thousand years.", "A sealed library cave held the Diamond Sutra of 868, the oldest dated printed book."],
    [["Caves", "about 492"], ["Diamond Sutra", "868"]], { also: ["Dunhuang", "Mogao Grottoes"] }),
  P("lijiang", "Old Town of Lijiang", "Yunnan, China", 100.233, 26.8721, 1200, ["architecture"],
    ["A Naxi market town of canals and tiled roofs under Jade Dragon Snow Mountain.", "Water from the springs runs through the streets."],
    [["Altitude", "about 2,400 m"]], { also: ["Lijiang"] }),
  P("jiuzhaigou", "Jiuzhaigou", "Sichuan, China", 103.9, 33.2, 15000, [],
    ["A valley of turquoise lakes, waterfalls and Tibetan villages.", "The colours come from travertine and dissolved minerals."],
    [["Lakes", "more than 100"]]),
  P("leshan-buddha", "Leshan Giant Buddha", "Sichuan, China", 103.7699, 29.5446, 500, ["art"],
    ["A Buddha 71 m tall cut into the cliff where three rivers meet, carved from 713 to 803.", "It was made to calm the waters for boats."],
    [["Height", "71 m"], ["Carved", "713–803"]], { also: ["Leshan"], forms: [{ f: "box", w: 28, d: 10, h: 71 }] }),
  P("suzhou-gardens", "Classical Gardens of Suzhou", "Suzhou, China", 120.629, 31.3236, 600, ["art", "architecture"],
    ["Scholars' gardens of rock, water and pavilions, made between the 1000s and 1800s.", "The Humble Administrator's Garden is the largest."],
    [["Gardens listed", "9"]], { also: ["Suzhou", "Humble Administrator's Garden"] }),
  P("pingyao", "Ancient City of Pingyao", "Shanxi, China", 112.1817, 37.2011, 2000, ["architecture"],
    ["A Ming and Qing walled town, where China's first banks opened.", "Its walls, about 6 km round, have 72 watchtowers."],
    [["Walls", "about 6 km"]], { also: ["Pingyao"], forms: [{ f: "ring", rx: 800, ry: 700, ix: 790, iy: 690, h: 12 }] }),
  P("himeji-castle", "Himeji Castle", "Hyōgo, Japan", 134.6939, 34.8394, 600, ["architecture"],
    ["The White Heron: a castle finished in 1609, never besieged and never bombed.", "Its plastered walls are made to resist fire."],
    [["Finished", "1609"], ["Keep", "about 46 m above the base"]], { also: ["Himeji"], forms: [{ f: "frustum", w: 55, top: 42, h: 14 }, { f: "steps", w: 40, top: 18, h: 32, n: 6, z: 14 }, { f: "pyramid", w: 18, h: 6, z: 46 }, { f: "steps", w: 22, top: 12, h: 18, n: 3, dx: -40, dy: 20, z: 10 }] }),
  P("kinkaku-ji", "Kinkaku-ji", "Kyoto, Japan", 135.7292, 35.0394, 400, ["architecture", "art"],
    ["The Golden Pavilion, its upper floors covered in gold leaf, beside a mirror pond.", "Burned by a monk in 1950, it was rebuilt in 1955."],
    [["Rebuilt", "1955"]], { also: ["Golden Pavilion", "Kyoto"], forms: [{ f: "box", w: 18, d: 14, h: 5 }, { f: "box", w: 15, d: 12, h: 4, z: 5 }, { f: "box", w: 10, d: 10, h: 3.5, z: 9 }, { f: "pyramid", w: 14, h: 3.5, z: 12.5 }] }),
  P("todai-ji", "Tōdai-ji", "Nara, Japan", 135.8398, 34.689, 500, ["architecture", "art"],
    ["A temple whose Great Buddha Hall shelters a bronze Buddha 15 m tall, cast in 752.", "Deer roam the park around it."],
    [["Great Buddha", "about 15 m"], ["Hall", "about 49 m"]], { also: ["Todaiji", "Nara", "Great Buddha of Nara"], forms: [{ f: "box", w: 57, d: 50, h: 28 }, { f: "pyramid", w: 60, h: 21, z: 28 }] }),
  P("hiroshima-peace", "Hiroshima Peace Memorial", "Hiroshima, Japan", 132.4536, 34.3955, 500, [],
    ["The A-Bomb Dome, the building nearest the atomic bomb's hypocentre on 6 August 1945 left standing.", "It is kept as it was, as a call for a world without nuclear weapons."],
    [["Bombed", "6 August 1945"]], { also: ["A-Bomb Dome", "Genbaku Dome", "Hiroshima"], forms: [{ f: "box", w: 30, d: 20, h: 15 }, { f: "box", w: 12, d: 12, h: 8, z: 15 }, { f: "dome", r: 6, h: 5, z: 23 }] }),
  P("itsukushima", "Itsukushima Shrine", "Miyajima, Japan", 132.3196, 34.296, 600, ["architecture"],
    ["A Shinto shrine built over the water, with a great torii that seems to float at high tide.", "Its form dates from the 1100s."],
    [["Torii", "about 16 m"]], { also: ["Miyajima", "Floating torii"], forms: [{ f: "cyl", r: 1.2, h: 16, dx: -8, dy: -170 }, { f: "cyl", r: 1.2, h: 16, dx: 8, dy: -170 }, { f: "box", w: 24, d: 2, h: 1.5, dy: -170, z: 16 }, { f: "box", w: 120, d: 60, h: 6 }] }),
  P("nikko", "Nikkō Tōshō-gū", "Tochigi, Japan", 139.5994, 36.758, 800, ["architecture", "art"],
    ["The richly carved, gilded shrine of Tokugawa Ieyasu, founder of the shogunate.", "Its Three Wise Monkeys carving is the original of see no evil, hear no evil, speak no evil."],
    [["Built", "1617, rebuilt 1636"]], { also: ["Nikko", "Toshogu"] }),
  P("shirakawa-go", "Shirakawa-gō", "Gifu, Japan", 136.9063, 36.2577, 800, ["architecture"],
    ["Mountain villages of gasshō-zukuri farmhouses, their steep thatched roofs like hands joined in prayer.", "The roofs shed heavy snow; silkworms were raised in the attics."],
    [["Roof pitch", "about 60°"]], { also: ["Shirakawa-go", "Gokayama"], forms: grid(4, 3, 40, () => [{ f: "box", w: 20, d: 10, h: 3 }, { f: "pyramid", w: 16, h: 12, z: 3 }]) }),
  P("yakushima", "Yakushima", "Kagoshima, Japan", 130.5, 30.35, 25000, [],
    ["An island of ancient cedars, some thought to be thousands of years old, under heavy rain.", "Its moss forests inspired Princess Mononoke."],
    [["Jōmon Sugi", "perhaps 2,000+ years"]]),
  P("bulguksa", "Bulguksa", "Gyeongju, South Korea", 129.332, 35.79, 500, ["architecture"],
    ["A Silla temple of 751 with stone bridges and two famous stone pagodas.", "Above it, the Seokguram grotto holds a granite Buddha facing the sea."],
    [["Built", "751"]], { also: ["Gyeongju", "Seokguram"] }),
  P("changdeokgung", "Changdeokgung", "Seoul, South Korea", 126.991, 37.5794, 700, ["architecture"],
    ["A Joseon palace of 1405 laid out to follow the hills, with a secret garden behind it.", "It was the kings' favourite palace."],
    [["Built", "1405"]], { also: ["Secret Garden", "Huwon"] }),
  P("red-fort", "Red Fort", "Delhi, India", 77.241, 28.6562, 1200, ["architecture"],
    ["Shah Jahan's palace-fortress of red sandstone, built from 1639 to 1648.", "India's prime minister speaks from its ramparts every Independence Day."],
    [["Built", "1639–1648"]], { also: ["Lal Qila", "Lal Qila Delhi"], forms: [{ f: "ring", rx: 250, ry: 450, ix: 242, iy: 442, h: 18 }, { f: "box", w: 30, d: 20, h: 33, dx: 250 }] }),
  P("agra-fort", "Agra Fort", "Agra, India", 78.0211, 27.1795, 900, ["architecture"],
    ["The Mughals' red sandstone fortress, rebuilt by Akbar from 1565.", "Shah Jahan was kept here by his son and could see the Taj Mahal from his rooms."],
    [["Rebuilt from", "1565"]], { forms: [{ f: "ring", rx: 300, ry: 250, ix: 292, iy: 242, h: 20 }] }),
  P("fatehpur-sikri", "Fatehpur Sikri", "Agra, India", 77.661, 27.0945, 900, ["architecture"],
    ["Akbar's red sandstone capital, built in the 1570s and left soon after, perhaps for lack of water.", "The Buland Darwaza gate is 54 m high."],
    [["Buland Darwaza", "54 m"]], { forms: [{ f: "box", w: 40, d: 25, h: 54 }, { f: "box", w: 160, d: 130, h: 10, dy: -90 }] }),
  P("humayuns-tomb", "Humayun's Tomb", "Delhi, India", 77.2507, 28.5933, 500, ["architecture"],
    ["The first great garden tomb of the Mughals, finished in 1572, a model for the Taj Mahal.", "It stands in a garden divided by water channels into four parts."],
    [["Finished", "1572"], ["Height", "about 47 m"]], { also: ["Humayun Tomb"], forms: [{ f: "box", w: 120, d: 120, h: 7 }, { f: "box", w: 50, d: 50, h: 20, z: 7 }, { f: "cyl", r: 14, h: 6, z: 27 }, { f: "dome", r: 15, h: 18, z: 33 }] }),
  P("ajanta", "Ajanta Caves", "Maharashtra, India", 75.7033, 20.5519, 800, ["art"],
    ["About thirty Buddhist caves cut into a horseshoe cliff from the 2nd century BC to about AD 480.", "Their wall paintings are masterpieces of early Indian art."],
    [["Caves", "about 30"]], { also: ["Ajanta"] }),
  P("ellora", "Ellora Caves", "Maharashtra, India", 75.179, 20.0268, 900, ["art", "architecture"],
    ["Buddhist, Hindu and Jain temples cut into the rock side by side.", "The Kailasa temple was carved from the top down out of a single block of basalt."],
    [["Caves", "34"]], { also: ["Ellora", "Kailasa Temple"], forms: [{ f: "box", w: 50, d: 30, h: 30 }, { f: "frustum", w: 20, top: 5, h: 15, z: 30 }] }),
  P("hampi", "Hampi", "Karnataka, India", 76.46, 15.335, 3000, ["architecture"],
    ["Ruins of Vijayanagara, capital of a great southern empire, among giant granite boulders.", "The Virupaksha temple is still in use."],
    [["Sacked", "1565"]], { forms: [{ f: "frustum", w: 40, top: 10, h: 50 }, { f: "box", w: 100, d: 60, h: 8, dy: -80 }] }),
  P("khajuraho", "Khajuraho", "Madhya Pradesh, India", 79.9199, 24.8518, 800, ["art", "architecture"],
    ["Hindu and Jain temples of about 950 to 1050, carved with crowded scenes of everyday life, gods and love.", "About 25 survive of some 85."],
    [["Temples surviving", "about 25"]], { forms: [{ f: "box", w: 35, d: 20, h: 4 }, { f: "frustum", w: 18, top: 4, h: 31, dx: 6, z: 4 }, { f: "frustum", w: 12, top: 3, h: 20, dx: -8, z: 4 }] }),
  P("konark", "Konark Sun Temple", "Odisha, India", 86.0945, 19.8876, 500, ["art", "architecture"],
    ["A temple of the 1200s built as the sun god's chariot, with 24 carved stone wheels and seven horses.", "Sailors called it the Black Pagoda."],
    [["Wheels", "24"]], { also: ["Konark"], forms: [{ f: "box", w: 60, d: 40, h: 8 }, { f: "frustum", w: 30, top: 12, h: 30, z: 8 }] }),
  P("amber-fort", "Amber Fort", "Jaipur, India", 75.8513, 26.9855, 800, ["architecture"],
    ["A palace-fort of pale yellow and pink sandstone above Maota Lake, one of the hill forts of Rajasthan.", "Its Hall of Mirrors glitters with inlaid glass."],
    [["Begun", "1592"]], { also: ["Amer Fort", "Jaipur"], forms: [{ f: "steps", w: 160, top: 100, h: 30, n: 3 }, { f: "box", w: 3, d: 400, h: 6, dx: 200, rot: 30 }] }),
  P("mahabodhi", "Mahabodhi Temple", "Bodh Gaya, India", 84.9912, 24.6959, 400, ["architecture"],
    ["Where the Buddha is said to have attained enlightenment under the Bodhi tree.", "The temple of brick, 55 m tall, dates in its present form from the 400s or 500s."],
    [["Height", "55 m"]], { also: ["Bodh Gaya"], forms: [{ f: "box", w: 30, d: 30, h: 8 }, { f: "frustum", w: 15, top: 5, h: 47, z: 8 }] }),
  P("csmt", "Chhatrapati Shivaji Terminus", "Mumbai, India", 72.8355, 18.9398, 500, ["architecture"],
    ["A Victorian Gothic railway station of 1888, one of the busiest in India.", "It blends Gothic and Indian styles under a great central dome."],
    [["Opened", "1888"]], { also: ["CSMT", "Victoria Terminus", "VT Mumbai"], forms: [{ f: "box", w: 120, d: 25, h: 20 }, { f: "box", w: 30, d: 60, h: 20, dx: -50, dy: -30 }, { f: "box", w: 30, d: 60, h: 20, dx: 50, dy: -30 }, { f: "cyl", r: 9, h: 15, z: 20 }, { f: "dome", r: 9, h: 15, z: 35 }] }),
  P("kaziranga", "Kaziranga", "Assam, India", 93.37, 26.67, 25000, [],
    ["Grasslands on the Brahmaputra floodplain, home of about two-thirds of the world's greater one-horned rhinos.", "Tigers, elephants and wild water buffalo live here too."],
    [["Rhinos", "about 2,600"]], { also: ["Kaziranga National Park"] }),
  P("shore-temple", "Shore Temple, Mahabalipuram", "Tamil Nadu, India", 80.1993, 12.6166, 600, ["architecture", "art"],
    ["A Pallava temple of the 700s on the sea, among rock-cut shrines and carved boulders.", "Arjuna's Penance, a relief 27 m long, is carved into the rock nearby."],
    [["Built", "700s"]], { also: ["Mahabalipuram", "Mamallapuram"], forms: [{ f: "frustum", w: 14, top: 4, h: 18 }, { f: "frustum", w: 9, top: 3, h: 12, dx: -15 }] }),
  P("brihadisvara", "Brihadisvara Temple", "Thanjavur, India", 79.1318, 10.7828, 500, ["architecture"],
    ["The great Chola temple of 1010, its tower 66 m tall, topped by a capstone said to weigh 80 tonnes.", "It is still in worship after a thousand years."],
    [["Finished", "1010"], ["Tower", "66 m"]], { also: ["Thanjavur", "Big Temple"], forms: [{ f: "box", w: 30, d: 30, h: 10 }, { f: "frustum", w: 30, top: 8, h: 50, z: 10 }, { f: "dome", r: 4.5, h: 6, z: 60 }, { f: "ring", rx: 120, ry: 70, ix: 116, iy: 66, h: 6 }] }),
  P("galle-fort", "Galle Fort", "Galle, Sri Lanka", 80.217, 6.027, 1000, ["architecture"],
    ["A walled town built by the Portuguese and rebuilt by the Dutch in the 1600s on a headland.", "Its lighthouse and ramparts face the Indian Ocean."],
    [["Rebuilt by the Dutch", "from 1663"]], { also: ["Galle"], forms: [{ f: "ring", rx: 400, ry: 300, ix: 392, iy: 292, h: 8 }, { f: "cyl", r: 3, h: 26, dx: 300, dy: -150 }] }),
  P("temple-of-the-tooth", "Temple of the Tooth", "Kandy, Sri Lanka", 80.6413, 7.2936, 500, ["architecture"],
    ["Sri Lanka's holiest Buddhist shrine, which keeps a tooth of the Buddha.", "Each year the Esala Perahera parades it through Kandy on an elephant."],
    [["Kandy, royal capital until", "1815"]], { also: ["Kandy", "Sri Dalada Maligawa"] }),
  P("lumbini", "Lumbini", "Rupandehi, Nepal", 83.276, 27.4696, 1000, [],
    ["The birthplace of the Buddha, marked by a pillar Emperor Ashoka set up in 249 BC.", "Monasteries from many Buddhist countries stand in its garden."],
    [["Ashoka's pillar", "249 BC"]], { forms: [{ f: "box", w: 30, d: 30, h: 8 }, { f: "cyl", r: 0.6, h: 6, dx: 25 }] }),
  P("prambanan", "Prambanan", "Central Java, Indonesia", 110.4914, -7.752, 600, ["architecture", "art"],
    ["The largest Hindu temple compound in Indonesia, from the 800s, its towers dedicated to Shiva, Vishnu and Brahma.", "Reliefs on its walls tell the Ramayana."],
    [["Shiva temple", "47 m"]], { forms: [{ f: "box", w: 110, d: 110, h: 2 }, { f: "frustum", w: 34, top: 4, h: 47 }, { f: "frustum", w: 20, top: 3, h: 33, dy: 35 }, { f: "frustum", w: 20, top: 3, h: 33, dy: -35 }, ...[-35, 0, 35].map((dy): Form => ({ f: "frustum", w: 14, top: 2, h: 25, dx: 40, dy }))] }),
  P("hoi-an", "Hội An", "Quảng Nam, Vietnam", 108.327, 15.877, 1000, ["architecture", "food"],
    ["A trading port of the 1400s to 1800s where Japanese, Chinese and European merchants met, kept almost intact.", "At full moon the old town is lit with lanterns."],
    [["Japanese Covered Bridge", "1590s"]], { also: ["Hoi An"], forms: [{ f: "box", w: 18, d: 5, h: 6 }] }),
  P("hue", "Huế Imperial City", "Huế, Vietnam", 107.5774, 16.4698, 2500, ["architecture"],
    ["Capital of the Nguyễn emperors from 1802 to 1945, with a walled citadel modelled on Beijing's.", "The Purple Forbidden City lay at its heart."],
    [["Capital", "1802–1945"]], { also: ["Hue", "Hue Citadel"], forms: [{ f: "ring", rx: 1100, ry: 1100, ix: 1080, iy: 1080, h: 7, rot: 45 }, { f: "ring", rx: 300, ry: 300, ix: 290, iy: 290, h: 5, rot: 45 }] }),
  P("phong-nha", "Phong Nha-Kẻ Bàng", "Quảng Bình, Vietnam", 106.2, 17.5, 20000, [],
    ["Karst mountains riddled with caves, including Sơn Đoòng, the largest cave passage known.", "Sơn Đoòng has its own jungle and clouds inside."],
    [["Sơn Đoòng", "over 5 km long"]], { also: ["Phong Nha", "Son Doong"] }),
  P("luang-prabang", "Luang Prabang", "Laos", 102.135, 19.892, 1500, ["architecture"],
    ["A royal town where the Mekong and Nam Khan meet, with Buddhist temples and French colonial houses.", "Each dawn, monks walk the streets collecting alms."],
    [["Temples", "more than 30"]], { forms: [{ f: "box", w: 30, d: 15, h: 6 }, { f: "pyramid", w: 25, h: 10, z: 6 }] }),
  P("ayutthaya", "Ayutthaya", "Thailand", 100.5577, 14.3557, 1500, ["architecture"],
    ["Capital of Siam for 400 years, one of the world's great cities until it was sacked in 1767.", "The three bell-shaped stupas of Wat Phra Si Sanphet hold the ashes of kings."],
    [["Founded", "1350"], ["Sacked", "1767"]], { forms: [-35, 0, 35].flatMap((dx): Form[] => [{ f: "box", w: 20, d: 20, h: 5, dx }, { f: "dome", r: 9, h: 10, dx, z: 5 }, { f: "cone", r: 3, h: 18, dx, z: 15 }]) }),
  P("sukhothai", "Sukhothai", "Thailand", 99.7034, 17.0174, 1500, ["architecture", "art"],
    ["The first Thai kingdom's capital, of the 1200s and 1300s, with lotus-bud stupas and serene seated Buddhas.", "Its kings are credited with the Thai alphabet."],
    [["Founded", "1238"]], { forms: [{ f: "box", w: 50, d: 50, h: 3 }, { f: "cone", r: 6, h: 25, z: 3 }] }),
  P("komodo", "Komodo National Park", "East Nusa Tenggara, Indonesia", 119.5, -8.55, 20000, [],
    ["Volcanic islands that are home to the Komodo dragon, the largest living lizard.", "Its reefs are among the richest in the world."],
    [["Komodo dragons", "about 3,000"]], { also: ["Komodo", "Komodo Island"] }),
  P("jatiluwih", "Jatiluwih Rice Terraces", "Bali, Indonesia", 115.1268, -8.37, 3000, ["food"],
    ["Rice terraces fed by the subak, a cooperative water system run from water temples since the 800s.", "Water is shared by ritual as much as by rule."],
    [["Subak system", "since the 800s"]], { also: ["Bali rice terraces", "Subak", "Jatiluwih"] }),
  P("vigan", "Vigan", "Ilocos Sur, Philippines", 120.387, 17.5747, 800, ["architecture"],
    ["The best-kept Spanish colonial town in Asia, its cobbled Calle Crisologo lined with mansions.", "Chinese, Ilocano and Spanish building styles mix here."],
    [["Founded", "1572"]]),
  P("puerto-princesa", "Puerto Princesa Underground River", "Palawan, Philippines", 118.925, 10.1925, 6000, [],
    ["A river that runs about 8 km through a limestone cave straight to the sea.", "Boats can go some 4 km in."],
    [["Underground", "about 8 km"]], { also: ["Underground River", "Puerto Princesa"] }),
  P("kinabalu", "Mount Kinabalu", "Sabah, Malaysia", 116.5583, 6.0753, 15000, [],
    ["The highest mountain in Malaysian Borneo, with one of the richest floras on Earth.", "Some 5,000 kinds of plants grow on it."],
    [["Summit", "4,095 m"]], { also: ["Kinabalu"] }),
  P("melaka", "Melaka", "Malaysia", 102.248, 2.1946, 1500, ["architecture", "food"],
    ["A trading port on the Strait of Malacca, ruled in turn by sultans, the Portuguese, the Dutch and the British.", "With George Town, it shows 500 years of trade between East and West."],
    [["Portuguese took it", "1511"]], { also: ["Malacca", "George Town", "Penang"] }),
  P("bukhara", "Bukhara", "Uzbekistan", 64.41, 39.7756, 1200, ["architecture"],
    ["A Silk Road city of mosques and madrasas over two thousand years old.", "The Kalyan Minaret of 1127 so impressed Genghis Khan that he spared it."],
    [["Kalyan Minaret", "about 46 m"]], { forms: [{ f: "cyl", r: 4.5, top: 3, h: 46 }, { f: "box", w: 130, d: 80, h: 12, dx: -80 }, { f: "box", w: 70, d: 50, h: 18, dx: 80 }, { f: "dome", r: 9, h: 10, dx: -110, z: 12 }] }),
  P("khiva", "Itchan Kala, Khiva", "Uzbekistan", 60.3626, 41.3785, 900, ["architecture"],
    ["The walled inner town of Khiva, an oasis on the Silk Road, with over 50 monuments.", "The squat, tiled Kalta Minor minaret was never finished."],
    [["Walls", "about 2.2 km"]], { also: ["Khiva", "Itchan Kala"], forms: [{ f: "ring", rx: 330, ry: 200, ix: 323, iy: 193, h: 10, rot: 90 }, { f: "cyl", r: 7, top: 5, h: 29 }] }),
  P("bamiyan", "Bamiyan Valley", "Afghanistan", 67.825, 34.832, 3000, ["art"],
    ["A valley on the Silk Road where two giant Buddhas, 55 m and 38 m, were carved into the cliff in the 500s.", "They were destroyed in 2001; the empty niches remain."],
    [["Larger Buddha", "55 m"], ["Destroyed", "2001"]], { also: ["Bamiyan Buddhas", "Bamyan"] }),
  P("mohenjo-daro", "Mohenjo-daro", "Sindh, Pakistan", 68.1386, 27.3242, 1500, ["architecture"],
    ["One of the largest cities of the Indus civilisation, laid out on a grid about 4,500 years ago.", "Its Great Bath and drains show early city planning."],
    [["Built", "about 2500 BC"]], { also: ["Mohenjo Daro"], forms: [...grid(5, 4, 60, () => [{ f: "box", w: 50, d: 50, h: 3 }]), { f: "box", w: 12, d: 7, h: 1, dy: 200 }] }),
  P("lahore-fort", "Lahore Fort", "Lahore, Pakistan", 74.3157, 31.588, 900, ["architecture", "art"],
    ["A Mughal fort rebuilt by Akbar, with the Sheesh Mahal, a palace of mirrors.", "Its picture wall is covered with tile mosaics of elephants, polo and dragons."],
    [["Rebuilt", "from 1566"]], { also: ["Shahi Qila", "Shalamar Gardens"], forms: [{ f: "ring", rx: 210, ry: 160, ix: 202, iy: 152, h: 15 }] }),
  P("kakadu", "Kakadu National Park", "Northern Territory, Australia", 132.42, -12.84, 25000, ["art"],
    ["Wetlands, gorges and escarpments, where Aboriginal people have lived for at least 65,000 years.", "Rock paintings at Ubirr and Nourlangie span thousands of years."],
    [["Area", "about 19,800 km²"]], { also: ["Kakadu"] }),
  P("three-sisters", "Three Sisters, Blue Mountains", "New South Wales, Australia", 150.312, -33.732, 4000, [],
    ["Three sandstone pillars over the Jamison Valley, in the Blue Mountains.", "The blue haze comes from oil given off by eucalyptus trees."],
    [["Height", "about 920 m above sea level"]], { also: ["Blue Mountains", "Three Sisters"] }),
  P("shark-bay", "Shark Bay", "Western Australia", 113.7, -25.9, 30000, [],
    ["Living stromatolites, the oldest form of life, grow in its salty waters.", "Its seagrass meadows feed about 10,000 dugongs."],
    [["Dugongs", "about 10,000"]]),
  P("cradle-mountain", "Cradle Mountain", "Tasmanian Wilderness", 145.95, -41.68, 8000, [],
    ["A jagged dolerite peak over Dove Lake, in one of the last great temperate wildernesses.", "The Overland Track starts here."],
    [["Summit", "1,545 m"]], { also: ["Tasmanian Wilderness"] }),
  P("kgari", "K'gari", "Queensland, Australia", 153.1, -25.25, 25000, [],
    ["The largest sand island in the world, with rainforest growing on the sand and perched freshwater lakes.", "It was long known as Fraser Island."],
    [["Length", "about 120 km"]], { also: ["Fraser Island", "K'gari (Fraser Island)"] }),
  P("royal-exhibition-building", "Royal Exhibition Building", "Melbourne, Australia", 144.9717, -37.8047, 500, ["architecture"],
    ["Built for the great exhibition of 1880, and where Australia's first parliament opened in 1901.", "One of the few great exhibition halls of that age still standing."],
    [["Built", "1880"]], { forms: [{ f: "box", w: 150, d: 50, h: 20 }, { f: "box", w: 50, d: 150, h: 20 }, { f: "cyl", r: 12, h: 15, z: 20 }, { f: "dome", r: 12, h: 18, z: 35 }] }),
  P("tongariro", "Tongariro", "North Island, New Zealand", 175.6, -39.2, 20000, [],
    ["Volcanoes sacred to Māori, given to the nation by Ngāti Tūwharetoa in 1887.", "Ngāuruhoe stood in for Mount Doom on film."],
    [["Ruapehu", "2,797 m"]], { also: ["Tongariro National Park", "Mount Ngauruhoe"] }),
  P("sundarbans", "Sundarbans", "Bangladesh and India", 89.18, 21.95, 30000, [],
    ["The largest mangrove forest in the world, in the delta of the Ganges and Brahmaputra.", "Bengal tigers here swim between the islands."],
    [["Area", "about 10,000 km²"]]),
];
