// Breeds and typical care routines for Flock. Weights are typical adult
// females (males are usually heavier); care intervals are common practice and
// vary by farm, region and vet advice, so they're offered as starting points.

export interface Breed {
  name: string;
  /** What it's kept for. */
  use: string;
  origin: string;
  /** Typical adult female weight, kg. */
  kg: number;
  note?: string;
}

export const BREEDS: Record<string, Breed[]> = {
  cattle: [
    { name: "Angus", use: "beef", origin: "Scotland", kg: 550, note: "Naturally polled; marbled beef; easy calving." },
    { name: "Hereford", use: "beef", origin: "England", kg: 550, note: "Docile, good forager; white face." },
    { name: "Charolais", use: "beef", origin: "France", kg: 750, note: "Large, fast-growing, lean; used as a terminal sire." },
    { name: "Limousin", use: "beef", origin: "France", kg: 650, note: "Heavy muscling, high carcass yield." },
    { name: "Simmental", use: "beef and dairy", origin: "Switzerland", kg: 700, note: "Big, milky mothers; fast growth." },
    { name: "Shorthorn", use: "beef and dairy", origin: "England", kg: 600 },
    { name: "Highland", use: "beef", origin: "Scotland", kg: 450, note: "Very hardy on rough grazing and in cold, wet weather." },
    { name: "Galloway", use: "beef", origin: "Scotland", kg: 500, note: "Hardy, polled, thick winter coat." },
    { name: "Dexter", use: "beef and dairy", origin: "Ireland", kg: 320, note: "Small and hardy: suits smallholdings." },
    { name: "Wagyu", use: "beef", origin: "Japan", kg: 450, note: "Intense marbling; slow finishing." },
    { name: "Brahman", use: "beef", origin: "United States (zebu)", kg: 500, note: "Heat, humidity and tick tolerant." },
    { name: "Nelore", use: "beef", origin: "Brazil (zebu)", kg: 450, note: "The main beef breed of Brazil; tropical hardiness." },
    { name: "Ankole-Watusi", use: "beef and dairy", origin: "East Africa", kg: 450, note: "Very long horns that help shed heat." },
    { name: "Holstein-Friesian", use: "dairy", origin: "Netherlands and Germany", kg: 650, note: "Highest milk volume." },
    { name: "Jersey", use: "dairy", origin: "Jersey", kg: 400, note: "Rich milk (high butterfat); efficient, heat tolerant." },
    { name: "Guernsey", use: "dairy", origin: "Guernsey", kg: 450, note: "Golden, rich milk." },
    { name: "Brown Swiss", use: "dairy", origin: "Switzerland", kg: 600, note: "Long-lived; milk good for cheese." },
    { name: "Ayrshire", use: "dairy", origin: "Scotland", kg: 500 },
    { name: "Gir", use: "dairy", origin: "India (zebu)", kg: 400, note: "Heat tolerant; parent of Brazil's Girolando." },
    { name: "Sahiwal", use: "dairy", origin: "Pakistan (zebu)", kg: 400, note: "Heat and tick tolerant dairy breed." },
  ],
  sheep: [
    { name: "Merino", use: "fine wool", origin: "Spain, Australia", kg: 60, note: "The finest wool; needs shearing and flystrike care." },
    { name: "Suffolk", use: "meat", origin: "England", kg: 90, note: "Black face; a common terminal sire." },
    { name: "Texel", use: "meat", origin: "Netherlands", kg: 80, note: "Heavily muscled, lean carcass." },
    { name: "Dorper", use: "meat (hair)", origin: "South Africa", kg: 70, note: "Sheds its coat: no shearing. Hardy in heat." },
    { name: "Katahdin", use: "meat (hair)", origin: "United States", kg: 65, note: "Hair sheep, parasite resistant, easy care." },
    { name: "Dorset", use: "meat", origin: "England", kg: 80, note: "Can lamb out of season." },
    { name: "Hampshire Down", use: "meat", origin: "England", kg: 85 },
    { name: "Romney", use: "meat and wool", origin: "England", kg: 70, note: "Copes with wet pasture; foot-rot resistant." },
    { name: "Border Leicester", use: "meat and wool", origin: "England", kg: 80 },
    { name: "Cheviot", use: "meat and wool", origin: "Scotland", kg: 60, note: "Hill breed, hardy." },
    { name: "Scottish Blackface", use: "meat and wool", origin: "Scotland", kg: 55, note: "The classic hill sheep." },
    { name: "Welsh Mountain", use: "meat and wool", origin: "Wales", kg: 45, note: "Small and very hardy." },
    { name: "Jacob", use: "wool and meat", origin: "Britain", kg: 50, note: "Spotted, often four-horned; popular with smallholders." },
    { name: "Shetland", use: "wool", origin: "Shetland", kg: 40, note: "Small, fine wool in many colours; easy for beginners." },
    { name: "Icelandic", use: "meat, wool and milk", origin: "Iceland", kg: 60 },
    { name: "East Friesian", use: "dairy", origin: "Germany", kg: 75, note: "The highest-yielding dairy sheep." },
    { name: "Lacaune", use: "dairy", origin: "France", kg: 70, note: "Milk for Roquefort cheese." },
    { name: "Awassi", use: "dairy and meat", origin: "Middle East", kg: 55, note: "Fat-tailed; tolerates heat and dry grazing." },
  ],
  goat: [
    { name: "Boer", use: "meat", origin: "South Africa", kg: 80, note: "Fast-growing, docile." },
    { name: "Kiko", use: "meat", origin: "New Zealand", kg: 55, note: "Hardy, parasite tolerant, low input." },
    { name: "Kalahari Red", use: "meat", origin: "South Africa", kg: 65, note: "Heat tolerant; red coat hides dirt." },
    { name: "Saanen", use: "dairy", origin: "Switzerland", kg: 65, note: "High milk volume; calm." },
    { name: "Alpine", use: "dairy", origin: "French Alps", kg: 60 },
    { name: "Anglo-Nubian", use: "dairy and meat", origin: "England", kg: 60, note: "Rich milk; long ears; vocal." },
    { name: "Toggenburg", use: "dairy", origin: "Switzerland", kg: 55 },
    { name: "LaMancha", use: "dairy", origin: "United States", kg: 60, note: "Tiny ears; calm, productive." },
    { name: "Nigerian Dwarf", use: "dairy (small)", origin: "West Africa, United States", kg: 30, note: "Small with very rich milk; good for small plots." },
    { name: "Pygmy", use: "pets and small meat", origin: "West Africa", kg: 25 },
    { name: "Angora", use: "mohair", origin: "Turkey", kg: 40, note: "Shorn twice a year." },
    { name: "Cashmere", use: "cashmere fibre", origin: "Central Asia", kg: 45 },
  ],
  pig: [
    { name: "Large White (Yorkshire)", use: "pork and bacon", origin: "England", kg: 250, note: "Big litters; the most common commercial breed." },
    { name: "Landrace", use: "pork and bacon", origin: "Denmark", kg: 250, note: "Long body; good mothers." },
    { name: "Duroc", use: "pork", origin: "United States", kg: 270, note: "Red; marbled meat, hardy." },
    { name: "Hampshire", use: "pork", origin: "United States (from England)", kg: 250, note: "Belted; lean." },
    { name: "Pietrain", use: "pork", origin: "Belgium", kg: 230, note: "Very lean and muscled." },
    { name: "Berkshire", use: "pork (heritage)", origin: "England", kg: 220, note: "Dark, tender meat (kurobuta)." },
    { name: "Tamworth", use: "pork (heritage)", origin: "England", kg: 230, note: "Ginger; a great forager and rooter." },
    { name: "Gloucestershire Old Spot", use: "pork (heritage)", origin: "England", kg: 250, note: "Orchard pig; docile." },
    { name: "Large Black", use: "pork (heritage)", origin: "England", kg: 250, note: "Outdoor hardy; lop ears." },
    { name: "Kunekune", use: "small pork, pets", origin: "New Zealand", kg: 100, note: "Grazes grass; gentle; suits small plots." },
    { name: "Iberian", use: "cured ham", origin: "Spain and Portugal", kg: 160, note: "Finished on acorns for jamón ibérico." },
    { name: "Mangalica", use: "lard and cured meat", origin: "Hungary", kg: 160, note: "Woolly coat." },
    { name: "Pot-bellied", use: "pets", origin: "Vietnam", kg: 60 },
  ],
  horse: [
    { name: "Thoroughbred", use: "racing, sport", origin: "England", kg: 500 },
    { name: "Arabian", use: "endurance, riding", origin: "Arabian Peninsula", kg: 430, note: "Stamina; one of the oldest breeds." },
    { name: "Quarter Horse", use: "ranch work, riding", origin: "United States", kg: 500, note: "Quick over short distances; calm." },
    { name: "Warmblood", use: "dressage, jumping", origin: "Europe", kg: 600 },
    { name: "Appaloosa", use: "riding, ranch", origin: "United States", kg: 480, note: "Spotted coat." },
    { name: "Morgan", use: "riding, driving", origin: "United States", kg: 450 },
    { name: "Friesian", use: "driving, dressage", origin: "Netherlands", kg: 600 },
    { name: "Andalusian", use: "riding, dressage", origin: "Spain", kg: 500 },
    { name: "Icelandic", use: "riding", origin: "Iceland", kg: 350, note: "Five gaits, including the tölt." },
    { name: "Shire", use: "draught", origin: "England", kg: 900, note: "One of the largest horses." },
    { name: "Clydesdale", use: "draught", origin: "Scotland", kg: 800 },
    { name: "Percheron", use: "draught", origin: "France", kg: 850 },
    { name: "Connemara", use: "riding pony", origin: "Ireland", kg: 400 },
    { name: "Welsh pony", use: "riding pony", origin: "Wales", kg: 250 },
    { name: "Shetland pony", use: "children's pony, driving", origin: "Shetland", kg: 180, note: "Prone to laminitis on rich grass: restrict grazing." },
    { name: "Donkey", use: "companion, work", origin: "Africa", kg: 200, note: "Gestation is longer (about 12 months); needs less rich food than horses." },
  ],
  alpaca: [
    { name: "Huacaya alpaca", use: "fibre", origin: "Andes", kg: 65, note: "Crimpy, fluffy fleece; shorn once a year." },
    { name: "Suri alpaca", use: "fibre", origin: "Andes", kg: 65, note: "Long, silky locks." },
    { name: "Llama", use: "packing, guarding, fibre", origin: "Andes", kg: 150, note: "Good flock guardians against foxes and dogs." },
  ],
  chicken: [
    { name: "ISA Brown (hybrid)", use: "eggs", origin: "France (hybrid)", kg: 2, note: "About 300 brown eggs a year." },
    { name: "Leghorn", use: "eggs", origin: "Italy", kg: 2, note: "About 280 white eggs a year; flighty." },
    { name: "Rhode Island Red", use: "eggs and meat", origin: "United States", kg: 2.9, note: "Hardy, about 250 brown eggs a year." },
    { name: "Plymouth Rock (Barred Rock)", use: "eggs and meat", origin: "United States", kg: 3, note: "Friendly, cold hardy." },
    { name: "Sussex", use: "eggs and meat", origin: "England", kg: 3, note: "Docile; good in gardens." },
    { name: "Australorp", use: "eggs", origin: "Australia", kg: 2.9, note: "Record layers; calm." },
    { name: "Orpington", use: "eggs and meat", origin: "England", kg: 3.6, note: "Gentle, fluffy, often broody." },
    { name: "Wyandotte", use: "eggs and meat", origin: "United States", kg: 2.7, note: "Cold hardy (rose comb)." },
    { name: "Marans", use: "eggs", origin: "France", kg: 3, note: "Very dark chocolate-brown eggs." },
    { name: "Araucana / Ameraucana", use: "eggs", origin: "Chile, United States", kg: 2.3, note: "Blue or green eggs." },
    { name: "Brahma", use: "meat and eggs", origin: "United States (from Asia)", kg: 4.5, note: "Very large and gentle; feathered feet." },
    { name: "Cochin", use: "pets, broodies", origin: "China", kg: 4, note: "Excellent mothers for hatching." },
    { name: "Silkie", use: "pets, broodies", origin: "China", kg: 1, note: "Fluffy; go broody readily." },
    { name: "Cornish Cross (broiler)", use: "meat", origin: "United States (hybrid)", kg: 3.5, note: "Ready at 6–9 weeks; grows too fast to keep long." },
  ],
  duck: [
    { name: "Pekin", use: "meat", origin: "China", kg: 3.6 },
    { name: "Khaki Campbell", use: "eggs", origin: "England", kg: 2, note: "Up to 300 eggs a year." },
    { name: "Indian Runner", use: "eggs, slug control", origin: "Indonesia", kg: 1.8, note: "Upright; they run rather than waddle." },
    { name: "Rouen", use: "meat", origin: "France", kg: 3.6 },
    { name: "Cayuga", use: "meat and eggs", origin: "United States", kg: 3.2, note: "Iridescent black-green feathers." },
    { name: "Muscovy", use: "meat", origin: "South America", kg: 3, note: "A different species: eggs take about 35 days to hatch." },
    { name: "Call duck", use: "pets, shows", origin: "Netherlands", kg: 0.6, note: "Tiny and loud." },
  ],
  dog: [
    { name: "Mixed breed", use: "companion", origin: "—", kg: 20 },
    { name: "Labrador Retriever", use: "companion, working", origin: "Canada, Britain", kg: 30 },
    { name: "Golden Retriever", use: "companion, working", origin: "Scotland", kg: 30 },
    { name: "German Shepherd", use: "working, guarding", origin: "Germany", kg: 30 },
    { name: "Border Collie", use: "herding", origin: "Scotland and England", kg: 18, note: "Needs work or a lot of exercise." },
    { name: "Australian Shepherd", use: "herding", origin: "United States", kg: 23 },
    { name: "Kelpie", use: "herding", origin: "Australia", kg: 16 },
    { name: "Great Pyrenees", use: "livestock guardian", origin: "France and Spain", kg: 45 },
    { name: "Anatolian Shepherd", use: "livestock guardian", origin: "Turkey", kg: 50 },
    { name: "Beagle", use: "companion, scent hound", origin: "England", kg: 10 },
    { name: "Dachshund", use: "companion", origin: "Germany", kg: 9, note: "Prone to back problems." },
    { name: "Poodle", use: "companion", origin: "Germany and France", kg: 20, note: "Toy and miniature sizes are smaller." },
    { name: "French Bulldog", use: "companion", origin: "France", kg: 12, note: "Short muzzle: prone to heat stress and breathing problems." },
    { name: "Bulldog", use: "companion", origin: "England", kg: 23, note: "Short muzzle: keep cool." },
    { name: "Boxer", use: "companion", origin: "Germany", kg: 28 },
    { name: "Rottweiler", use: "guarding, companion", origin: "Germany", kg: 42 },
    { name: "Staffordshire Bull Terrier", use: "companion", origin: "England", kg: 14 },
    { name: "Pit bull type", use: "companion", origin: "United States", kg: 22 },
    { name: "Jack Russell Terrier", use: "companion, ratting", origin: "England", kg: 6 },
    { name: "Yorkshire Terrier", use: "companion", origin: "England", kg: 3 },
    { name: "Chihuahua", use: "companion", origin: "Mexico", kg: 2.5 },
    { name: "Shih Tzu", use: "companion", origin: "China (Tibet)", kg: 6 },
    { name: "Cocker Spaniel", use: "companion, gundog", origin: "England", kg: 13 },
    { name: "Siberian Husky", use: "sled, companion", origin: "Siberia", kg: 20 },
    { name: "Greyhound", use: "companion (retired racers)", origin: "Britain", kg: 30, note: "Gentle; often adopted after racing." },
    { name: "Great Dane", use: "companion", origin: "Germany", kg: 55 },
  ],
  cat: [
    { name: "Domestic shorthair", use: "companion", origin: "—", kg: 4.5 },
    { name: "Domestic longhair", use: "companion", origin: "—", kg: 4.5 },
    { name: "Maine Coon", use: "companion", origin: "United States", kg: 6 },
    { name: "Siamese", use: "companion", origin: "Thailand", kg: 4 },
    { name: "Persian", use: "companion", origin: "Iran", kg: 4, note: "Daily grooming; short muzzle." },
    { name: "Ragdoll", use: "companion", origin: "United States", kg: 5.5 },
    { name: "British Shorthair", use: "companion", origin: "Britain", kg: 5 },
    { name: "Bengal", use: "companion", origin: "United States", kg: 4.5 },
    { name: "Norwegian Forest Cat", use: "companion", origin: "Norway", kg: 5 },
    { name: "Sphynx", use: "companion", origin: "Canada", kg: 3.5, note: "Hairless: needs warmth and skin care." },
  ],
  rabbit: [
    { name: "New Zealand White", use: "meat", origin: "United States", kg: 4.5 },
    { name: "Californian", use: "meat", origin: "United States", kg: 4.3 },
    { name: "Rex", use: "fur, meat, pets", origin: "France", kg: 3.6 },
    { name: "Flemish Giant", use: "pets, meat", origin: "Belgium", kg: 7 },
    { name: "Holland Lop", use: "pets", origin: "Netherlands", kg: 1.8 },
    { name: "Netherland Dwarf", use: "pets", origin: "Netherlands", kg: 1 },
    { name: "Lionhead", use: "pets", origin: "Belgium", kg: 1.5 },
    { name: "Angora", use: "wool", origin: "Turkey", kg: 3, note: "Needs regular grooming or shearing." },
  ],
};

export const breedsFor = (species: string): Breed[] => BREEDS[species] ?? [];
export const findBreed = (species: string, name?: string): Breed | undefined =>
  name ? breedsFor(species).find((b) => b.name.toLowerCase() === name.trim().toLowerCase()) : undefined;

/** Common routine care, as one-tap entries: what, and when it's next due (days). */
export interface CareItem { kind: "vaccination" | "treatment" | "checkup"; text: string; every: number }

export const CARE: Record<string, CareItem[]> = {
  cattle: [
    { kind: "vaccination", text: "Clostridial booster", every: 365 },
    { kind: "vaccination", text: "BVD / IBR booster", every: 365 },
    { kind: "treatment", text: "Worming (check faecal egg count)", every: 90 },
    { kind: "checkup", text: "Hoof trim", every: 182 },
    { kind: "checkup", text: "Body condition score", every: 60 },
  ],
  sheep: [
    { kind: "vaccination", text: "Clostridial and pasteurella booster", every: 365 },
    { kind: "treatment", text: "Worming (check faecal egg count)", every: 42 },
    { kind: "checkup", text: "Feet check and trim", every: 90 },
    { kind: "treatment", text: "Shearing", every: 365 },
    { kind: "treatment", text: "Crutching and flystrike check", every: 60 },
  ],
  goat: [
    { kind: "vaccination", text: "CDT booster", every: 365 },
    { kind: "treatment", text: "Worming (check faecal egg count)", every: 42 },
    { kind: "checkup", text: "Hoof trim", every: 56 },
    { kind: "checkup", text: "FAMACHA eye check", every: 21 },
  ],
  pig: [
    { kind: "vaccination", text: "Erysipelas and parvovirus booster", every: 182 },
    { kind: "treatment", text: "Worming", every: 90 },
    { kind: "checkup", text: "Body condition and feet check", every: 30 },
  ],
  horse: [
    { kind: "vaccination", text: "Tetanus and flu booster", every: 365 },
    { kind: "treatment", text: "Worming (check faecal egg count)", every: 90 },
    { kind: "checkup", text: "Farrier: trim or reshoe", every: 42 },
    { kind: "checkup", text: "Dental check", every: 365 },
  ],
  alpaca: [
    { kind: "vaccination", text: "CDT booster", every: 365 },
    { kind: "treatment", text: "Shearing", every: 365 },
    { kind: "checkup", text: "Toenail trim", every: 60 },
    { kind: "treatment", text: "Worming (check faecal egg count)", every: 90 },
  ],
  chicken: [
    { kind: "checkup", text: "Red mite and lice check", every: 14 },
    { kind: "treatment", text: "Worming", every: 182 },
    { kind: "checkup", text: "Deep-clean the coop", every: 30 },
  ],
  duck: [
    { kind: "treatment", text: "Worming", every: 182 },
    { kind: "checkup", text: "Clean pond and bedding", every: 7 },
  ],
  dog: [
    { kind: "vaccination", text: "Annual vaccination (DHPP / leptospirosis)", every: 365 },
    { kind: "vaccination", text: "Rabies (where required)", every: 365 },
    { kind: "treatment", text: "Worming", every: 90 },
    { kind: "treatment", text: "Flea and tick treatment", every: 30 },
  ],
  cat: [
    { kind: "vaccination", text: "Annual vaccination (FVRCP)", every: 365 },
    { kind: "treatment", text: "Worming", every: 90 },
    { kind: "treatment", text: "Flea treatment", every: 30 },
  ],
  rabbit: [
    { kind: "vaccination", text: "Myxomatosis and RHD2 vaccination", every: 365 },
    { kind: "checkup", text: "Nails and teeth check", every: 42 },
    { kind: "checkup", text: "Flystrike check (warm weather)", every: 7 },
  ],
};
