// The rest of the Earth's great shapes, in the same form as features.ts: ice sheets and glaciers, islands,
// reefs, caves, mountain ranges, plateaus, wetlands and deltas, and the rifts and faults where the plates
// meet. Figures are the commonly cited ones, rounded ("about"), because sources differ and ice, deltas and
// swamps change size with the seasons and the decades. Points mark the feature (for ranges and plateaus,
// roughly the middle; for ice sheets and plateaus, somewhere well inside).
import type { Feature } from "./features";

const f = (kind: Feature["kind"], name: string, lat: number, lon: number, facts: [string, string][], blurb: string, aka?: string[]): Feature => ({ kind, name, lat, lon, facts, blurb, aka });
const opt = (k: string, v: string | null): [string, string][] => (v ? [[k, v]] : []);

const glacier = (name: string, lat: number, lon: number, size: string, type: string, blurb: string, aka?: string[]) => f("glacier", name, lat, lon, [["Size", size], ["Type", type]], blurb, aka);
const island = (name: string, lat: number, lon: number, area: string, where: string, blurb: string, aka?: string[]) => f("island", name, lat, lon, [["Area", area], ["Country", where]], blurb, aka);
const reef = (name: string, lat: number, lon: number, extent: string, sea: string, blurb: string, aka?: string[]) => f("reef", name, lat, lon, [["Extent", extent], ["Sea", sea]], blurb, aka);
const cave = (name: string, lat: number, lon: number, known: string, type: string, blurb: string, aka?: string[]) => f("cave", name, lat, lon, [["Known for", known], ["Type", type]], blurb, aka);
const range = (name: string, lat: number, lon: number, top: string, length: string | null, blurb: string, aka?: string[]) => f("range", name, lat, lon, [["Highest point", top], ...opt("Length", length)], blurb, aka);
const plateau = (name: string, lat: number, lon: number, height: string, known: string, blurb: string, aka?: string[]) => f("plateau", name, lat, lon, [["Height", height], ["Known for", known]], blurb, aka);
const wetland = (name: string, lat: number, lon: number, area: string, type: string, blurb: string, aka?: string[]) => f("wetland", name, lat, lon, [["Area", area], ["Type", type]], blurb, aka);
const rift = (name: string, lat: number, lon: number, type: string, moving: string, blurb: string, aka?: string[]) => f("rift", name, lat, lon, [["Kind", type], ["Moving", moving]], blurb, aka);

export const LANDFORMS: Feature[] = [
  // ---- Ice ---------------------------------------------------------------------------------------------
  glacier("Antarctic Ice Sheet", -82, 50, "about 14 million km²", "Ice sheet",
    "The largest single mass of ice on Earth, up to about 4.8 km thick and holding most of the world's fresh water. Melted, it would raise the seas by about 58 m."),
  glacier("Greenland Ice Sheet", 72, -40, "about 1.7 million km²", "Ice sheet",
    "Up to about 3 km thick, so heavy it has pressed the bedrock below sea level. Melted, it would raise the seas by about 7 m; it is losing ice every year."),
  glacier("Lambert Glacier", -72.5, 68.5, "about 400 km long, up to 100 km wide", "Outlet glacier",
    "The largest glacier in the world, draining a large share of East Antarctica's ice into the Amery Ice Shelf."),
  glacier("Thwaites Glacier", -75.5, -106.75, "about 120 km wide", "Outlet glacier",
    "Nicknamed the Doomsday Glacier: warm ocean water is eating it from below, and its loss could unlock much of the West Antarctic Ice Sheet."),
  glacier("Pine Island Glacier", -75.2, -100, "about 250 km long", "Outlet glacier", "The fastest-thinning glacier in Antarctica, side by side with Thwaites in the Amundsen Sea."),
  glacier("Beardmore Glacier", -84, 170, "about 200 km long", "Valley glacier",
    "One of the largest valley glaciers on Earth: the road through the Transantarctic Mountains that Shackleton and Scott took toward the South Pole."),
  glacier("Siachen Glacier", 35.42, 77.1, "about 76 km long", "Valley glacier",
    "The longest glacier in the Karakoram, and the highest battlefield on Earth: Indian and Pakistani troops have faced each other here since 1984."),
  glacier("Baltoro Glacier", 35.73, 76.4, "about 63 km long", "Valley glacier",
    "The highway into the heart of the Karakoram: at Concordia it meets the Godwin-Austen Glacier, with K2 and three more 8,000 m peaks in view."),
  glacier("Fedchenko Glacier", 38.83, 72.25, "about 77 km long", "Valley glacier", "The longest glacier outside the polar regions, in Tajikistan's Pamirs."),
  glacier("Khumbu Glacier", 27.96, 86.83, "about 17 km long", "Valley glacier",
    "Everest Base Camp sits on it; above, the Khumbu Icefall is the most dangerous stretch of the climb from Nepal."),
  glacier("Aletsch Glacier", 46.45, 8.05, "about 20 km long", "Valley glacier", "The largest glacier in the Alps, about 900 m thick at Konkordiaplatz, where three ice streams meet.", ["Great Aletsch Glacier"]),
  glacier("Mer de Glace", 45.9, 6.93, "about 7 km long", "Valley glacier", "France's longest glacier, on Mont Blanc's north side; the station at Montenvers looks down on how far it has shrunk."),
  glacier("Perito Moreno Glacier", -50.48, -73.05, "about 30 km long", "Outlet glacier",
    "Its 5 km-wide front stands 60–70 m above Lake Argentino and calves with a roar; unlike most glaciers, it has held its ground for a century."),
  glacier("Vatnajökull", 64.4, -16.8, "about 7,700 km²", "Ice cap", "Europe's largest ice cap by volume, lying over active volcanoes (Grímsvötn, Bárðarbunga) whose eruptions melt floods out from under it."),
  glacier("Sermeq Kujalleq", 69.17, -49.83, "drains about 6% of Greenland's ice", "Outlet glacier",
    "Among the fastest glaciers on Earth, at times moving tens of metres a day, and the source of many of the North Atlantic's icebergs. Its icefjord is a World Heritage site.", ["Jakobshavn Glacier", "Jakobshavn Isbræ"]),
  glacier("Hubbard Glacier", 60.3, -139.4, "about 120 km long", "Tidewater glacier", "North America's largest tidewater glacier, advancing while most retreat; twice it has dammed Russell Fjord shut."),
  glacier("Malaspina Glacier", 59.9, -140.5, "about 3,900 km²", "Piedmont glacier", "The largest piedmont glacier on Earth: ice spilling out of the St. Elias Mountains onto the coastal plain like batter from a bowl."),
  glacier("Columbia Icefield", 52.17, -117.25, "about 325 km²", "Ice field",
    "A hydrological apex: its meltwater runs to three oceans, the Pacific, the Atlantic (by way of Hudson Bay) and the Arctic."),
  glacier("Franz Josef Glacier", -43.47, 170.18, "about 11 km long", "Valley glacier", "It falls from the Southern Alps nearly to sea level, ending among temperate rainforest.", ["Kā Roimata o Hine Hukatere"]),

  // ---- Islands -----------------------------------------------------------------------------------------
  island("Greenland", 71.7, -42.6, "about 2,130,000 km²", "Denmark (self-governing)", "The largest island on Earth, about four-fifths under ice; about 57,000 people live along its coasts."),
  island("New Guinea", -5.5, 141, "about 786,000 km²", "Indonesia, Papua New Guinea",
    "The second-largest island, with glaciers just south of the equator (on Puncak Jaya) and around a thousand languages, more than anywhere else on Earth."),
  island("Borneo", 0.9, 114.2, "about 743,000 km²", "Indonesia, Malaysia, Brunei", "The only island shared by three countries, home to orangutans and some of the oldest rainforest on Earth."),
  island("Madagascar", -19, 46.7, "about 587,000 km²", "Madagascar",
    "Cut off from Africa and India for tens of millions of years, so most of its plants and animals, every lemur among them, live nowhere else."),
  island("Baffin Island", 69, -72, "about 507,000 km²", "Canada", "The fifth-largest island and the largest in Canada, with the sheer granite walls of Auyuittuq and Sam Ford Fjord."),
  island("Sumatra", -0.6, 101.3, "about 473,000 km²", "Indonesia", "Along the Sunda megathrust; home to the last Sumatran tigers, rhinos and orangutans, and to the supervolcano Toba."),
  island("Honshu", 36, 138, "about 228,000 km²", "Japan", "Japan's main island: Tokyo, Osaka, Kyoto and Mount Fuji, and about 100 million people."),
  island("Victoria Island", 71, -110, "about 217,000 km²", "Canada", "The eighth-largest island, in the Canadian Arctic; it has a lake on an island in a lake on the island."),
  island("Great Britain", 53.8, -2.4, "about 209,000 km²", "United Kingdom", "The largest island in Europe and the ninth-largest on Earth; it was joined to the continent until about 8,000 years ago."),
  island("Ellesmere Island", 79.8, -79, "about 196,000 km²", "Canada", "The northernmost large island, with fossil forests from a warmer age and Arctic hares that run on two legs."),
  island("Sulawesi", -2, 121, "about 181,000 km²", "Indonesia", "Four long arms from three old landmasses, east of the Wallace Line, so its animals (babirusa, anoa, tarsiers) are its own."),
  island("Java", -7.5, 110, "about 128,000 km²", "Indonesia", "The most populous island on Earth, with about 150 million people, Jakarta, and a spine of active volcanoes."),
  island("South Island", -43.5, 171, "about 150,000 km²", "New Zealand", "Cut along its length by the Alpine Fault, with the Southern Alps, fiords and glaciers on one side of it.", ["Te Waipounamu"]),
  island("North Island", -38.5, 176, "about 114,000 km²", "New Zealand", "Volcanic in its heart: Taupō's caldera, Ruapehu, and geysers and hot springs at Rotorua.", ["Te Ika-a-Māui"]),
  island("Newfoundland", 48.6, -56, "about 109,000 km²", "Canada", "Where the Vikings landed around 1000 at L'Anse aux Meadows, and where icebergs drift past in spring."),
  island("Cuba", 21.6, -79, "about 105,000 km²", "Cuba", "The largest island in the Caribbean, about 1,250 km long."),
  island("Iceland", 64.9, -18.6, "about 102,000 km²", "Iceland", "Built where the Mid-Atlantic Ridge meets a hot spot, so it grows: the island is being pulled apart about 2 cm a year."),
  island("Ireland", 53.4, -8, "about 84,000 km²", "Ireland, United Kingdom", "Kept green by Atlantic rain; with no snakes since the Ice Age, legend gives the credit to St Patrick."),
  island("Sri Lanka", 7.9, 80.8, "about 65,600 km²", "Sri Lanka", "Tea in the hills, leopards in Yala and rainforest at Sinharaja, a short reach from India across the Palk Strait."),
  island("Tasmania", -42, 146.6, "about 68,000 km²", "Australia", "Some of the cleanest air on Earth, measured at Cape Grim, and the last home of the Tasmanian devil."),
  island("Spitsbergen", 78.8, 16.5, "about 37,700 km²", "Norway", "The largest island of Svalbard, with more polar bears than people, and a seed vault cut into its permafrost."),
  island("Hawaiʻi", 19.6, -155.5, "about 10,400 km²", "United States",
    "The Big Island, still growing: Mauna Kea, measured from its base on the sea floor, is taller than Everest.", ["Big Island", "Hawaii Island"]),
  island("Socotra", 12.47, 53.87, "about 3,800 km²", "Yemen", "Dragon's blood trees and plants found nowhere else: about a third of its plants are its own."),
  island("Surtsey", 63.3, -20.6, "about 1.3 km²", "Iceland", "Born from the sea in an eruption that began in 1963; scientists have watched life arrive on it ever since, and it's off limits to everyone else."),

  // ---- Reefs -------------------------------------------------------------------------------------------
  reef("Great Barrier Reef", -18.3, 147.7, "about 2,300 km", "Coral Sea",
    "The largest structure built by living things: about 2,900 reefs and 900 islands, visible from orbit. Repeated marine heatwaves have bleached much of it since 2016."),
  reef("Mesoamerican Barrier Reef", 17.3, -87.5, "about 1,000 km", "Caribbean Sea", "The largest reef system in the Western Hemisphere, from Mexico's Yucatán to Honduras, with Belize's Great Blue Hole in its lagoon.", ["Belize Barrier Reef"]),
  reef("New Caledonia Barrier Reef", -21.5, 165.5, "about 1,500 km", "Coral Sea", "One of the longest barrier reefs, ringing one of the largest lagoons on Earth."),
  reef("Raja Ampat", -0.5, 130.5, "about 1,500 islands", "Coral Triangle",
    "The richest reefs on Earth: about three-quarters of the world's known coral species live in the Coral Triangle, and Raja Ampat is its heart."),
  reef("Ningaloo Reef", -22.6, 113.7, "about 260 km", "Indian Ocean", "A fringing reef you can swim to from the beach, where whale sharks gather each autumn."),
  reef("Red Sea coral reefs", 27, 34.5, "about 2,000 km of coast", "Red Sea", "Corals unusually tolerant of heat, which may make the northern Red Sea a refuge as the oceans warm."),
  reef("Florida Reef", 24.7, -80.9, "about 580 km", "Atlantic, Gulf of Mexico", "The only living coral barrier reef in the continental United States, along the Florida Keys.", ["Florida Reef Tract"]),

  // ---- Caves -------------------------------------------------------------------------------------------
  cave("Hang Sơn Đoòng", 17.46, 106.29, "The largest cave passage known", "Limestone",
    "A passage over 5 km long and up to about 200 m high, with its own jungle and its own clouds. Explored only in 2009.", ["Son Doong", "Son Doong Cave"]),
  cave("Mammoth Cave", 37.19, -86.1, "The longest cave system known, over 680 km mapped", "Limestone", "Passages under a sandstone cap in Kentucky; every few years cavers connect more of them."),
  cave("Veryovkina Cave", 43.42, 40.36, "The deepest cave known, about 2,200 m", "Limestone", "In the Arabika Massif in Abkhazia, beside Krubera, the previous record holder."),
  cave("Krubera Cave", 43.41, 40.36, "About 2,200 m deep", "Limestone", "The first cave known to go deeper than 2 km, reached in 2004.", ["Voronya Cave"]),
  cave("Sistema Sac Actun", 20.24, -87.47, "The longest underwater cave known, over 370 km", "Flooded limestone", "Under the Yucatán's forest, reached through cenotes; it holds Maya remains and the bones of Ice Age animals."),
  cave("Sarawak Chamber", 4.05, 114.88, "The largest cave chamber by area", "Limestone", "Inside Gunung Mulu: a single room that could hold about 40 Boeing 747s."),
  cave("Cave of the Crystals", 27.85, -105.5, "Selenite crystals up to about 12 m long", "Mine-exposed crystal cave", "About 300 m below Naica, Mexico, at about 58 °C: too hot to stay in for long without a cooling suit.", ["Naica crystal cave", "Cueva de los Cristales"]),
  cave("Eisriesenwelt", 47.5, 13.19, "The largest ice cave known, about 42 km long", "Limestone with ice", "Its first kilometre is ice all year, frozen by winter air that sinks in and stays."),
  cave("Carlsbad Caverns", 32.15, -104.56, "The Big Room", "Limestone dissolved by acid", "Carved by sulfuric acid rising from oil deposits; on summer evenings hundreds of thousands of bats pour out."),
  cave("Waitomo Glowworm Caves", -38.26, 175.1, "Thousands of glowworms", "Limestone", "A ceiling lit by fungus-gnat larvae (Arachnocampa luminosa) that glow to catch insects; you see it from a boat in silence."),
  cave("Fingal's Cave", 56.43, -6.34, "Columns of basalt", "Sea cave in basalt", "Six-sided columns from a lava flow that cooled 60 million years ago; it inspired Mendelssohn's Hebrides overture."),

  // ---- Mountain ranges ---------------------------------------------------------------------------------
  range("Himalayas", 28.6, 84, "Mount Everest, 8,849 m", "about 2,400 km", "Still rising as India pushes into Asia at a few centimetres a year. Ten of the fourteen 8,000 m peaks are here.", ["Himalaya", "The Himalayas"]),
  range("Karakoram", 35.9, 76.5, "K2, 8,611 m", "about 500 km", "More glacier ice than anywhere outside the poles, and four of the 8,000 m peaks."),
  range("Hindu Kush", 36, 70.5, "Tirich Mir, 7,708 m", "about 800 km", "The western reach of the great Asian ranges, between Afghanistan and Pakistan."),
  range("Pamir Mountains", 38.5, 73, "Kongur Tagh, 7,649 m", null, "The knot where the Himalaya, Karakoram, Hindu Kush, Kunlun and Tian Shan meet; long called the Roof of the World.", ["Pamirs"]),
  range("Tian Shan", 42, 80, "Jengish Chokusu, 7,439 m", "about 2,500 km", "The Celestial Mountains, across Central Asia; the Silk Road ran along their feet."),
  range("Kunlun Mountains", 36, 84, "Liushi Shan, 7,167 m", "about 3,000 km", "One of the longest ranges in Asia, the northern wall of the Tibetan Plateau."),
  range("Altai Mountains", 49.5, 88, "Belukha, 4,506 m", "about 2,000 km", "Where Russia, China, Mongolia and Kazakhstan meet; snow leopards, and the frozen Pazyryk tombs."),
  range("Ural Mountains", 60, 59.5, "Mount Narodnaya, 1,895 m", "about 2,500 km", "Old and worn down; the traditional line between Europe and Asia, rich in iron, copper and gems.", ["Urals"]),
  range("Caucasus Mountains", 42.8, 44, "Mount Elbrus, 5,642 m", "about 1,200 km", "Between the Black and Caspian seas; Elbrus is the highest mountain in Europe.", ["Caucasus"]),
  range("Zagros Mountains", 32.5, 50, "Mount Dena, about 4,400 m", "about 1,600 km", "Folded rock where Arabia meets Iran, and home to some of the oldest farming in the world."),
  range("Alps", 46.3, 9, "Mont Blanc, 4,806 m", "about 1,200 km", "Raised as Africa pushed into Europe; the birthplace of mountaineering."),
  range("Pyrenees", 42.65, 0.5, "Aneto, 3,404 m", "about 430 km", "The wall between France and Spain, with tiny Andorra in the middle."),
  range("Carpathian Mountains", 47.5, 25, "Gerlachovský štít, 2,655 m", "about 1,500 km", "Europe's largest stretch of old-growth forest, with its biggest populations of bears, wolves and lynx.", ["Carpathians"]),
  range("Scandinavian Mountains", 64, 13, "Galdhøpiggen, 2,469 m", "about 1,700 km", "Cut by the ice ages into Norway's fjords.", ["Scandes"]),
  range("Atlas Mountains", 31.5, -6, "Toubkal, 4,167 m", "about 2,500 km", "They split the Mediterranean coast from the Sahara, across Morocco, Algeria and Tunisia."),
  range("Drakensberg", -29, 29.3, "Thabana Ntlenyana, 3,482 m", "about 1,000 km", "The basalt escarpment of southern Africa, with thousands of San rock paintings in its shelters.", ["uKhahlamba"]),
  range("Rocky Mountains", 45, -112, "Mount Elbert, 4,401 m", "about 4,800 km", "From British Columbia to New Mexico; the Continental Divide runs along them.", ["Rockies"]),
  range("Sierra Nevada", 37.5, -119, "Mount Whitney, 4,421 m", "about 650 km", "A single tilted block of granite: Yosemite, Lake Tahoe and the giant sequoias."),
  range("Alaska Range", 63, -151, "Denali, 6,190 m", "about 650 km", "Denali rises about 5,500 m from its base, more than Everest does from its own."),
  range("Appalachian Mountains", 37.5, -80, "Mount Mitchell, 2,037 m", "about 2,400 km", "Once as high as the Alps, worn down over 400 million years; the Appalachian Trail runs their length.", ["Appalachians"]),
  range("Andes", -20, -68, "Aconcagua, 6,961 m", "about 7,000 km", "The longest mountain range on land, along all of South America's west coast."),
  range("Great Dividing Range", -25, 148, "Mount Kosciuszko, 2,228 m", "about 3,500 km", "Australia's spine, splitting the wet east coast from the dry interior."),
  range("Southern Alps", -43.5, 170.5, "Aoraki / Mount Cook, 3,724 m", "about 500 km", "Pushed up along the Alpine Fault about a centimetre a year, nearly as fast as erosion wears them down.", ["Kā Tiritiri o te Moana"]),
  range("Transantarctic Mountains", -84, 170, "Mount Kirkpatrick, 4,528 m", "about 3,500 km", "They split East from West Antarctica; dinosaur fossils have been found near their summits."),
  range("Western Ghats", 13, 75, "Anamudi, 2,695 m", "about 1,600 km", "They catch the monsoon and keep one of the world's richest forests; older than the Himalayas.", ["Sahyadri"]),
  range("Brooks Range", 68, -152, "Mount Isto, 2,736 m", "about 1,100 km", "The northernmost range in North America, inside the Arctic Circle."),

  // ---- Plateaus ----------------------------------------------------------------------------------------
  plateau("Tibetan Plateau", 33, 88, "over 4,500 m on average", "The Roof of the World",
    "The highest and largest plateau on Earth; its ice feeds the Yangtze, Yellow, Mekong, Indus and Brahmaputra.", ["Qinghai–Tibet Plateau"]),
  plateau("Altiplano", -17.5, -67.5, "about 3,750 m on average", "Lake Titicaca and the Uyuni salt flat", "The largest high plateau on Earth outside Tibet, shared by Peru, Bolivia, Chile and Argentina."),
  plateau("Colorado Plateau", 37, -110, "about 1,500–2,000 m", "Grand Canyon, Arches, Monument Valley", "Lifted slowly and in one piece, so rivers cut down through it and laid two billion years of rock bare."),
  plateau("Deccan Plateau", 17, 77, "about 600 m on average", "The Deccan Traps", "Partly built of flood basalt from eruptions around the time the dinosaurs died out."),
  plateau("Ethiopian Highlands", 9.5, 38.5, "mostly over 1,500 m", "The source of the Blue Nile", "The Roof of Africa: the largest area above 1,500 m on the continent, with Ras Dashen at 4,550 m."),
  plateau("Iranian Plateau", 32.5, 55, "about 1,000–1,500 m", "Its salt deserts, the Dasht-e Kavir and Dasht-e Lut", "A high basin ringed by the Zagros, Alborz and the mountains of the east."),
  plateau("Anatolian Plateau", 39, 33.5, "about 1,000 m", "Cappadocia's fairy chimneys", "Central Turkey's high steppe, where the world's first cities rose, Çatalhöyük among them."),
  plateau("Mongolian Plateau", 46.5, 105, "about 1,500 m", "The Gobi and the steppe", "High, dry grassland with some of the coldest winters and widest skies on Earth."),
  plateau("Antarctic Plateau", -84, 90, "about 3,000 m", "The coldest place on Earth", "Vostok Station measured −89.2 °C in 1983; satellites have since found hollows near −94 °C.", ["Polar Plateau"]),
  plateau("Loess Plateau", 37, 108, "about 1,000–2,000 m", "Wind-blown silt", "Silt laid tens to hundreds of metres deep by the wind; it washes into the Yellow River and gives it its colour."),
  plateau("Mount Roraima", 5.14, -60.76, "2,810 m", "Its sheer walls, about 400 m high", "The highest of the tepuis, table mountains of ancient sandstone; it inspired Conan Doyle's The Lost World.", ["Roraima"]),
  plateau("Columbia Plateau", 46.5, -119, "about 600 m", "Flood basalts and the Channeled Scablands", "Lava floods 17 to 6 million years ago, then Ice Age megafloods from Lake Missoula that tore channels across it."),

  // ---- Wetlands and deltas -----------------------------------------------------------------------------
  wetland("Pantanal", -17.5, -57, "about 150,000–195,000 km²", "Tropical floodplain", "The largest tropical wetland on Earth, and the best place to see jaguars in the wild."),
  wetland("Sudd", 7.5, 30.5, "up to tens of thousands of km²", "Swamp of the White Nile", "The White Nile spreads into a maze of papyrus and loses about half its water to the sun.", ["The Sudd"]),
  wetland("Okavango Delta", -19.3, 22.9, "about 6,000–15,000 km²", "Inland delta", "A river that never reaches the sea: it fans out into the Kalahari and is drunk by the sand and the sun, drawing elephants and lions."),
  wetland("Everglades", 25.8, -80.9, "about 6,100 km² (the national park)", "Subtropical wetland", "A slow river of grass, a few centimetres deep and about 100 km wide, flowing south to Florida Bay."),
  wetland("Vasyugan Swamp", 57, 79, "about 53,000 km²", "Peat bog", "One of the largest bogs on Earth, in western Siberia, and still growing; it locks away a great store of carbon."),
  wetland("Ganges–Brahmaputra Delta", 22.5, 89.5, "about 105,000 km²", "River delta", "The largest delta on Earth, home to well over 100 million people and to the Sundarbans' mangroves.", ["Bengal Delta"]),
  wetland("Mekong Delta", 10, 105.8, "about 40,000 km²", "River delta", "Vietnam's rice bowl, threaded with nine mouths of the Mekong, and sinking faster than the sea is rising."),
  wetland("Danube Delta", 45.1, 29.3, "about 4,100 km²", "River delta", "Europe's best-kept delta, with more than 300 species of birds and one of the largest reed beds on Earth."),
  wetland("Inner Niger Delta", 14.5, -4.5, "about 40,000 km² in flood", "Inland delta", "The Niger floods across the Sahel each year, an oasis for fishermen, herders and millions of migrating birds."),
  wetland("Camargue", 43.55, 4.5, "about 930 km²", "River delta", "Where the Rhône meets the Mediterranean: flamingos, white horses and salt pans."),
  wetland("Llanos", 6.5, -69, "about 500,000 km²", "Seasonally flooded savanna", "The plains of the Orinoco: dry half the year, a sea of shallow water the other half, with capybaras, caimans and scarlet ibis.", ["Los Llanos"]),

  // ---- Where the plates meet ---------------------------------------------------------------------------
  rift("East African Rift", 0, 36, "Continental rift", "a few millimetres a year apart",
    "Africa slowly splitting in two along a string of valleys, lakes and volcanoes; in millions of years the sea may flood in.", ["Great Rift Valley"]),
  rift("Afar Triangle", 12, 41.5, "Triple junction", "a centimetre or two a year",
    "Where three rifts meet: the Danakil Depression, about 125 m below sea level, has a lava lake, acid pools and some of the hottest year-round temperatures on Earth.", ["Afar Depression", "Danakil Depression"]),
  rift("Mid-Atlantic Ridge", 30, -42, "Spreading ridge", "about 2.5 cm a year apart",
    "A mountain range about 16,000 km long under the Atlantic, where new ocean floor is made; the Atlantic widens about as fast as fingernails grow."),
  rift("Þingvellir", 64.26, -21.13, "Spreading ridge on land", "about 2 cm a year apart",
    "One of the few places you can stand between two plates: North America on one side of the valley, Eurasia on the other. Divers swim the gap in Silfra.", ["Thingvellir", "Silfra"]),
  rift("San Andreas Fault", 35.2, -119.9, "Transform fault", "about 3–4 cm a year",
    "The Pacific Plate grinding north past North America for about 1,200 km; it caused the 1906 San Francisco earthquake."),
  rift("North Anatolian Fault", 40.7, 31, "Transform fault", "about 2 cm a year", "Turkey being squeezed west; its great quakes have marched westward toward Istanbul through the last century."),
  rift("Dead Sea Transform", 31, 35.45, "Transform fault", "a few millimetres a year", "Arabia sliding past Africa; it opened the Dead Sea basin, the lowest land on Earth at about 430 m below sea level."),
  rift("Baikal Rift Zone", 53, 107, "Continental rift", "a few millimetres a year apart", "The rift that made Lake Baikal, the deepest lake on Earth, and it is still widening."),
  rift("Alpine Fault", -43.4, 170.4, "Transform fault", "about 3 cm a year",
    "It runs the length of New Zealand's South Island; it has broken in a great quake about every 300 years, and last did so in 1717."),
  rift("East Pacific Rise", -20, -112, "Spreading ridge", "up to about 15 cm a year apart", "The fastest-spreading ridge on Earth, where hydrothermal vents and their black smokers were first seen in 1979."),
  rift("Main Himalayan Thrust", 27.8, 85.5, "Collision zone", "India and Asia closing about 4–5 cm a year", "India pushing under Asia: it raises the Himalayas and caused the 2015 Nepal earthquake."),
];
