// The planet's great wildlife places and migrations, for the Animals theme.
// Coordinates mark the heart of each place; migration routes are simplified
// sketches of the usual path, not tracks.

export interface WildPlace { name: string; lon: number; lat: number; emoji: string; what: string }
export interface Migration { name: string; emoji: string; color: string; about: string; pts: [number, number][] }

export const WILD_PLACES: WildPlace[] = [
  { name: "Serengeti", lon: 34.83, lat: -2.33, emoji: "🦓", what: "Over a million wildebeest, zebra and gazelle, and the lions that follow them" },
  { name: "Maasai Mara", lon: 35.14, lat: -1.49, emoji: "🦁", what: "Big cats and the Mara River crossings" },
  { name: "Okavango Delta", lon: 22.9, lat: -19.3, emoji: "🐘", what: "An inland delta in the Kalahari: elephants, hippos, wild dogs" },
  { name: "Kruger", lon: 31.5, lat: -24.0, emoji: "🦏", what: "The Big Five, and one of Africa's last rhino strongholds" },
  { name: "Etosha", lon: 16.0, lat: -18.85, emoji: "🦒", what: "A salt pan where animals gather at the waterholes" },
  { name: "Virunga", lon: 29.5, lat: -1.4, emoji: "🦍", what: "Mountain gorillas on the volcano slopes" },
  { name: "Madagascar rainforests", lon: 48.4, lat: -18.9, emoji: "🐒", what: "Lemurs and chameleons found nowhere else" },
  { name: "Galápagos", lon: -90.5, lat: -0.7, emoji: "🐢", what: "Giant tortoises, marine iguanas and Darwin's finches" },
  { name: "Amazon", lon: -62.0, lat: -3.5, emoji: "🦜", what: "One in ten known species lives in the Amazon basin" },
  { name: "Pantanal", lon: -57.0, lat: -17.5, emoji: "🐆", what: "The world's largest tropical wetland; the best place to see jaguars" },
  { name: "Patagonia (Península Valdés)", lon: -64.0, lat: -42.5, emoji: "🐋", what: "Southern right whales, elephant seals and orcas beaching for pups" },
  { name: "Yellowstone", lon: -110.5, lat: 44.6, emoji: "🐺", what: "Wolves, bison and grizzly bears" },
  { name: "Churchill", lon: -94.17, lat: 58.77, emoji: "🐻‍❄️", what: "Polar bears wait here for Hudson Bay to freeze" },
  { name: "Katmai", lon: -155.0, lat: 58.6, emoji: "🐻", what: "Brown bears catching salmon at Brooks Falls" },
  { name: "Monterey Bay", lon: -122.0, lat: 36.8, emoji: "🦦", what: "Sea otters in the kelp forests; whales offshore" },
  { name: "Everglades", lon: -80.9, lat: 25.3, emoji: "🐊", what: "Alligators and crocodiles side by side" },
  { name: "Costa Rica cloud forests", lon: -84.8, lat: 10.3, emoji: "🐸", what: "Quetzals, sloths and tree frogs" },
  { name: "Great Barrier Reef", lon: 146.8, lat: -18.3, emoji: "🐠", what: "The largest coral reef system: 1,500 kinds of fish" },
  { name: "Raja Ampat", lon: 130.5, lat: -0.5, emoji: "🪸", what: "The richest coral reefs on Earth" },
  { name: "Borneo", lon: 116.0, lat: 1.0, emoji: "🦧", what: "Orangutans and pygmy elephants in ancient rainforest" },
  { name: "Komodo", lon: 119.5, lat: -8.55, emoji: "🦎", what: "Komodo dragons, the largest living lizards" },
  { name: "Kaziranga", lon: 93.4, lat: 26.6, emoji: "🦏", what: "Two-thirds of the world's greater one-horned rhinos" },
  { name: "Ranthambore", lon: 76.5, lat: 26.0, emoji: "🐅", what: "Tigers among ruined forts" },
  { name: "Wolong", lon: 103.2, lat: 31.0, emoji: "🐼", what: "Giant pandas in the bamboo forests of Sichuan" },
  { name: "Svalbard", lon: 16.0, lat: 78.5, emoji: "🐻‍❄️", what: "Polar bears, walruses and Arctic foxes" },
  { name: "South Georgia", lon: -36.5, lat: -54.3, emoji: "🐧", what: "Hundreds of thousands of king penguins" },
  { name: "Antarctic Peninsula", lon: -62.0, lat: -64.5, emoji: "🐧", what: "Penguins, seals and feeding humpbacks" },
  { name: "Kamchatka", lon: 159.0, lat: 54.5, emoji: "🐻", what: "Brown bears and salmon rivers under volcanoes" },
  { name: "Scottish Highlands", lon: -4.8, lat: 57.1, emoji: "🦌", what: "Red deer, golden eagles and pine martens" },
  { name: "Doñana", lon: -6.4, lat: 37.0, emoji: "🐈", what: "The rare Iberian lynx and a million migrating birds" },
  { name: "Danube Delta", lon: 29.3, lat: 45.1, emoji: "🦩", what: "Europe's biggest wetland: pelicans and 300 bird species" },
  { name: "Lake Nakuru", lon: 36.08, lat: -0.37, emoji: "🦩", what: "Flamingos by the hundred thousand" },
  { name: "Sea of Cortez", lon: -110.5, lat: 26.0, emoji: "🐳", what: "Blue whales, whale sharks and mobula rays" },
  { name: "Ningaloo", lon: 113.8, lat: -22.6, emoji: "🦈", what: "Whale sharks along a fringing reef" },
  { name: "Kakadu", lon: 132.4, lat: -12.8, emoji: "🐊", what: "Saltwater crocodiles and a third of Australia's birds" },
  { name: "Fiordland", lon: 167.5, lat: -45.4, emoji: "🐬", what: "Dolphins, fur seals and rare penguins in the sounds" },
];

export const MIGRATIONS: Migration[] = [
  { name: "Wildebeest", emoji: "🐃", color: "#e0a458", about: "About 1.5 million wildebeest circle the Serengeti and Maasai Mara each year, following the rain",
    pts: [[35.0, -3.1], [34.6, -2.5], [34.5, -1.9], [35.1, -1.5], [35.3, -2.0], [35.3, -2.6], [35.0, -3.1]] },
  { name: "Arctic tern", emoji: "🐦", color: "#8ecae6", about: "The longest migration of any animal: pole to pole and back, about 70,000 km a year",
    pts: [[-20, 72], [-15, 55], [-25, 30], [-30, 5], [-15, -20], [0, -45], [20, -65]] },
  { name: "Monarch butterfly", emoji: "🦋", color: "#fb8500", about: "Millions fly up to 4,000 km from Canada and the US to winter in Mexico's fir forests",
    pts: [[-80, 45], [-86, 40], [-93, 35], [-98, 28], [-100.3, 19.6]] },
  { name: "Humpback whales (Pacific)", emoji: "🐋", color: "#48cae4", about: "Summer in Alaska's feeding grounds, winter in Hawaii to give birth",
    pts: [[-150, 58], [-152, 45], [-155, 30], [-156.5, 20.8]] },
  { name: "Grey whales", emoji: "🐳", color: "#90e0ef", about: "From the Arctic to Baja California's lagoons: one of the longest mammal migrations",
    pts: [[-168, 66], [-155, 58], [-135, 52], [-125, 42], [-118, 30], [-113.5, 26.7]] },
  { name: "Caribou (Porcupine herd)", emoji: "🦌", color: "#bc6c25", about: "About 200,000 caribou cross Alaska and the Yukon to calve on the coastal plain",
    pts: [[-137, 65.5], [-140, 67], [-143, 68.5], [-144, 69.6]] },
  { name: "Sardine run", emoji: "🐟", color: "#56cfe1", about: "Billions of sardines move up South Africa's east coast in winter, chased by dolphins, sharks and gannets",
    pts: [[22, -34.5], [26, -34], [30, -32], [32.5, -29]] },
  { name: "Christmas Island red crabs", emoji: "🦀", color: "#e63946", about: "Tens of millions of crabs march from the forest to the sea to breed",
    pts: [[105.6, -10.45], [105.7, -10.5]] },
  { name: "Leatherback turtles", emoji: "🐢", color: "#52b788", about: "Swim from nesting beaches in Indonesia across the Pacific to feed off California",
    pts: [[132, -0.5], [150, 10], [175, 25], [-160, 33], [-135, 36], [-123, 36.5]] },
  { name: "Bar-tailed godwit", emoji: "🪶", color: "#ffd166", about: "Flies nonstop from Alaska to New Zealand: about 11,000 km in nine days",
    pts: [[-162, 61], [-170, 45], [-178, 25], [178, 0], [175, -25], [174.8, -37]] },
  { name: "Salmon run (Bristol Bay)", emoji: "🐟", color: "#ff6b6b", about: "Tens of millions of sockeye return from the ocean to the rivers where they hatched",
    pts: [[-170, 55], [-163, 57], [-157, 58.7], [-155, 59.5]] },
];
