// Lists every package the shipped app depends on (directly or through others), with its licence, for due
// diligence and for the attributions licences ask for. Run: node scripts/licenses.mjs > docs/diligence/third-party-licenses.md
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const seen = new Map();
const walk = (name, from) => {
  if (seen.has(name)) return;
  const dir = [join(from, "node_modules", name), join(root, "node_modules", name)].find((d) => existsSync(join(d, "package.json")));
  if (!dir) return;
  const p = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  const lic = typeof p.license === "string" ? p.license : p.license?.type ?? (Array.isArray(p.licenses) ? p.licenses.map((l) => l.type ?? l).join(" OR ") : "UNKNOWN");
  seen.set(name, { version: p.version, license: lic, repo: typeof p.repository === "string" ? p.repository : p.repository?.url ?? p.homepage ?? "" });
  for (const d of Object.keys(p.dependencies ?? {})) walk(d, dir);
};
for (const d of Object.keys(pkg.dependencies ?? {})) walk(d, root);
const rows = [...seen].sort(([a], [b]) => a.localeCompare(b));
const by = new Map();
for (const [, v] of rows) by.set(v.license, (by.get(v.license) ?? 0) + 1);
const flag = (l) => (/GPL|AGPL|SSPL|BUSL|Commons Clause|UNKNOWN|CC-BY-NC/i.test(l) && !/LGPL/i.test(l) ? " ⚠️" : "");
console.log(`# Third-party software licences\n\nPackages shipped in the app (runtime dependencies and everything they depend on), generated by \`scripts/licenses.mjs\` on ${new Date().toISOString().slice(0, 10)}. Data and service licences are in [data-licensing.md](../data-licensing.md).\n`);
console.log(`## Summary\n\n| Licence | Packages |\n|---|---|\n${[...by].sort((a, b) => b[1] - a[1]).map(([l, n]) => `| ${l}${flag(l)} | ${n} |`).join("\n")}\n`);
console.log(`Anything marked ⚠️ needs a look: copyleft (GPL/AGPL) or unknown terms can carry obligations for a commercial product.\n`);
console.log(`## Packages\n\n| Package | Version | Licence |\n|---|---|---|\n${rows.map(([n, v]) => `| ${n} | ${v.version} | ${v.license}${flag(v.license)} |`).join("\n")}`);
